name: Report a bug
description: Report encountered problem
title: "[Bug] ISSUE_TITLE"
labels: [bug]

body:
  - type: checkboxes
    attributes:
      label: DO NOT REMOVE OR SKIP THE TEMPLATE
      description: Fill all fields even if you think it is irrelevant for the issue
      options:
        - label: I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field
          required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a well enough worded description
      placeholder: Provide any additional information, any suggested solutions, and as much context and examples as possible
    validations:
      required: true
  - type: textarea
    id: verboselog
    attributes:
      label: Provide verbose output that demonstrated the problem (use -verbose | Edit -> Verbose log)
      description: |
        It should start like this:
      placeholder: |
        Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
        Base args: .../src/ruxx.py
        My args: Cmd: sfw -module rs -path '.../dl/1' -threads 3 -prefix -append_info -verbose
      render: shell
    validations:
      required: true
