# coding=UTF-8
"""
Author: trickerer (https://github.com/trickerer, https://github.com/trickerer01)
"""
#########################################
#
#

# native
from base64 import b64decode
from json import loads
from re import compile as re_compile
from typing import Pattern, Dict, List

# internal
from app_gui_defines import UNDERSCORE
from app_re import re_replace_symbols, re_tags_exclude_major1, re_tags_exclude_major2, re_numbered_or_counted_tag
from app_utils import trim_undersores

__all__ = ('append_filtered_tags',)

re_meta_group = re_compile(r'^([^(]+)\(([^)]+)\).*?$')
re_not_a_letter = re_compile(r'[^a-z]+')


TAG_ALIASES_STR = (
    'eyJidW5ueV9ib3kiOiAiMStib3lzIiwgIm1hbGUiOiAiMStib3lzIiwgIm1hbGVfc29sbyI6ICIxK2JveXMiLCAibWFsZWRvbSI6ICIxK2JveXMiLCAibWFsZXN1YiI6ICIxK2'
    'JveXMiLCAibW9uc3Rlcl9ib3kiOiAiMStib3lzIiwgIm9yY19tYWxlIjogIjErYm95cyIsICIxMDFfZGFsbWF0aWFuX3N0cmVldCI6ICIxMDFfZGFsbWF0aWFucyIsICIybWFs'
    'ZSI6ICIyYm95cyIsICIybWFsZXMiOiAiMmJveXMiLCAiM21hbGUiOiAiM2JveXMiLCAiNjlfcG9zZSI6ICI2OSIsICI2OV9wb3NpdGlvbiI6ICI2OSIsICI2OV9zdGFuZGluZy'
    'I6ICI2OSIsICJzdGFuZGluZ182OSI6ICI2OSIsICJhbnl0aGluZ19kaWZmdXNpb24iOiAiYWlfZ2VuZXJhdGVkIiwgImNoaWxsX2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQi'
    'LCAiaGVudGFpX2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQiLCAibGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJtYWlfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZC'
    'IsICJuYWlfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJwaXJhdGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJybnN0YWJsZV9kaWZmdXNpb24iOiAiYWlfZ2Vu'
    'ZXJhdGVkIiwgInNlbnN1YWxfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJzdGFibGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJ0YWJsZV9kaWZmdXNpb24iOi'
    'AiYWlfZ2VuZXJhdGVkIiwgIndhaWZ1X2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQiLCAieXVraV9kaWZmdXNpb24iOiAiYWlfZ2VuZXJhdGVkIiwgInhlbm9tb3JwaCI6ICJh'
    'bGllbiIsICJhbmFsX3NleCI6ICJhbmFsIiwgImFuYWxpbmd1cyI6ICJhbmFsIiwgImFuaWxpbmd1cyI6ICJhbmFsIiwgInJlY3R1bSI6ICJhbmFsIiwgInNzYmJ3IjogImJidy'
    'IsICJiZHNtX2NvbGxhciI6ICJiZHNtIiwgImJkc21fZ2VhciI6ICJiZHNtIiwgImJkc21faGFybmVzcyI6ICJiZHNtIiwgImJkc21fb3V0Zml0IjogImJkc20iLCAiYmRzbV9y'
    'b29tIjogImJkc20iLCAiYmRzbV9zdWl0IjogImJkc20iLCAiYnNkbSI6ICJiZHNtIiwgIm1hc29jaGlzbSI6ICJiZHNtIiwgIm1hc29jaGlzdCI6ICJiZHNtIiwgImFsbGlnYX'
    'RvciI6ICJiZWFzdCIsICJhbmltYWwiOiAiYmVhc3QiLCAiZmVyYWwiOiAiYmVhc3QiLCAiZmVyYWxfb25fZmVyYWwiOiAiYmVhc3QiLCAiZmVyYWxfcGVuZXRyYXRlZCI6ICJi'
    'ZWFzdCIsICJmZXJhbF9wZW5ldHJhdGluZyI6ICJiZWFzdCIsICJtYW1tYWwiOiAiYmVhc3QiLCAibWVwaGl0aWQiOiAiYmVhc3QiLCAib2NlbG90IjogImJlYXN0IiwgInByb2'
    'N5b25pZCI6ICJiZWFzdCIsICJyZXB0aWxlIjogImJlYXN0IiwgInJvZGVudCI6ICJiZWFzdCIsICJlZ2dfYnVsZ2UiOiAiYmVsbHlfYnVsZ2UiLCAic3RvbWFjaF9idWxnZSI6'
    'ICJiZWxseV9idWxnZSIsICJmZW1hbGVfb25fZmVyYWwiOiAiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9hbnRocm8iOiAiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9mZW1hbGUiOi'
    'AiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9odW1hbiI6ICJiZXN0aWFsaXR5IiwgImZlcmFsX29uX21hbGUiOiAiYmVzdGlhbGl0eSIsICJodW1hbl9vbl9mZXJhbCI6ICJiZXN0'
    'aWFsaXR5IiwgIm1hbGVfb25fZmVyYWwiOiAiYmVzdGlhbGl0eSIsICJ6b29waGlsaWEiOiAiYmVzdGlhbGl0eSIsICJiaW1ib19hbnRocm8iOiAiYmltYm8iLCAiYmltYm9fYm'
    '9keSI6ICJiaW1ibyIsICJiaW1ib19mdXRhbmFyaSI6ICJiaW1ibyIsICJiaW1ib19saXAiOiAiYmltYm8iLCAiYmltYm9fbGlwcyI6ICJiaW1ibyIsICJiaW1ib19zdWNjdWJ1'
    'cyI6ICJiaW1ibyIsICJiaW1ib2VkIjogImJpbWJvIiwgImJpbWJvZmljYXRpb24iOiAiYmltYm8iLCAiYmltYm9maWVkIjogImJpbWJvIiwgImJpbWJvcyI6ICJiaW1ibyIsIC'
    'JiaWtlc3VpdCI6ICJib2R5c3VpdCIsICJiaW9zdWl0IjogImJvZHlzdWl0IiwgImJpdGNoX3N1aXQiOiAiYm9keXN1aXQiLCAiYml0Y2hzdWl0IjogImJvZHlzdWl0IiwgImJ1'
    'bm55X3N1aXQiOiAiYm9keXN1aXQiLCAiYnVubnlzdWl0IjogImJvZHlzdWl0IiwgImNhdF9zdWl0IjogImJvZHlzdWl0IiwgImNhdHN1aXQiOiAiYm9keXN1aXQiLCAiZ2ltcF'
    '9zdWl0IjogImJvZHlzdWl0IiwgImdpbXBzdWl0IjogImJvZHlzdWl0IiwgInBsdWdfc3VpdCI6ICJib2R5c3VpdCIsICJwbHVnc3VpdCI6ICJib2R5c3VpdCIsICJzd2ltX3N1'
    'aXQiOiAiYm9keXN1aXQiLCAic3dpbXN1aXQiOiAiYm9keXN1aXQiLCAiemVyb19zdWl0IjogImJvZHlzdWl0IiwgInplcm9zdWl0IjogImJvZHlzdWl0IiwgImJvdW5kIjogIm'
    'JvbmRhZ2UiLCAiYm91bmRfYXJtcyI6ICJib25kYWdlIiwgImJvdW5kX2ZlZXQiOiAiYm9uZGFnZSIsICJib3VuZF9oYW5kcyI6ICJib25kYWdlIiwgImJvdW5kX2xlZ3MiOiAi'
    'Ym9uZGFnZSIsICJib3VuZF9uZWNrIjogImJvbmRhZ2UiLCAiYm91bmRfcGVuaXMiOiAiYm9uZGFnZSIsICJib3VuZF90b19iZWQiOiAiYm9uZGFnZSIsICJib3VuZF90b19jaG'
    'FpciI6ICJib25kYWdlIiwgImJvdW5kX3dyaXN0cyI6ICJib25kYWdlIiwgImJyZWFzdF9ib25kYWdlIjogImJvbmRhZ2UiLCAiY2hhaXJfYm9uZGFnZSI6ICJib25kYWdlIiwg'
    'Im11bW1pZmljYXRpb24iOiAiYm9uZGFnZSIsICJtdW1taWZpZWQiOiAiYm9uZGFnZSIsICJwcmVkaWNhbWVudF9ib25kYWdlIjogImJvbmRhZ2UiLCAicmVzdHJhaW4iOiAiYm'
    '9uZGFnZSIsICJyZXN0cmFpbmVkIjogImJvbmRhZ2UiLCAicmVzdHJhaW50IjogImJvbmRhZ2UiLCAicmVzdHJhaW50cyI6ICJib25kYWdlIiwgInJpYmJvbl9ib25kYWdlIjog'
    'ImJvbmRhZ2UiLCAicm9wZV9ib25kYWdlIjogImJvbmRhZ2UiLCAic2hpYmFyaSI6ICJib25kYWdlIiwgInN0ZWVsX2JvbmRhZ2UiOiAiYm9uZGFnZSIsICJzdHJhcHBhZG8iOi'
    'AiYm9uZGFnZSIsICJzdHJhcHBlZF9kb3duIjogImJvbmRhZ2UiLCAic3VzcGVuZGVkIjogImJvbmRhZ2UiLCAic3VzcGVuc2lvbiI6ICJib25kYWdlIiwgInN1c3BlbnNpb25f'
    'Ym9uZGFnZSI6ICJib25kYWdlIiwgInRhaWxfYm9uZGFnZSI6ICJib25kYWdlIiwgInRhcGVfYm9uZGFnZSI6ICJib25kYWdlIiwgIndlYl9ib25kYWdlIjogImJvbmRhZ2UiLC'
    'AiYm92aW5lIjogImJvdmlkIiwgImNhbmluIjogImNhbmlkIiwgImNhbmluZSI6ICJjYW5pZCIsICJjYW5pcyI6ICJjYW5pZCIsICJjb2xsaWUiOiAiY2FuaWQiLCAiZGlyZV93'
    'b2xmIjogImNhbmlkIiwgImRvYmVybWFuIjogImNhbmlkIiwgImh1c2t5IjogImNhbmlkIiwgImxhYnJhZG9yIjogImNhbmlkIiwgIm1hbGFtdXRlIjogImNhbmlkIiwgIm1hc3'
    'RpZmYiOiAiY2FuaWQiLCAicGl0X2J1bGwiOiAiY2FuaWQiLCAicGl0YnVsbCI6ICJjYW5pZCIsICJwb29kbGUiOiAiY2FuaWQiLCAicmV0cmlldmVyIjogImNhbmlkIiwgInNh'
    'bW95ZWQiOiAiY2FuaWQiLCAic3BhbmllbCI6ICJjYW5pZCIsICJ3b2xmIjogImNhbmlkIiwgIndvbGZkb2ciOiAiY2FuaWQiLCAiYWJkdWN0ZWQiOiAiY2FwdHVyZWQiLCAiYW'
    'JkdWN0aW9uIjogImNhcHR1cmVkIiwgImFycmVzdGVkIjogImNhcHR1cmVkIiwgImNhZ2VkIjogImNhcHR1cmVkIiwgImNhcHRpdmUiOiAiY2FwdHVyZWQiLCAiY2FwdGl2aXR5'
    'IjogImNhcHR1cmVkIiwgImNhcHR1cmUiOiAiY2FwdHVyZWQiLCAiY2hhaW5lZCI6ICJjYXB0dXJlZCIsICJkZXRhaW5lZCI6ICJjYXB0dXJlZCIsICJqYWlsZWQiOiAiY2FwdH'
    'VyZWQiLCAia2lkbmFwIjogImNhcHR1cmVkIiwgImtpZG5hcHBlZCI6ICJjYXB0dXJlZCIsICJraWRuYXBwaW5nIjogImNhcHR1cmVkIiwgInNoYWNrbGVkIjogImNhcHR1cmVk'
    'IiwgInRyYXBwZWQiOiAiY2FwdHVyZWQiLCAiY2F0Z2lybCI6ICJjYXRfZ2lybCIsICJkZWVyX3RhdXIiOiAiY2VudGF1ciIsICJkZWVydGF1ciI6ICJjZW50YXVyIiwgImNlcn'
    'ZpbmUiOiAiY2VydmlkIiwgImJsdWVfY3VtIjogImN1bSIsICJjdW1fYmF0aCI6ICJjdW0iLCAiY3VtX2JlbGx5IjogImN1bSIsICJjdW1fYnViYmxlIjogImN1bSIsICJjdW1f'
    'YnVja2V0IjogImN1bSIsICJjdW1fY292ZXJlZCI6ICJjdW0iLCAiY3VtX2RyaW5raW5nIjogImN1bSIsICJjdW1fZHJpcCI6ICJjdW0iLCAiY3VtX2RyaXBwaW5nIjogImN1bS'
    'IsICJjdW1fZmlsbGVkIjogImN1bSIsICJjdW1fZmxvb2QiOiAiY3VtIiwgImN1bV9mcm9tX2FzcyI6ICJjdW0iLCAiY3VtX2Zyb21fcHVzc3kiOiAiY3VtIiwgImN1bV9nbGF6'
    'ZSI6ICJjdW0iLCAiY3VtX2h1bmdyeSI6ICJjdW0iLCAiY3VtX2luX2FudXMiOiAiY3VtIiwgImN1bV9pbl9hc3MiOiAiY3VtIiwgImN1bV9pbl9jbG90aGVzIjogImN1bSIsIC'
    'JjdW1faW5fY29uZG9tIjogImN1bSIsICJjdW1faW5fY29udGFpbmVyIjogImN1bSIsICJjdW1faW5faGFpciI6ICJjdW0iLCAiY3VtX2luX21vdXRoIjogImN1bSIsICJjdW1f'
    'aW5fbm9zZSI6ICJjdW0iLCAiY3VtX2luX3B1c3N5IjogImN1bSIsICJjdW1faW5fdGhyb2F0IjogImN1bSIsICJjdW1faW5fdXRlcnVzIjogImN1bSIsICJjdW1faW5zaWRlIj'
    'ogImN1bSIsICJjdW1famFyIjogImN1bSIsICJjdW1fa2lzcyI6ICJjdW0iLCAiY3VtX2xlYWsiOiAiY3VtIiwgImN1bV9sZWFraW5nIjogImN1bSIsICJjdW1fbGljayI6ICJj'
    'dW0iLCAiY3VtX21pbGtpbmciOiAiY3VtIiwgImN1bV9vbl9hc3MiOiAiY3VtIiwgImN1bV9vbl9iYWxscyI6ICJjdW0iLCAiY3VtX29uX2JvZHkiOiAiY3VtIiwgImN1bV9vbl'
    '9icmVhc3RzIjogImN1bSIsICJjdW1fb25fYnV0dCI6ICJjdW0iLCAiY3VtX29uX2NoZXN0IjogImN1bSIsICJjdW1fb25fY2xvdGhlcyI6ICJjdW0iLCAiY3VtX29uX2ZhY2Ui'
    'OiAiY3VtIiwgImN1bV9vbl9mZWV0IjogImN1bSIsICJjdW1fb25fZ3JvdW5kIjogImN1bSIsICJjdW1fb25faGFpciI6ICJjdW0iLCAiY3VtX29uX2hhbmQiOiAiY3VtIiwgIm'
    'N1bV9vbl9sZWciOiAiY3VtIiwgImN1bV9vbl9wZW5pcyI6ICJjdW0iLCAiY3VtX29uX3NlbGYiOiAiY3VtIiwgImN1bV9vbl9zdG9tYWNoIjogImN1bSIsICJjdW1fb25fdG9u'
    'Z3VlIjogImN1bSIsICJjdW1fcG9vbCI6ICJjdW0iLCAiY3VtX3B1ZGRsZSI6ICJjdW0iLCAiY3VtX3JpbmciOiAiY3VtIiwgImN1bV9zaG90IjogImN1bSIsICJjdW1fc3BhdH'
    'RlciI6ICJjdW0iLCAiY3VtX3NxdWlydCI6ICJjdW0iLCAiY3VtX3N0YWluIjogImN1bSIsICJjdW1fc3RyYW5kIjogImN1bSIsICJjdW1fc3RyaW5nIjogImN1bSIsICJjdW1f'
    'c3dhbGxvdyI6ICJjdW0iLCAiY3VtX3N3YXAiOiAiY3VtIiwgImN1bWRyaXAiOiAiY3VtIiwgImN1bWR1bXAiOiAiY3VtIiwgImN1bWx1YmUiOiAiY3VtIiwgImN1bW1pbmciOi'
    'AiY3VtIiwgImN1bXBvb2wiOiAiY3VtIiwgImN1bXNlYSI6ICJjdW0iLCAiY3Vtc2hvdCI6ICJjdW0iLCAiY3Vtc2x1dCI6ICJjdW0iLCAiY3Vtc3RyaW5nIjogImN1bSIsICJn'
    'cmVlbl9jdW0iOiAiY3VtIiwgInByZWN1bSI6ICJjdW0iLCAidGhpY2tfY3VtIjogImN1bSIsICJoYW5hX3NvbmciOiAiZC52YSIsICJkYW5nYW5yb25wYV92MyI6ICJkYW5nYW'
    '5yb25wYSIsICJuZXdfZGFuZ2Fucm9ucGFfdjMiOiAiZGFuZ2Fucm9ucGEiLCAic3VwZXJfZGFuZ2Fucm9ucGFfMiI6ICJkYW5nYW5yb25wYSIsICJkcm93X2VsZiI6ICJkYXJr'
    'X2VsZiIsICJkdW5tZXIiOiAiZGFya19lbGYiLCAiZHVubWVyX2VsZiI6ICJkYXJrX2VsZiIsICJkZWFkIjogImRlYXRoIiwgInJvZV9kZWVyIjogImRlZXIiLCAiZGVsdGFydW'
    '5lX2NoYXB0ZXJfMSI6ICJkZWx0YXJ1bmUiLCAiZGVsdGFydW5lX2NoYXB0ZXJfMiI6ICJkZWx0YXJ1bmUiLCAiZGVsdGFydW5lX2NoYXB0ZXJfMyI6ICJkZWx0YXJ1bmUiLCAi'
    'ZGVtb25fYm95IjogImRlbW9uIiwgImRlbW9uX2h1bWFub2lkIjogImRlbW9uIiwgImRlbW9ucyI6ICJkZW1vbiIsICJkZXZpbCI6ICJkZW1vbiIsICJkZXZpbF9naXJsIjogIm'
    'RlbW9uIiwgImVyZWRhciI6ICJkZW1vbiIsICJkZW1vbl9naXJsIjogImRlbW9uZXNzIiwgImRlbW9uX2dpcmxzIjogImRlbW9uZXNzIiwgImRlbW9uZ2lybCI6ICJkZW1vbmVz'
    'cyIsICJkZW1vbmdpcmxzIjogImRlbW9uZXNzIiwgImRlcnBfZXllcyI6ICJkZXJwIiwgImRvZ2dpcmwiOiAiZG9nX2dpcmwiLCAiZHdhcmZfZmVtYWxlIjogImR3YXJmIiwgIm'
    'VlbF9pbl9hc3MiOiAiZWVsIiwgImVlbF9pbl9wdXNzeSI6ICJlZWwiLCAiZWVsX2luX3VyZXRocmEiOiAiZWVsIiwgImVlbF9pbnNlcnRpb24iOiAiZWVsIiwgImVnZ19iaXJ0'
    'aCI6ICJlZ2ciLCAiZWdnX2Zyb21fYXNzIjogImVnZyIsICJlZ2dfZnJvbV9tb3V0aCI6ICJlZ2ciLCAiZWdnX2Zyb21fcHVzc3kiOiAiZWdnIiwgImVnZ19pbXBsYW50YXRpb2'
    '4iOiAiZWdnIiwgImVnZ19pbl9hc3MiOiAiZWdnIiwgImVnZ19pbl9tb3V0aCI6ICJlZ2ciLCAiZWdnX2luX3B1c3N5IjogImVnZyIsICJlZ2dfaW5zZXJ0aW9uIjogImVnZyIs'
    'ICJlZ2dfbGF5aW5nIjogImVnZyIsICJlZ2duYW50IjogImVnZyIsICJlZ2dzX2luX3N0b21hY2giOiAiZWdnIiwgIm9yYWxfZWdnX2ltcGxhbnRhdGlvbiI6ICJlZ2ciLCAiZW'
    'x2ZXMiOiAiZWxmIiwgImhpZ2hfZWxmIjogImVsZiIsICJ3b29kX2VsZiI6ICJlbGYiLCAiZXF1aW5lIjogImVxdWlkIiwgImZhY2Vfc2l0dGluZyI6ICJmYWNlc2l0dGluZyIs'
    'ICJmYWNlc2l0IjogImZhY2VzaXR0aW5nIiwgImZhY2VzaXR0aW5nX3BvdiI6ICJmYWNlc2l0dGluZyIsICJjdW1fZmFydCI6ICJmYXJ0IiwgImZhY2VfZmFydCI6ICJmYXJ0Ii'
    'wgImZhY2VmYXJ0IjogImZhcnQiLCAiZmFydF9jbG91ZCI6ICJmYXJ0IiwgImZhcnRfZmV0aXNoIjogImZhcnQiLCAiZmFydF9pbl9mYWNlIjogImZhcnQiLCAiZmFydF9pbl9t'
    'b3V0aCI6ICJmYXJ0IiwgImZhcnRfb25fZGljayI6ICJmYXJ0IiwgImZhcnRfb25fZmFjZSI6ICJmYXJ0IiwgImZhcnRfc25pZmZpbmciOiAiZmFydCIsICJmYXJ0aW5nX2luX2'
    'ZhY2UiOiAiZmFydCIsICJmYXJ0aW5nX2luX21vdXRoIjogImZhcnQiLCAiZmFydGluZ19vbl9mYWNlIjogImZhcnQiLCAiZmFydGpvYiI6ICJmYXJ0IiwgImZhcnRzIjogImZh'
    'cnQiLCAiZmVsaW5lIjogImZlbGlkIiwgImZlbGlzIjogImZlbGlkIiwgImZlbWJveXN1YiI6ICJmZW1ib3kiLCAiYW5hbF9maXN0aW5nIjogImZpc3RpbmciLCAiYXV0b2Zpc3'
    'RpbmciOiAiZmlzdGluZyIsICJkZWVwX2Zpc3RpbmciOiAiZmlzdGluZyIsICJkb3VibGVfZmlzdGluZyI6ICJmaXN0aW5nIiwgInNlbGZfZmlzdGluZyI6ICJmaXN0aW5nIiwg'
    'InZhZ2luYWxfZmlzdGluZyI6ICJmaXN0aW5nIiwgImZveGdpcmwiOiAiZm94X2dpcmwiLCAiYmxhY2tfZnVyIjogImZ1ciIsICJibHVlX2Z1ciI6ICJmdXIiLCAiYm9keV9mdX'
    'IiOiAiZnVyIiwgImJyb3duX2Z1ciI6ICJmdXIiLCAiZGFya19mdXIiOiAiZnVyIiwgImdyYXlfZnVyIjogImZ1ciIsICJncmVlbl9mdXIiOiAiZnVyIiwgImdyZXlfZnVyIjog'
    'ImZ1ciIsICJvcmFuZ2VfZnVyIjogImZ1ciIsICJwaW5rX2Z1ciI6ICJmdXIiLCAicHVycGxlX2Z1ciI6ICJmdXIiLCAicmVkX2Z1ciI6ICJmdXIiLCAidGFuX2Z1ciI6ICJmdX'
    'IiLCAid2V0X2Z1ciI6ICJmdXIiLCAid2hpdGVfZnVyIjogImZ1ciIsICJ5ZWxsb3dfZnVyIjogImZ1ciIsICJhbnRocm9fZm9jdXMiOiAiZnVycnkiLCAiYW50aHJvX29uX2Fu'
    'dGhybyI6ICJmdXJyeSIsICJhbnRocm9fb25fZmVyYWwiOiAiZnVycnkiLCAiYW50aHJvX29ubHkiOiAiZnVycnkiLCAiZnVycmVkX2RyYWdvbiI6ICJmdXJyeSIsICJmdXJyaW'
    'ZpY2F0aW9uIjogImZ1cnJ5IiwgImZ1cnJ5X2FzcyI6ICJmdXJyeSIsICJmdXJyeV9icmVhc3RzIjogImZ1cnJ5IiwgImZ1cnJ5X2VhcnMiOiAiZnVycnkiLCAiZnVycnlfZmVt'
    'YWxlIjogImZ1cnJ5IiwgImZ1cnJ5X2ludGVyc2V4IjogImZ1cnJ5IiwgImZ1cnJ5X21hbGUiOiAiZnVycnkiLCAiZnVycnlfb25seSI6ICJmdXJyeSIsICJmdXJyeV90YWlsIj'
    'ogImZ1cnJ5IiwgImZ1cnJ5ZmljYXRpb24iOiAiZnVycnkiLCAibWFtbWFsX2h1bWFub2lkIjogImZ1cnJ5IiwgInNjYWxpZSI6ICJmdXJyeSIsICJzZXh5ZnVyIjogImZ1cnJ5'
    'IiwgIndvcmdlbiI6ICJmdXJyeSIsICJ5aWZmIjogImZ1cnJ5IiwgInlpZmZpbmciOiAiZnVycnkiLCAiZnV0YV93aXRoX21hbGUiOiAiZnV0YV9vbl9tYWxlIiwgImZ1dGFuYX'
    'JpL21hbGUiOiAiZnV0YV9vbl9tYWxlIiwgImRlbW9uX2Z1dGEiOiAiZnV0YW5hcmkiLCAiZWxmX2Z1dGEiOiAiZnV0YW5hcmkiLCAiZnV0YS9jdW50Ym95IjogImZ1dGFuYXJp'
    'IiwgImZ1dGEvZmVtYWxlIjogImZ1dGFuYXJpIiwgImZ1dGEvZmVtYm95IjogImZ1dGFuYXJpIiwgImZ1dGEvZnV0YSI6ICJmdXRhbmFyaSIsICJmdXRhL21hbGUiOiAiZnV0YW'
    '5hcmkiLCAiZnV0YV8iOiAiZnV0YW5hcmkiLCAiZnV0YV9iYWxscyI6ICJmdXRhbmFyaSIsICJmdXRhX2NvY2siOiAiZnV0YW5hcmkiLCAiZnV0YV9mb2N1cyI6ICJmdXRhbmFy'
    'aSIsICJmdXRhX2dpYW50ZXNzIjogImZ1dGFuYXJpIiwgImZ1dGFfaXNfYmlnZ2VyIjogImZ1dGFuYXJpIiwgImZ1dGFfaXNfc21hbGxlciI6ICJmdXRhbmFyaSIsICJmdXRhX2'
    '1pbGYiOiAiZnV0YW5hcmkiLCAiZnV0YV9vbl9mZW1hbGUiOiAiZnV0YW5hcmkiLCAiZnV0YV9vbl9mdXRhIjogImZ1dGFuYXJpIiwgImZ1dGFfb25fdG9wIjogImZ1dGFuYXJp'
    'IiwgImZ1dGFfb25seSI6ICJmdXRhbmFyaSIsICJmdXRhX3BvdiI6ICJmdXRhbmFyaSIsICJmdXRhX3NhbnNfYmFsbHMiOiAiZnV0YW5hcmkiLCAiZnV0YV9zYW5zX3B1c3N5Ij'
    'ogImZ1dGFuYXJpIiwgImZ1dGFfc29sbyI6ICJmdXRhbmFyaSIsICJmdXRhX3N1YiI6ICJmdXRhbmFyaSIsICJmdXRhX3dpZmUiOiAiZnV0YW5hcmkiLCAiZnV0YV93aXRoX2Zl'
    'bWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhX3dpdGhfZmVtYm95IjogImZ1dGFuYXJpIiwgImZ1dGFfd2l0aF9mdXRhIjogImZ1dGFuYXJpIiwgImZ1dGFkb20iOiAiZnV0YW5hcm'
    'kiLCAiZnV0YW5hcmkvY3VudGJveSI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaS9mZW1hbGUiOiAiZnV0YW5hcmkiLCAiZnV0YW5hcmkvZmVtYm95IjogImZ1dGFuYXJpIiwgImZ1'
    'dGFuYXJpL2Z1dGEiOiAiZnV0YW5hcmkiLCAiZnV0YW5hcmlfcGVuZXRyYXRlZCI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaV9wZW5ldHJhdGluZyI6ICJmdXRhbmFyaSIsICJmdX'
    'RhbmFyaV9wb3YiOiAiZnV0YW5hcmkiLCAiZnV0YW5hcmlfdHJhbnNmb3JtYXRpb24iOiAiZnV0YW5hcmkiLCAiZnV0YW5hcml6YXRpb24iOiAiZnV0YW5hcmkiLCAiZnV0YXN1'
    'YiI6ICJmdXRhbmFyaSIsICJtaW5pZnV0YSI6ICJmdXRhbmFyaSIsICJzb2xlX2Z1dGEiOiAiZnV0YW5hcmkiLCAic29sb19mdXRhIjogImZ1dGFuYXJpIiwgImJhbGxfZ2FnIj'
    'ogImdhZyIsICJiYWxsZ2FnIjogImdhZyIsICJiYW1ib29fZ2FnIjogImdhZyIsICJiaXRfZ2FnIjogImdhZyIsICJiaXRlX2dhZyI6ICJnYWciLCAiYmxhY2tfYmFsbF9nYWci'
    'OiAiZ2FnIiwgImJsdWVfYmFsbF9nYWciOiAiZ2FnIiwgImJvbmVfZ2FnIjogImdhZyIsICJjbGVhdmVfZ2FnIjogImdhZyIsICJjbG90aF9nYWciOiAiZ2FnIiwgImNvY2tfZ2'
    'FnIjogImdhZyIsICJkZW50YWxfZ2FnIjogImdhZyIsICJkaWxkb19nYWciOiAiZ2FnIiwgImdhZ19iYWxsIjogImdhZyIsICJnYWdfYm9uZGFnZSI6ICJnYWciLCAiZ2FnX2hh'
    'cm5lc3MiOiAiZ2FnIiwgImdhZ19tYXNrIjogImdhZyIsICJnYWdnZWQiOiAiZ2FnIiwgImdhZ2dpbmciOiAiZ2FnIiwgImhhbmRnYWciOiAiZ2FnIiwgImhhcm5lc3NfYmFsbF'
    '9nYWciOiAiZ2FnIiwgImhhcm5lc3NfYml0X2dhZyI6ICJnYWciLCAiaGFybmVzc19iaXRlX2dhZyI6ICJnYWciLCAiaGFybmVzc19nYWciOiAiZ2FnIiwgImhhcm5lc3Nfcmlu'
    'Z19nYWciOiAiZ2FnIiwgImltcHJvdmlzZWRfZ2FnIjogImdhZyIsICJtb3V0aF9nYWciOiAiZ2FnIiwgIm11enpsZV9nYWciOiAiZ2FnIiwgIm9uYWhvbGVfZ2FnIjogImdhZy'
    'IsICJvcGVuX21vdXRoX2dhZyI6ICJnYWciLCAib3RtX2dhZyI6ICJnYWciLCAib3Zlcl90aGVfbW91dGhfZ2FnIjogImdhZyIsICJvdmVyX3RoZV9ub3NlX2dhZyI6ICJnYWci'
    'LCAicGFuZWxfZ2FnIjogImdhZyIsICJwYW50eV9nYWciOiAiZ2FnIiwgInBpbmtfYmFsbF9nYWciOiAiZ2FnIiwgInBsdWdfZ2FnIjogImdhZyIsICJwdXJwbGVfYmFsbF9nYW'
    'ciOiAiZ2FnIiwgInJlZF9iYWxsX2dhZyI6ICJnYWciLCAicmluZ19nYWciOiAiZ2FnIiwgInJvcGVfZ2FnIjogImdhZyIsICJyb3BlZ2FnIjogImdhZyIsICJzaGFyZWRfZ2Fn'
    'IjogImdhZyIsICJzdHVmZmVkX21vdXRoX2dhZyI6ICJnYWciLCAidGFwZV9nYWciOiAiZ2FnIiwgInRlbnRhY2xlX2dhZyI6ICJnYWciLCAid2ViX2dhZyI6ICJnYWciLCAid2'
    'hpdGVfYmFsbF9nYWciOiAiZ2FnIiwgImdhbmdfYmFuZyI6ICJnYW5nYmFuZyIsICJnYW5nX3JhcGUiOiAiZ2FuZ2JhbmciLCAiZ2FuZ3JhcGUiOiAiZ2FuZ2JhbmciLCAiZ2Fu'
    'Z3JhcGVkIjogImdhbmdiYW5nIiwgImFuYWxfZ2FwZSI6ICJnYXBlIiwgImJpZ19nYXBlIjogImdhcGUiLCAiZ2FwaW5nIjogImdhcGUiLCAiZ2FwaW5nX2FudXMiOiAiZ2FwZS'
    'IsICJnYXBpbmdfYXNzIjogImdhcGUiLCAiZ2FwaW5nX2Nsb2FjYSI6ICJnYXBlIiwgImdhcGluZ19uaXBwbGUiOiAiZ2FwZSIsICJnYXBpbmdfbmlwcGxlcyI6ICJnYXBlIiwg'
    'ImdhcGluZ19wdXN5eSI6ICJnYXBlIiwgImdhcGluZ191cmV0aHJhIjogImdhcGUiLCAiaHVnZV9nYXBlIjogImdhcGUiLCAiYmFyYSI6ICJnYXkiLCAiYmFyYV90aWRkaWVzIj'
    'ogImdheSIsICJiYXJhX3RpdHMiOiAiZ2F5IiwgImJhcmFrYSI6ICJnYXkiLCAiYmFyYWtpbmciOiAiZ2F5IiwgImJhcmFsdXN0IjogImdheSIsICJiYXJhc3Vpc2hvdSI6ICJn'
    'YXkiLCAiYmFyYXlvdCI6ICJnYXkiLCAiYmFyYXpva3UiOiAiZ2F5IiwgImJpc2V4dWFsX21hbGUiOiAiZ2F5IiwgImdheV9hbmFsX21hc3R1cmJhdGlvbiI6ICJnYXkiLCAiZ2'
    'F5X2JhciI6ICJnYXkiLCAiZ2F5X2JlYXIiOiAiZ2F5IiwgImdheV9ibG93am9iIjogImdheSIsICJnYXlfZGVuaWFsIjogImdheSIsICJnYXlfZG9ja2luZyI6ICJnYXkiLCAi'
    'Z2F5X2RvbWluYXRpb24iOiAiZ2F5IiwgImdheV9oYW5kam9iIjogImdheSIsICJnYXlfaGFyZW0iOiAiZ2F5IiwgImdheV9vcmd5IjogImdheSIsICJnYXlfcG9ybnN0YXIiOi'
    'AiZ2F5IiwgImdheV9wcmlkZSI6ICJnYXkiLCAiZ2F5X3ByaWRlX2NvbG9ycyI6ICJnYXkiLCAiZ2F5X3NleCI6ICJnYXkiLCAiZ2F5X3NvdW5kIjogImdheSIsICJnYXlfdG9f'
    'c3RyYWlnaHQiOiAiZ2F5IiwgImdheV93aXRoX3dvbWFuIjogImdheSIsICJnYXlfd3Jlc3RsaW5nIjogImdheSIsICJnYXl0b3IiOiAiZ2F5IiwgIm1lbl9raXNzaW5nIjogIm'
    'dheSIsICJnaXJhZmZlIjogImdpcmFmZmlkIiwgImdscHJ5X2hvbGUiOiAiZ2xvcnlob2xlIiwgImdvb2dpcmwiOiAiZ29vX2dpcmwiLCAic2xpbWVfZ2lybCI6ICJnb29fZ2ly'
    'bCIsICJzbGltZWdpcmwiOiAiZ29vX2dpcmwiLCAiZ290aGlmaWVkIjogImdvdGgiLCAibWFyZSI6ICJob3JzZSIsICJwb255IjogImhvcnNlIiwgInN0YWxsaW9uIjogImhvcn'
    'NlIiwgImh5ZW5hIjogImh5YWVuaWQiLCAiaWd1YW5hIjogImlndWFuaWQiLCAiY2xvbmVjZXN0IjogImluY2VzdCIsICJpbXBsaWVkX2luY2VzdCI6ICJpbmNlc3QiLCAibW9t'
    'Y2VzdCI6ICJpbmNlc3QiLCAic2VsZmNlc3QiOiAiaW5jZXN0IiwgInR3aW5jZXN0IjogImluY2VzdCIsICJjdW1faW5mbGF0aW9uIjogImluZmxhdGlvbiIsICJjdW1mbGF0aW'
    '9uIjogImluZmxhdGlvbiIsICJlZ2dfaW5mbGF0aW9uIjogImluZmxhdGlvbiIsICJzbGltZV9pbmZsYXRpb24iOiAiaW5mbGF0aW9uIiwgImluanVyZSI6ICJpbmp1cnkiLCAi'
    'aW5qdXJlZCI6ICJpbmp1cnkiLCAiaW5qdXJlcyI6ICJpbmp1cnkiLCAiYXJhY2huaWQiOiAiaW5zZWN0IiwgImFydGhyb3BvZCI6ICJpbnNlY3QiLCAiYmVlIjogImluc2VjdC'
    'IsICJiZWVzIjogImluc2VjdCIsICJibG9hdGZseSI6ICJpbnNlY3QiLCAiY2VudGlwZWRlIjogImluc2VjdCIsICJjb2Nrcm9hY2giOiAiaW5zZWN0IiwgImNvY2tyb2FzaCI6'
    'ICJpbnNlY3QiLCAiZWFydGh3b3JtIjogImluc2VjdCIsICJnYXN0cm9wb2QiOiAiaW5zZWN0IiwgImhvcm5ldCI6ICJpbnNlY3QiLCAiaW5zZWN0b2lkIjogImluc2VjdCIsIC'
    'JsZWVjaCI6ICJpbnNlY3QiLCAibGVlY2hlcyI6ICJpbnNlY3QiLCAibG9jdXN0IjogImluc2VjdCIsICJsb2N1c3RzIjogImluc2VjdCIsICJtYWdnb3QiOiAiaW5zZWN0Iiwg'
    'Im1hZ2dvdHMiOiAiaW5zZWN0IiwgIm1hbnRpcyI6ICJpbnNlY3QiLCAibW9zcXVpdG8iOiAiaW5zZWN0IiwgIm1vdGgiOiAiaW5zZWN0IiwgInF1ZWVuX2JlZSI6ICJpbnNlY3'
    'QiLCAic3BpZGVyIjogImluc2VjdCIsICJ0YXJhbnR1bGEiOiAiaW5zZWN0IiwgInZlc3BpZCI6ICJpbnNlY3QiLCAid2FzcCI6ICJpbnNlY3QiLCAid2FzcHMiOiAiaW5zZWN0'
    'IiwgIndvcm0iOiAiaW5zZWN0IiwgIndvcm1zIjogImluc2VjdCIsICJrYWlfc2EiOiAia2Fpc2EiLCAiYmxhY2tfbGF0ZXgiOiAibGF0ZXgiLCAibGF0ZXhfYm9keXN1aXQiOi'
    'AibGF0ZXgiLCAibGF0ZXhfY2xvdGhpbmciOiAibGF0ZXgiLCAibGF0ZXhfZHJlc3MiOiAibGF0ZXgiLCAibGF0ZXhfZ2xvdmVzIjogImxhdGV4IiwgImxhdGV4X2xlZ2dpbmdz'
    'IjogImxhdGV4IiwgImxhdGV4X2xlZ3dlYXIiOiAibGF0ZXgiLCAibGF0ZXhfc3RvY2tpbmdzIjogImxhdGV4IiwgImxhdGV4X3N1aXQiOiAibGF0ZXgiLCAibGF0ZXhfdGhpZ2'
    'hoaWdodHMiOiAibGF0ZXgiLCAicnViYmVyIjogImxhdGV4IiwgInJ1YmJlcl9ib290cyI6ICJsYXRleCIsICJydWJiZXJfY2xvdGhpbmciOiAibGF0ZXgiLCAicnViYmVyX2ds'
    'b3ZlcyI6ICJsYXRleCIsICJydWJiZXJfc3VpdCI6ICJsYXRleCIsICJsZXpkb20iOiAibGVzYmlhbiIsICJsZXpzdWIiOiAibGVzYmlhbiIsICJ5dXJpIjogImxlc2JpYW4iLC'
    'AibGlvbmVzcyI6ICJsaW9uIiwgIm1hcmlvX2dvbGYiOiAibWFyaW8iLCAibWFyaW9fa2FydCI6ICJtYXJpbyIsICJtYXJpb19wYXJ0eSI6ICJtYXJpbyIsICJtYXJpb190ZW5u'
    'aXMiOiAibWFyaW8iLCAicGFwZXJfbWFyaW8iOiAibWFyaW8iLCAic3VwZXJfbWFyaW8iOiAibWFyaW8iLCAic3VwZXJfbWFyaW9fNjQiOiAibWFyaW8iLCAibXlfbGl0dGxlX3'
    'BvbnkiOiAibWxwIiwgIm15X2xpdHRsZV9wb255X2ZyaWVuZHNoaXBfaXNfbWFnaWMiOiAibWxwIiwgIm15X2xpdHRsZV9wb255X3RoZV9tb3ZpZSI6ICJtbHAiLCAiZ2FyZ295'
    'bGUiOiAibW9uc3RlciIsICJnYXJnb3lsZXMiOiAibW9uc3RlciIsICJtb3VzZWdpcmwiOiAibW91c2VfZ2lybCIsICJtdXN0ZWxhIjogIm11c3RlbGlkIiwgIm11c3RlbGluZS'
    'I6ICJtdXN0ZWxpZCIsICJuYXJ1dG86X3RoZV9sYXN0IjogIm5hcnV0byIsICJuYXJ1dG9fYm9tYiI6ICJuYXJ1dG8iLCAibmFydXRvX3NoaXBwdW5kZW4iOiAibmFydXRvIiwg'
    'Im5pZXI6X2F1dG9tYXRhIjogIm5pZXIiLCAibmllcl9yZXBsaWNhbnQiOiAibmllciIsICJrYWxkb3JlaSI6ICJuaWdodF9lbGYiLCAibnVtYnVoXzUiOiAibnVtYmFoXzUiLC'
    'AiYmxvd2pvYiI6ICJvcmFsIiwgImZhY2VfZnVjayI6ICJvcmFsIiwgImZhY2VfZnVja2luZyI6ICJvcmFsIiwgImZhY2VmdWNrIjogIm9yYWwiLCAiZmVsbGF0aW8iOiAib3Jh'
    'bCIsICJvcmFsX2NyZWFtcGllIjogIm9yYWwiLCAib3JhbF9pbnNlcnRpb24iOiAib3JhbCIsICJvcmFsX2tub3R0aW5nIjogIm9yYWwiLCAib3JhbF9tYXN0dXJiYXRpb24iOi'
    'Aib3JhbCIsICJvcmFsX3BlbmV0cmF0aW9uIjogIm9yYWwiLCAib3JhbF9yYXBlIjogIm9yYWwiLCAib3JhbF9zZXgiOiAib3JhbCIsICJzcGl0cm9hc3QiOiAib3JhbCIsICJz'
    'dWNraW5nIjogIm9yYWwiLCAidG9uZ3VlX2pvYiI6ICJvcmFsIiwgInRvbmd1ZWpvYiI6ICJvcmFsIiwgIjNzb21lIjogIm9yZ3kiLCAiNHNvbWUiOiAib3JneSIsICI1c29tZS'
    'I6ICJvcmd5IiwgIjZzb21lIjogIm9yZ3kiLCAiZml2ZXNvbWUiOiAib3JneSIsICJmb3Vyc29tZSI6ICJvcmd5IiwgImdyb3VwX3NleCI6ICJvcmd5IiwgInNpeHNvbWUiOiAi'
    'b3JneSIsICJ0aHJlZXNvbWUiOiAib3JneSIsICJwZXJzb25hXzNfcG9ydGFibGUiOiAicGVyc29uYV8zIiwgInBlcnNvbmFfNF9hcmVuYSI6ICJwZXJzb25hXzQiLCAicGVyc2'
    '9uYV80X3RoZV9nb2xkZW4iOiAicGVyc29uYV80IiwgInBlcnNvbmFfNV9yb3lhbCI6ICJwZXJzb25hXzUiLCAicGV0Z2lydGwiOiAicGV0X2dpcmwiLCAiYXNzaXN0ZWRfcGVl'
    'IjogInBpc3NpbmciLCAiZHJpbmtpbmdfcGVlIjogInBpc3NpbmciLCAibW91dGhfcGVlIjogInBpc3NpbmciLCAicGFudHlfcGVlIjogInBpc3NpbmciLCAicGVlaW5nIjogIn'
    'Bpc3NpbmciLCAic2l0dGluZ19wZWUiOiAicGlzc2luZyIsICJzdGFuZGluZ19wZWUiOiAicGlzc2luZyIsICJ1cmluYXRpbmciOiAicGlzc2luZyIsICJ1cmluYXRpb24iOiAi'
    'cGlzc2luZyIsICJ1cmluZV9pbl9hc3MiOiAicGlzc2luZyIsICJ1cmluZV9pbl9tb3V0aCI6ICJwaXNzaW5nIiwgInVyaW5lX3Bvb2wiOiAicGlzc2luZyIsICJ1cmluZV9zdH'
    'JlYW0iOiAicGlzc2luZyIsICJkaWdpbW9uIjogInBva2Vtb24iLCAiZXNwZW9uIjogInBva2Vtb24iLCAiZmxhcmVvbiI6ICJwb2tlbW9uIiwgImdhcmRldm9pciI6ICJwb2tl'
    'bW9uIiwgImdsYWNlb24iOiAicG9rZW1vbiIsICJqb2x0ZW9uIjogInBva2Vtb24iLCAibG9wdW5ueSI6ICJwb2tlbW9uIiwgInBva2VfYmFsbCI6ICJwb2tlbW9uIiwgInBva2'
    'ViYWxsIjogInBva2Vtb24iLCAicG9rZW1vbl9idyI6ICJwb2tlbW9uIiwgInBva2Vtb25fYncyIjogInBva2Vtb24iLCAicG9rZW1vbl9kcHB0IjogInBva2Vtb24iLCAicG9r'
    'ZW1vbl9mb2N1cyI6ICJwb2tlbW9uIiwgInBva2Vtb25fZ28iOiAicG9rZW1vbiIsICJwb2tlbW9uX2dzYyI6ICJwb2tlbW9uIiwgInBva2Vtb25faGdzcyI6ICJwb2tlbW9uIi'
    'wgInBva2Vtb25fbWFzdGVycyI6ICJwb2tlbW9uIiwgInBva2Vtb25fb25seSI6ICJwb2tlbW9uIiwgInBva2Vtb25fb3JhcyI6ICJwb2tlbW9uIiwgInBva2Vtb25fcmdieSI6'
    'ICJwb2tlbW9uIiwgInBva2Vtb25fcnNlIjogInBva2Vtb24iLCAicG9rZW1vbl9zbSI6ICJwb2tlbW9uIiwgInBva2Vtb25fc3MiOiAicG9rZW1vbiIsICJwb2tlbW9uX3N2Ij'
    'ogInBva2Vtb24iLCAicG9rZW1vbl94eSI6ICJwb2tlbW9uIiwgInBva2Vtb3JwaCI6ICJwb2tlbW9uIiwgInBva2VwaGlsaWEiOiAicG9rZW1vbiIsICJwb2vDqW1vbiI6ICJw'
    'b2tlbW9uIiwgInBva8OpcGhpbGlhIjogInBva2Vtb24iLCAicmVuYW1vbiI6ICJwb2tlbW9uIiwgInNuZWFzbGVyIjogInBva2Vtb24iLCAic3lsdmVvbiI6ICJwb2tlbW9uIi'
    'wgInVtYnJlb24iOiAicG9rZW1vbiIsICJ2YXBvcmVvbiI6ICJwb2tlbW9uIiwgInBvbnlnaXJsIjogInBvbnlfZ2lybCIsICJwb255X3BsYXkiOiAicG9ueXBsYXkiLCAicHJl'
    'Z25hbmN5IjogInByZWduYW50IiwgImJ1bm55IjogInJhYmJpdCIsICJsZXBvcmlkIjogInJhYmJpdCIsICJyYWJiaXRfZ2lybCI6ICJyYWJiaXRfZ2lybCIsICJyYWJiaXRnaX'
    'JsIjogInJhYmJpdF9naXJsIiwgInJhdGdpcmwiOiAicmF0X2dpcmwiLCAicm9ib3RnaXJsIjogInJvYm90X2dpcmwiLCAicnVsZTYzIjogInJ1bGVfNjMiLCAiY29wcm9waGFn'
    'aWEiOiAic2NhdCIsICJleGNlc3NpdmVfc2NhdCI6ICJzY2F0IiwgImZlY2VzIjogInNjYXQiLCAicG9vcCI6ICJzY2F0IiwgInBvb3BpbmciOiAic2NhdCIsICJzY2F0X2VhdG'
    'luZyI6ICJzY2F0IiwgInNjYXRfcGlsZSI6ICJzY2F0IiwgInNoaXQiOiAic2NhdCIsICJzaGl0dGluZyI6ICJzY2F0IiwgInNoYWRvd19lbGYiOiAic2hhZG93X2VsZiIsICJz'
    'aGFya19naXJsIjogInNoYXJrX2dpcmwiLCAic2hhcmtnaXJsIjogInNoYXJrX2dpcmwiLCAiZW5zbGF2ZWQiOiAic2xhdmUiLCAiZW5zbGF2ZWRfcm95YWwiOiAic2xhdmUiLC'
    'Aic2xhdmVfYm95IjogInNsYXZlIiwgInNsYXZlYm95IjogInNsYXZlIiwgInNsYXZlZ2lybCI6ICJzbGF2ZSIsICJzbGF2ZXMiOiAic2xhdmUiLCAidGFtZWQiOiAic2xhdmUi'
    'LCAiZ29vIjogInNsaW1lIiwgImdvb19ib3kiOiAic2xpbWUiLCAiZ29vX2NyZWF0dXJlIjogInNsaW1lIiwgImdvb19oYWlyIjogInNsaW1lIiwgImdvb19odW1hbm9pZCI6IC'
    'JzbGltZSIsICJnb29fbW9uc3RlciI6ICJzbGltZSIsICJnb29fdGVudGFjbGUiOiAic2xpbWUiLCAiZ29vX3RlbnRhY2xlcyI6ICJzbGltZSIsICJnb29fdHJhbnNmb3JtYXRp'
    'b24iOiAic2xpbWUiLCAiZ29vZXkiOiAic2xpbWUiLCAic2xpbWVfYm95IjogInNsaW1lIiwgInNsaW1lX2hhaXIiOiAic2xpbWUiLCAic2xpbWVfbW9uc3RlciI6ICJzbGltZS'
    'IsICJzbGltZWJveSI6ICJzbGltZSIsICJzbGlteSI6ICJzbGltZSIsICJoZWFsX3NsdXQiOiAic2x1dCIsICJoZWFsc2x1dCI6ICJzbHV0IiwgInNsdXRfYmVsdCI6ICJzbHV0'
    'IiwgInNsdXRfY2FwIjogInNsdXQiLCAic2x1dF9jb2xsYXIiOiAic2x1dCIsICJzbHV0X2tpdHR5IjogInNsdXQiLCAic2x1dF9vd25lciI6ICJzbHV0IiwgInNsdXRfcHJpbn'
    'QiOiAic2x1dCIsICJ3ZW5jaCI6ICJzbHV0IiwgIndob3JlIjogInNsdXQiLCAiY29icmEiOiAic25ha2UiLCAicHl0aG9uIjogInNuYWtlIiwgInNxdWlydGluZyI6ICJzcXVp'
    'cnQiLCAib2RvciI6ICJzdGluayIsICJzbWVsbHkiOiAic3RpbmsiLCAic21lbGx5X2FzcyI6ICJzdGluayIsICJzbWVsbHlfY29jayI6ICJzdGluayIsICJzbWVsbHlfZmVldC'
    'I6ICJzdGluayIsICJzdGlua19saW5lcyI6ICJzdGluayIsICJzdGlua3kiOiAic3RpbmsiLCAic3Rpbmt5X2ZlZXQiOiAic3RpbmsiLCAiaGV0ZXJvIjogInN0cmFpZ2h0Iiwg'
    'ImhldGVyb19zZXgiOiAic3RyYWlnaHQiLCAiaGV0ZXJvc2V4dWFsIjogInN0cmFpZ2h0IiwgInJlY2VpdmluZ19wb3YiOiAidGFrZXJfcG92IiwgInN1Ym1pc3NpdmVfcG92Ij'
    'ogInRha2VyX3BvdiIsICJmb3hfdGF1ciI6ICJ0YXVyIiwgImZveHRhdXIiOiAidGF1ciIsICJ3b2xmX3RhdXIiOiAidGF1ciIsICJ3b2xmdGF1ciI6ICJ0YXVyIiwgInRla2tl'
    'bl81X2RhcmtfcmVzdXJyZWN0aW9uIjogInRla2tuIiwgInRla2tlbl90YWdfdG91cm5hbWVudCI6ICJ0ZWtrbiIsICJ0ZWtrZW5fdGFnX3RvdXJuYW1lbnRfMiI6ICJ0ZWtrbi'
    'IsICJ0ZW50YWNsZV9faW5fbW91dGgiOiAidGVudGFjbGUiLCAidGVudGFjbGVfZmVsbGF0aW8iOiAidGVudGFjbGUiLCAidGVudGFjbGVfZ3JhYiI6ICJ0ZW50YWNsZSIsICJ0'
    'ZW50YWNsZV9oYWlyIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX2luX2FudXMiOiAidGVudGFjbGUiLCAidGVudGFjbGVfaW5fYXNzIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX2'
    'luX3B1c3N5IjogInRlbnRhY2xlIiwgInRlbnRhY2xlX21vbnN0ZXIiOiAidGVudGFjbGUiLCAidGVudGFjbGVfb25fZmVtYWxlIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX29u'
    'X2Z1dGEiOiAidGVudGFjbGUiLCAidGVudGFjbGVfb25fbWFsZSI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9wZW5ldHJhdGlvbiI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9waX'
    'QiOiAidGVudGFjbGUiLCAidGVudGFjbGVfcmFwZSI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9zZXgiOiAidGVudGFjbGUiLCAidGVudGFjbGVqb2IiOiAidGVudGFjbGUiLCAi'
    'dGVudGFjbGVzX29uX2ZlbWFsZSI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZXNfb25fZnV0YSI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZXNfb25fbWFsZSI6ICJ0ZW50YWNsZSIsIC'
    'J0aWVkX2FybXMiOiAidGllZF91cCIsICJ0aWVkX2JhbGxzIjogInRpZWRfdXAiLCAidGllZF9kb3duIjogInRpZWRfdXAiLCAidGllZF9mZWV0IjogInRpZWRfdXAiLCAidGll'
    'ZF9oYWlyIjogInRpZWRfdXAiLCAidGllZF9oYW5kcyI6ICJ0aWVkX3VwIiwgInRpZWRfbGVncyI6ICJ0aWVkX3VwIiwgInRpZWRfcGVuaXMiOiAidGllZF91cCIsICJ0aWVkX3'
    'RvZXMiOiAidGllZF91cCIsICJ0b3J0dXJlX2NoYW1iZXIiOiAidG9ydHVyZSIsICJ0b3J0dXJlX2RldmljZSI6ICJ0b3J0dXJlIiwgInRvcnR1cmVfcmFjayI6ICJ0b3J0dXJl'
    'IiwgInRvcnR1cmVkIjogInRvcnR1cmUiLCAidG9ydHVyZXIiOiAidG9ydHVyZSIsICJ0b3J0dXJlcyI6ICJ0b3J0dXJlIiwgInRvcnR1cmluZyI6ICJ0b3J0dXJlIiwgImFtYm'
    'lndW91c19nZW5kZXIiOiAidHJhbnMiLCAiY3Jvc3NnZW5kZXIiOiAidHJhbnMiLCAiZ2VuZGVyX2JlbmRlciI6ICJ0cmFucyIsICJnZW5kZXJfdHJhbnNvZnJtYXRpb24iOiAi'
    'dHJhbnMiLCAiZ2VuZGVyYmVuZCI6ICJ0cmFucyIsICJnZW5kZXJiZW5kZXIiOiAidHJhbnMiLCAiZ2VuZGVyYmVudCI6ICJ0cmFucyIsICJnZW5kZXJzd2FwIjogInRyYW5zIi'
    'wgIm1hbGVfaGVybSI6ICJ0cmFucyIsICJtYWxlaGVybSI6ICJ0cmFucyIsICJtYW5fYm9vYnMiOiAidHJhbnMiLCAibWFuX3RpdHMiOiAidHJhbnMiLCAibWFuYm9vYnMiOiAi'
    'dHJhbnMiLCAibXRhX2Nyb3NzZ2VuZGVyIjogInRyYW5zIiwgIm10YV90cmFuc2Zvcm1hdGlvbiI6ICJ0cmFucyIsICJtdGYiOiAidHJhbnMiLCAibXRmX2Nyb3NzZ2VuZGVyIj'
    'ogInRyYW5zIiwgIm10Zl90cmFuc2Zvcm1hdGlvbiI6ICJ0cmFucyIsICJtdGdfY3Jvc3NnZW5kZXIiOiAidHJhbnMiLCAibXRnX3RyYW5zZm9ybWF0aW9uIjogInRyYW5zIiwg'
    'Im10aF9jcm9zc2dlbmRlciI6ICJ0cmFucyIsICJtdGhfdHJhbnNmb3JtYXRpb24iOiAidHJhbnMiLCAibXRpX2Nyb3NzZ2VuZGVyIjogInRyYW5zIiwgIm10aV90cmFuc2Zvcm'
    '1hdGlvbiI6ICJ0cmFucyIsICJ0dWJlX2ZlZWRpbmciOiAidHViZSIsICJ0dWJlX2dhZyI6ICJ0dWJlIiwgInR1YmVfaW5fYXNzIjogInR1YmUiLCAidHViZV9pbl9tb3V0aCI6'
    'ICJ0dWJlIiwgInR1YmVzIjogInR1YmUiLCAidWdseV9iYXN0YXJkIjogInVnbHkiLCAidWdseV9mZW1hbGUiOiAidWdseSIsICJ1Z2x5X2Z1dGEiOiAidWdseSIsICJ1Z2x5X2'
    '1hbGUiOiAidWdseSIsICJ1Z2x5X21hbiI6ICJ1Z2x5IiwgInVyZXRocmFsIjogInVyZXRocmEiLCAidXJldGhyYWxfYmVhZHMiOiAidXJldGhyYSIsICJ1cmV0aHJhbF9idWxn'
    'ZSI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX2ZpbmdlcmluZyI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX2Zpc3RpbiI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX2luc2VydGlvbiI6IC'
    'J1cmV0aHJhIiwgInVyZXRocmFsX2xpY2tpbmciOiAidXJldGhyYSIsICJ1cmV0aHJhbF9vdmlwb3NpdGlvbiI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX3BlbmV0cmF0aW9uIjog'
    'InVyZXRocmEiLCAidXJldGhyYWxfcGx1ZyI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX3NleCI6ICJ1cmV0aHJhIiwgInZpb2xhdGVkIjogInZpb2xlbmNlIiwgInZpb2xhdGlvbi'
    'I6ICJ2aW9sZW5jZSIsICJ2aW9sZW50IjogInZpb2xlbmNlIiwgImFuYWxfdm9yZSI6ICJ2b3JlIiwgImNvY2tfdm9yZSI6ICJ2b3JlIiwgImRldm91cmVkIjogInZvcmUiLCAi'
    'ZGV2b3VyaW5nIjogInZvcmUiLCAiZGlnZXN0aW9uIjogInZvcmUiLCAibWFzc192b3JlIjogInZvcmUiLCAib3JhbF92b3JlIjogInZvcmUiLCAicGxhbnRfdm9yZSI6ICJ2b3'
    'JlIiwgInBvc3Rfdm9yZSI6ICJ2b3JlIiwgInNvZnRfdm9yZSI6ICJ2b3JlIiwgInZvcmVfc2V4IjogInZvcmUiLCAid2FyaGFtbWVyXzQwMDAwIjogIndhcmhhbW1lciIsICJ3'
    'YXJoYW1tZXJfNDBrIjogIndhcmhhbW1lciIsICJ3b2xmZ2lybCI6ICJ3b2xmX2dpcmwiLCAid293IjogIndvcmxkX29mX3dhcmNyYWZ0IiwgInhyYXlfdmlldyI6ICJ4cmF5Ii'
    'wgInplYnJvaWQiOiAiemVicmEiLCAiem9tYmllX2Z1dGEiOiAiem9tYmllIiwgInpvbWJpZXMiOiAiem9tYmllIn0='
)
TAG_ALIASES = loads(b64decode(TAG_ALIASES_STR))  # type: Dict[str, str]


def append_filtered_tags(base_string: str, tags_str: str, re_tags_to_process: Pattern, re_tags_to_exclude: Pattern) -> str:
    if len(tags_str) == 0:
        return base_string

    tags_list = tags_str.split(' ')
    tags_toadd_list = []  # type: List[str]

    for tag in tags_list:
        tag = tag.replace('-', '').replace('\'', '')
        if TAG_ALIASES.get(tag) is None and re_tags_to_process.fullmatch(tag) is None:
            continue

        # digital_media_(artwork)
        aser_match = re_meta_group.fullmatch(tag)
        aser_valid = False
        if aser_match:
            major_skip_match1 = re_tags_exclude_major1.fullmatch(aser_match.group(1))
            major_skip_match2 = re_tags_exclude_major2.fullmatch(aser_match.group(2))
            if major_skip_match1 or major_skip_match2:
                continue
            stag = trim_undersores(aser_match.group(1))
            if len(stag) >= 14:
                continue
            tag = stag
            aser_valid = True

        tag = trim_undersores(tag)
        alias = TAG_ALIASES.get(tag)
        if alias:
            tag = alias

        if re_tags_to_exclude.fullmatch(tag):
            continue

        do_add = True
        if len(tags_toadd_list) > 0:
            nutag = re_not_a_letter.sub('', re_numbered_or_counted_tag.sub(r'\1', tag))
            # try and see
            # 1) if this tag can be consumed by existing tags
            # 2) if this tag can consume existing tags
            for i in reversed(range(len(tags_toadd_list))):
                t = re_numbered_or_counted_tag.sub(r'\1', tags_toadd_list[i].lower())
                nut = re_not_a_letter.sub('', t)
                if len(nut) >= len(nutag) and (nutag in nut):
                    do_add = False
                    break
            if do_add:
                for i in reversed(range(len(tags_toadd_list))):
                    t = re_numbered_or_counted_tag.sub(r'\1', tags_toadd_list[i].lower())
                    nut = re_not_a_letter.sub('', t)
                    if len(nutag) >= len(nut) and (nut in nutag):
                        if aser_valid is False and tags_toadd_list[i][0].isupper():
                            aser_valid = True
                        del tags_toadd_list[i]
        if do_add:
            if aser_valid:
                for i, c in enumerate(tag):  # type: int, str
                    if (i == 0 or tag[i - 1] == UNDERSCORE) and c.isalpha():
                        tag = f'{tag[:i]}{c.upper()}{tag[i + 1:]}'
            tags_toadd_list.append(tag)

    return f'{base_string}{UNDERSCORE}{re_replace_symbols.sub(UNDERSCORE, UNDERSCORE.join(sorted(tags_toadd_list)))}'

#
#
#########################################
