# coding=UTF-8
"""
Author: trickerer (https://github.com/trickerer, https://github.com/trickerer01)
"""
#########################################
#
#

# native
from base64 import b64decode
from json import loads
from re import fullmatch as re_fullmatch, sub as re_sub
from typing import Pattern, Dict, List

# internal
from app_gui_defines import UNDERSCORE
from app_re import re_replace_symbols, re_tags_exclude_major1, re_tags_exclude_major2, re_numbered_or_counted_tag
from app_utils import trim_undersores

__all__ = ('append_filtered_tags',)


TAG_ALIASES_STR = (
    'eyJidW5ueV9ib3kiOiAiMStib3lzIiwgIm1hbGUiOiAiMStib3lzIiwgIm1hbGVfc29sbyI6ICIxK2JveXMiLCAibWFsZWRvbSI6ICIxK2JveXMiLCAibWFsZXN1YiI6ICIxK2'
    'JveXMiLCAibW9uc3Rlcl9ib3kiOiAiMStib3lzIiwgIm9yY19tYWxlIjogIjErYm95cyIsICIxMDFfZGFsbWF0aWFuX3N0cmVldCI6ICIxMDFfZGFsbWF0aWFucyIsICIybWFs'
    'ZSI6ICIyYm95cyIsICIybWFsZXMiOiAiMmJveXMiLCAiM21hbGUiOiAiM2JveXMiLCAiNjlfcG9zZSI6ICI2OSIsICI2OV9wb3NpdGlvbiI6ICI2OSIsICI2OV9zdGFuZGluZy'
    'I6ICI2OSIsICJzdGFuZGluZ182OSI6ICI2OSIsICJhbnl0aGluZ19kaWZmdXNpb24iOiAiYWlfZ2VuZXJhdGVkIiwgImNoaWxsX2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQi'
    'LCAiaGVudGFpX2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQiLCAibGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJtYWlfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZC'
    'IsICJuYWlfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJwaXJhdGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJybnN0YWJsZV9kaWZmdXNpb24iOiAiYWlfZ2Vu'
    'ZXJhdGVkIiwgInNlbnN1YWxfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJzdGFibGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJ0YWJsZV9kaWZmdXNpb24iOi'
    'AiYWlfZ2VuZXJhdGVkIiwgIndhaWZ1X2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQiLCAieXVraV9kaWZmdXNpb24iOiAiYWlfZ2VuZXJhdGVkIiwgInhlbm9tb3JwaCI6ICJh'
    'bGllbiIsICJhbmFsX3NleCI6ICJhbmFsIiwgImFuYWxpbmd1cyI6ICJhbmFsIiwgImFuaWxpbmd1cyI6ICJhbmFsIiwgInJlY3R1bSI6ICJhbmFsIiwgInNzYmJ3IjogImJidy'
    'IsICJiZHNtX2NvbGxhciI6ICJiZHNtIiwgImJkc21fZ2VhciI6ICJiZHNtIiwgImJkc21faGFybmVzcyI6ICJiZHNtIiwgImJkc21fb3V0Zml0IjogImJkc20iLCAiYmRzbV9y'
    'b29tIjogImJkc20iLCAiYmRzbV9zdWl0IjogImJkc20iLCAiYnNkbSI6ICJiZHNtIiwgIm1hc29jaGlzbSI6ICJiZHNtIiwgIm1hc29jaGlzdCI6ICJiZHNtIiwgImFsbGlnYX'
    'RvciI6ICJiZWFzdCIsICJhbmltYWwiOiAiYmVhc3QiLCAiZmVyYWwiOiAiYmVhc3QiLCAiZmVyYWxfb25fZmVyYWwiOiAiYmVhc3QiLCAiZmVyYWxfcGVuZXRyYXRlZCI6ICJi'
    'ZWFzdCIsICJmZXJhbF9wZW5ldHJhdGluZyI6ICJiZWFzdCIsICJtYW1tYWwiOiAiYmVhc3QiLCAibWVwaGl0aWQiOiAiYmVhc3QiLCAib2NlbG90IjogImJlYXN0IiwgInByb2'
    'N5b25pZCI6ICJiZWFzdCIsICJyZXB0aWxlIjogImJlYXN0IiwgInJvZGVudCI6ICJiZWFzdCIsICJlZ2dfYnVsZ2UiOiAiYmVsbHlfYnVsZ2UiLCAic3RvbWFjaF9idWxnZSI6'
    'ICJiZWxseV9idWxnZSIsICJmZW1hbGVfb25fZmVyYWwiOiAiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9hbnRocm8iOiAiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9mZW1hbGUiOi'
    'AiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9odW1hbiI6ICJiZXN0aWFsaXR5IiwgImZlcmFsX29uX21hbGUiOiAiYmVzdGlhbGl0eSIsICJodW1hbl9vbl9mZXJhbCI6ICJiZXN0'
    'aWFsaXR5IiwgIm1hbGVfb25fZmVyYWwiOiAiYmVzdGlhbGl0eSIsICJ6b29waGlsaWEiOiAiYmVzdGlhbGl0eSIsICJiaW1ib19hbnRocm8iOiAiYmltYm8iLCAiYmltYm9fYm'
    '9keSI6ICJiaW1ibyIsICJiaW1ib19mdXRhbmFyaSI6ICJiaW1ibyIsICJiaW1ib19saXAiOiAiYmltYm8iLCAiYmltYm9fbGlwcyI6ICJiaW1ibyIsICJiaW1ib19zdWNjdWJ1'
    'cyI6ICJiaW1ibyIsICJiaW1ib2VkIjogImJpbWJvIiwgImJpbWJvZmljYXRpb24iOiAiYmltYm8iLCAiYmltYm9maWVkIjogImJpbWJvIiwgImJpbWJvcyI6ICJiaW1ibyIsIC'
    'JiaWtlc3VpdCI6ICJib2R5c3VpdCIsICJiaW9zdWl0IjogImJvZHlzdWl0IiwgImJpdGNoX3N1aXQiOiAiYm9keXN1aXQiLCAiYml0Y2hzdWl0IjogImJvZHlzdWl0IiwgImJ1'
    'bm55X3N1aXQiOiAiYm9keXN1aXQiLCAiYnVubnlzdWl0IjogImJvZHlzdWl0IiwgImNhdF9zdWl0IjogImJvZHlzdWl0IiwgImNhdHN1aXQiOiAiYm9keXN1aXQiLCAiZ2ltcF'
    '9zdWl0IjogImJvZHlzdWl0IiwgImdpbXBzdWl0IjogImJvZHlzdWl0IiwgInBsdWdfc3VpdCI6ICJib2R5c3VpdCIsICJwbHVnc3VpdCI6ICJib2R5c3VpdCIsICJzd2ltX3N1'
    'aXQiOiAiYm9keXN1aXQiLCAic3dpbXN1aXQiOiAiYm9keXN1aXQiLCAiemVyb19zdWl0IjogImJvZHlzdWl0IiwgInplcm9zdWl0IjogImJvZHlzdWl0IiwgImJvdW5kIjogIm'
    'JvbmRhZ2UiLCAiYm91bmRfYXJtcyI6ICJib25kYWdlIiwgImJvdW5kX2ZlZXQiOiAiYm9uZGFnZSIsICJib3VuZF9oYW5kcyI6ICJib25kYWdlIiwgImJvdW5kX2xlZ3MiOiAi'
    'Ym9uZGFnZSIsICJib3VuZF9uZWNrIjogImJvbmRhZ2UiLCAiYm91bmRfcGVuaXMiOiAiYm9uZGFnZSIsICJib3VuZF90b19iZWQiOiAiYm9uZGFnZSIsICJib3VuZF90b19jaG'
    'FpciI6ICJib25kYWdlIiwgImJvdW5kX3dyaXN0cyI6ICJib25kYWdlIiwgImJyZWFzdF9ib25kYWdlIjogImJvbmRhZ2UiLCAiY2hhaXJfYm9uZGFnZSI6ICJib25kYWdlIiwg'
    'Im11bW1pZmljYXRpb24iOiAiYm9uZGFnZSIsICJtdW1taWZpZWQiOiAiYm9uZGFnZSIsICJwcmVkaWNhbWVudF9ib25kYWdlIjogImJvbmRhZ2UiLCAicmVzdHJhaW4iOiAiYm'
    '9uZGFnZSIsICJyZXN0cmFpbmVkIjogImJvbmRhZ2UiLCAicmVzdHJhaW50IjogImJvbmRhZ2UiLCAicmVzdHJhaW50cyI6ICJib25kYWdlIiwgInJpYmJvbl9ib25kYWdlIjog'
    'ImJvbmRhZ2UiLCAicm9wZV9ib25kYWdlIjogImJvbmRhZ2UiLCAic2hpYmFyaSI6ICJib25kYWdlIiwgInN0ZWVsX2JvbmRhZ2UiOiAiYm9uZGFnZSIsICJzdHJhcHBhZG8iOi'
    'AiYm9uZGFnZSIsICJzdHJhcHBlZF9kb3duIjogImJvbmRhZ2UiLCAic3VzcGVuZGVkIjogImJvbmRhZ2UiLCAic3VzcGVuc2lvbiI6ICJib25kYWdlIiwgInN1c3BlbnNpb25f'
    'Ym9uZGFnZSI6ICJib25kYWdlIiwgInRhaWxfYm9uZGFnZSI6ICJib25kYWdlIiwgInRhcGVfYm9uZGFnZSI6ICJib25kYWdlIiwgIndlYl9ib25kYWdlIjogImJvbmRhZ2UiLC'
    'AiYm92aW5lIjogImJvdmlkIiwgImNhbmluIjogImNhbmlkIiwgImNhbmluZSI6ICJjYW5pZCIsICJjYW5pcyI6ICJjYW5pZCIsICJjb2xsaWUiOiAiY2FuaWQiLCAiZGlyZV93'
    'b2xmIjogImNhbmlkIiwgImRvYmVybWFuIjogImNhbmlkIiwgImh1c2t5IjogImNhbmlkIiwgImxhYnJhZG9yIjogImNhbmlkIiwgIm1hbGFtdXRlIjogImNhbmlkIiwgIm1hc3'
    'RpZmYiOiAiY2FuaWQiLCAicGl0X2J1bGwiOiAiY2FuaWQiLCAicGl0YnVsbCI6ICJjYW5pZCIsICJwb29kbGUiOiAiY2FuaWQiLCAicmV0cmlldmVyIjogImNhbmlkIiwgInNh'
    'bW95ZWQiOiAiY2FuaWQiLCAic3BhbmllbCI6ICJjYW5pZCIsICJ3b2xmIjogImNhbmlkIiwgIndvbGZkb2ciOiAiY2FuaWQiLCAiYWJkdWN0ZWQiOiAiY2FwdHVyZWQiLCAiYW'
    'JkdWN0aW9uIjogImNhcHR1cmVkIiwgImFycmVzdGVkIjogImNhcHR1cmVkIiwgImNhZ2VkIjogImNhcHR1cmVkIiwgImNhcHRpdmUiOiAiY2FwdHVyZWQiLCAiY2FwdHVyZSI6'
    'ICJjYXB0dXJlZCIsICJjaGFpbmVkIjogImNhcHR1cmVkIiwgImRldGFpbmVkIjogImNhcHR1cmVkIiwgImphaWxlZCI6ICJjYXB0dXJlZCIsICJraWRuYXAiOiAiY2FwdHVyZW'
    'QiLCAia2lkbmFwcGVkIjogImNhcHR1cmVkIiwgImtpZG5hcHBpbmciOiAiY2FwdHVyZWQiLCAic2hhY2tsZWQiOiAiY2FwdHVyZWQiLCAidHJhcHBlZCI6ICJjYXB0dXJlZCIs'
    'ICJjYXRnaXJsIjogImNhdF9naXJsIiwgImRlZXJfdGF1ciI6ICJjZW50YXVyIiwgImRlZXJ0YXVyIjogImNlbnRhdXIiLCAiY2VydmluZSI6ICJjZXJ2aWQiLCAiYmx1ZV9jdW'
    '0iOiAiY3VtIiwgImN1bV9iYXRoIjogImN1bSIsICJjdW1fYmVsbHkiOiAiY3VtIiwgImN1bV9idWJibGUiOiAiY3VtIiwgImN1bV9idWNrZXQiOiAiY3VtIiwgImN1bV9jb3Zl'
    'cmVkIjogImN1bSIsICJjdW1fZHJpbmtpbmciOiAiY3VtIiwgImN1bV9kcmlwIjogImN1bSIsICJjdW1fZHJpcHBpbmciOiAiY3VtIiwgImN1bV9maWxsZWQiOiAiY3VtIiwgIm'
    'N1bV9mbG9vZCI6ICJjdW0iLCAiY3VtX2Zyb21fYXNzIjogImN1bSIsICJjdW1fZnJvbV9wdXNzeSI6ICJjdW0iLCAiY3VtX2dsYXplIjogImN1bSIsICJjdW1faHVuZ3J5Ijog'
    'ImN1bSIsICJjdW1faW5fYW51cyI6ICJjdW0iLCAiY3VtX2luX2FzcyI6ICJjdW0iLCAiY3VtX2luX2Nsb3RoZXMiOiAiY3VtIiwgImN1bV9pbl9jb25kb20iOiAiY3VtIiwgIm'
    'N1bV9pbl9jb250YWluZXIiOiAiY3VtIiwgImN1bV9pbl9oYWlyIjogImN1bSIsICJjdW1faW5fbW91dGgiOiAiY3VtIiwgImN1bV9pbl9ub3NlIjogImN1bSIsICJjdW1faW5f'
    'cHVzc3kiOiAiY3VtIiwgImN1bV9pbl90aHJvYXQiOiAiY3VtIiwgImN1bV9pbl91dGVydXMiOiAiY3VtIiwgImN1bV9pbnNpZGUiOiAiY3VtIiwgImN1bV9qYXIiOiAiY3VtIi'
    'wgImN1bV9raXNzIjogImN1bSIsICJjdW1fbGVhayI6ICJjdW0iLCAiY3VtX2xlYWtpbmciOiAiY3VtIiwgImN1bV9saWNrIjogImN1bSIsICJjdW1fbWlsa2luZyI6ICJjdW0i'
    'LCAiY3VtX29uX2FzcyI6ICJjdW0iLCAiY3VtX29uX2JhbGxzIjogImN1bSIsICJjdW1fb25fYm9keSI6ICJjdW0iLCAiY3VtX29uX2JyZWFzdHMiOiAiY3VtIiwgImN1bV9vbl'
    '9idXR0IjogImN1bSIsICJjdW1fb25fY2hlc3QiOiAiY3VtIiwgImN1bV9vbl9jbG90aGVzIjogImN1bSIsICJjdW1fb25fZmFjZSI6ICJjdW0iLCAiY3VtX29uX2ZlZXQiOiAi'
    'Y3VtIiwgImN1bV9vbl9ncm91bmQiOiAiY3VtIiwgImN1bV9vbl9oYWlyIjogImN1bSIsICJjdW1fb25faGFuZCI6ICJjdW0iLCAiY3VtX29uX2xlZyI6ICJjdW0iLCAiY3VtX2'
    '9uX3BlbmlzIjogImN1bSIsICJjdW1fb25fc2VsZiI6ICJjdW0iLCAiY3VtX29uX3N0b21hY2giOiAiY3VtIiwgImN1bV9vbl90b25ndWUiOiAiY3VtIiwgImN1bV9wb29sIjog'
    'ImN1bSIsICJjdW1fcHVkZGxlIjogImN1bSIsICJjdW1fcmluZyI6ICJjdW0iLCAiY3VtX3Nob3QiOiAiY3VtIiwgImN1bV9zcGF0dGVyIjogImN1bSIsICJjdW1fc3F1aXJ0Ij'
    'ogImN1bSIsICJjdW1fc3RhaW4iOiAiY3VtIiwgImN1bV9zdHJhbmQiOiAiY3VtIiwgImN1bV9zdHJpbmciOiAiY3VtIiwgImN1bV9zd2FsbG93IjogImN1bSIsICJjdW1fc3dh'
    'cCI6ICJjdW0iLCAiY3VtZHJpcCI6ICJjdW0iLCAiY3VtZHVtcCI6ICJjdW0iLCAiY3VtbHViZSI6ICJjdW0iLCAiY3VtbWluZyI6ICJjdW0iLCAiY3VtcG9vbCI6ICJjdW0iLC'
    'AiY3Vtc2VhIjogImN1bSIsICJjdW1zaG90IjogImN1bSIsICJjdW1zbHV0IjogImN1bSIsICJjdW1zdHJpbmciOiAiY3VtIiwgImdyZWVuX2N1bSI6ICJjdW0iLCAicHJlY3Vt'
    'IjogImN1bSIsICJ0aGlja19jdW0iOiAiY3VtIiwgImhhbmFfc29uZyI6ICJkLnZhIiwgImRhbmdhbnJvbnBhX3YzIjogImRhbmdhbnJvbnBhIiwgIm5ld19kYW5nYW5yb25wYV'
    '92MyI6ICJkYW5nYW5yb25wYSIsICJzdXBlcl9kYW5nYW5yb25wYV8yIjogImRhbmdhbnJvbnBhIiwgImRyb3dfZWxmIjogImRhcmtfZWxmIiwgImR1bm1lciI6ICJkYXJrX2Vs'
    'ZiIsICJkdW5tZXJfZWxmIjogImRhcmtfZWxmIiwgImRlYWQiOiAiZGVhdGgiLCAicm9lX2RlZXIiOiAiZGVlciIsICJkZWx0YXJ1bmVfY2hhcHRlcl8xIjogImRlbHRhcnVuZS'
    'IsICJkZWx0YXJ1bmVfY2hhcHRlcl8yIjogImRlbHRhcnVuZSIsICJkZWx0YXJ1bmVfY2hhcHRlcl8zIjogImRlbHRhcnVuZSIsICJkZW1vbl9ib3kiOiAiZGVtb24iLCAiZGVt'
    'b25faHVtYW5vaWQiOiAiZGVtb24iLCAiZGVtb25zIjogImRlbW9uIiwgImRldmlsIjogImRlbW9uIiwgImRldmlsX2dpcmwiOiAiZGVtb24iLCAiZXJlZGFyIjogImRlbW9uIi'
    'wgImRlbW9uX2dpcmwiOiAiZGVtb25lc3MiLCAiZGVtb25fZ2lybHMiOiAiZGVtb25lc3MiLCAiZGVtb25naXJsIjogImRlbW9uZXNzIiwgImRlbW9uZ2lybHMiOiAiZGVtb25l'
    'c3MiLCAiZGVycF9leWVzIjogImRlcnAiLCAiZG9nZ2lybCI6ICJkb2dfZ2lybCIsICJkd2FyZl9mZW1hbGUiOiAiZHdhcmYiLCAiZWVsX2luX2FzcyI6ICJlZWwiLCAiZWVsX2'
    'luX3B1c3N5IjogImVlbCIsICJlZWxfaW5fdXJldGhyYSI6ICJlZWwiLCAiZWVsX2luc2VydGlvbiI6ICJlZWwiLCAiZWdnX2JpcnRoIjogImVnZyIsICJlZ2dfZnJvbV9hc3Mi'
    'OiAiZWdnIiwgImVnZ19mcm9tX21vdXRoIjogImVnZyIsICJlZ2dfZnJvbV9wdXNzeSI6ICJlZ2ciLCAiZWdnX2ltcGxhbnRhdGlvbiI6ICJlZ2ciLCAiZWdnX2luX2FzcyI6IC'
    'JlZ2ciLCAiZWdnX2luX21vdXRoIjogImVnZyIsICJlZ2dfaW5fcHVzc3kiOiAiZWdnIiwgImVnZ19pbnNlcnRpb24iOiAiZWdnIiwgImVnZ19sYXlpbmciOiAiZWdnIiwgImVn'
    'Z25hbnQiOiAiZWdnIiwgImVnZ3NfaW5fc3RvbWFjaCI6ICJlZ2ciLCAib3JhbF9lZ2dfaW1wbGFudGF0aW9uIjogImVnZyIsICJlbHZlcyI6ICJlbGYiLCAiaGlnaF9lbGYiOi'
    'AiZWxmIiwgIndvb2RfZWxmIjogImVsZiIsICJlcXVpbmUiOiAiZXF1aWQiLCAiZmFjZV9zaXR0aW5nIjogImZhY2VzaXR0aW5nIiwgImZhY2VzaXQiOiAiZmFjZXNpdHRpbmci'
    'LCAiZmFjZXNpdHRpbmdfcG92IjogImZhY2VzaXR0aW5nIiwgImN1bV9mYXJ0IjogImZhcnQiLCAiZmFjZV9mYXJ0IjogImZhcnQiLCAiZmFjZWZhcnQiOiAiZmFydCIsICJmYX'
    'J0X2Nsb3VkIjogImZhcnQiLCAiZmFydF9mZXRpc2giOiAiZmFydCIsICJmYXJ0X2luX2ZhY2UiOiAiZmFydCIsICJmYXJ0X2luX21vdXRoIjogImZhcnQiLCAiZmFydF9vbl9k'
    'aWNrIjogImZhcnQiLCAiZmFydF9vbl9mYWNlIjogImZhcnQiLCAiZmFydF9zbmlmZmluZyI6ICJmYXJ0IiwgImZhcnRpbmdfaW5fZmFjZSI6ICJmYXJ0IiwgImZhcnRpbmdfaW'
    '5fbW91dGgiOiAiZmFydCIsICJmYXJ0aW5nX29uX2ZhY2UiOiAiZmFydCIsICJmYXJ0am9iIjogImZhcnQiLCAiZmFydHMiOiAiZmFydCIsICJmZWxpbmUiOiAiZmVsaWQiLCAi'
    'ZmVsaXMiOiAiZmVsaWQiLCAiZmVtYm95c3ViIjogImZlbWJveSIsICJhbmFsX2Zpc3RpbmciOiAiZmlzdGluZyIsICJhdXRvZmlzdGluZyI6ICJmaXN0aW5nIiwgImRlZXBfZm'
    'lzdGluZyI6ICJmaXN0aW5nIiwgImRvdWJsZV9maXN0aW5nIjogImZpc3RpbmciLCAic2VsZl9maXN0aW5nIjogImZpc3RpbmciLCAidmFnaW5hbF9maXN0aW5nIjogImZpc3Rp'
    'bmciLCAiZm94Z2lybCI6ICJmb3hfZ2lybCIsICJibGFja19mdXIiOiAiZnVyIiwgImJsdWVfZnVyIjogImZ1ciIsICJib2R5X2Z1ciI6ICJmdXIiLCAiYnJvd25fZnVyIjogIm'
    'Z1ciIsICJkYXJrX2Z1ciI6ICJmdXIiLCAiZ3JheV9mdXIiOiAiZnVyIiwgImdyZWVuX2Z1ciI6ICJmdXIiLCAiZ3JleV9mdXIiOiAiZnVyIiwgIm9yYW5nZV9mdXIiOiAiZnVy'
    'IiwgInBpbmtfZnVyIjogImZ1ciIsICJwdXJwbGVfZnVyIjogImZ1ciIsICJyZWRfZnVyIjogImZ1ciIsICJ0YW5fZnVyIjogImZ1ciIsICJ3ZXRfZnVyIjogImZ1ciIsICJ3aG'
    'l0ZV9mdXIiOiAiZnVyIiwgInllbGxvd19mdXIiOiAiZnVyIiwgImFudGhyb19mb2N1cyI6ICJmdXJyeSIsICJhbnRocm9fb25fYW50aHJvIjogImZ1cnJ5IiwgImFudGhyb19v'
    'bl9mZXJhbCI6ICJmdXJyeSIsICJhbnRocm9fb25seSI6ICJmdXJyeSIsICJmdXJyZWRfZHJhZ29uIjogImZ1cnJ5IiwgImZ1cnJpZmljYXRpb24iOiAiZnVycnkiLCAiZnVycn'
    'lfYXNzIjogImZ1cnJ5IiwgImZ1cnJ5X2JyZWFzdHMiOiAiZnVycnkiLCAiZnVycnlfZWFycyI6ICJmdXJyeSIsICJmdXJyeV9mZW1hbGUiOiAiZnVycnkiLCAiZnVycnlfaW50'
    'ZXJzZXgiOiAiZnVycnkiLCAiZnVycnlfbWFsZSI6ICJmdXJyeSIsICJmdXJyeV9vbmx5IjogImZ1cnJ5IiwgImZ1cnJ5X3RhaWwiOiAiZnVycnkiLCAiZnVycnlmaWNhdGlvbi'
    'I6ICJmdXJyeSIsICJtYW1tYWxfaHVtYW5vaWQiOiAiZnVycnkiLCAic2NhbGllIjogImZ1cnJ5IiwgInNleHlmdXIiOiAiZnVycnkiLCAid29yZ2VuIjogImZ1cnJ5IiwgInlp'
    'ZmYiOiAiZnVycnkiLCAieWlmZmluZyI6ICJmdXJyeSIsICJmdXRhX3dpdGhfbWFsZSI6ICJmdXRhX29uX21hbGUiLCAiZnV0YW5hcmkvbWFsZSI6ICJmdXRhX29uX21hbGUiLC'
    'AiZGVtb25fZnV0YSI6ICJmdXRhbmFyaSIsICJlbGZfZnV0YSI6ICJmdXRhbmFyaSIsICJmdXRhL2N1bnRib3kiOiAiZnV0YW5hcmkiLCAiZnV0YS9mZW1hbGUiOiAiZnV0YW5h'
    'cmkiLCAiZnV0YS9mZW1ib3kiOiAiZnV0YW5hcmkiLCAiZnV0YS9mdXRhIjogImZ1dGFuYXJpIiwgImZ1dGEvbWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhXyI6ICJmdXRhbmFyaS'
    'IsICJmdXRhX2JhbGxzIjogImZ1dGFuYXJpIiwgImZ1dGFfY29jayI6ICJmdXRhbmFyaSIsICJmdXRhX2ZvY3VzIjogImZ1dGFuYXJpIiwgImZ1dGFfZ2lhbnRlc3MiOiAiZnV0'
    'YW5hcmkiLCAiZnV0YV9pc19iaWdnZXIiOiAiZnV0YW5hcmkiLCAiZnV0YV9pc19zbWFsbGVyIjogImZ1dGFuYXJpIiwgImZ1dGFfbWlsZiI6ICJmdXRhbmFyaSIsICJmdXRhX2'
    '9uX2ZlbWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhX29uX2Z1dGEiOiAiZnV0YW5hcmkiLCAiZnV0YV9vbl90b3AiOiAiZnV0YW5hcmkiLCAiZnV0YV9vbmx5IjogImZ1dGFuYXJp'
    'IiwgImZ1dGFfcG92IjogImZ1dGFuYXJpIiwgImZ1dGFfc2Fuc19iYWxscyI6ICJmdXRhbmFyaSIsICJmdXRhX3NhbnNfcHVzc3kiOiAiZnV0YW5hcmkiLCAiZnV0YV9zb2xvIj'
    'ogImZ1dGFuYXJpIiwgImZ1dGFfc3ViIjogImZ1dGFuYXJpIiwgImZ1dGFfd2lmZSI6ICJmdXRhbmFyaSIsICJmdXRhX3dpdGhfZmVtYWxlIjogImZ1dGFuYXJpIiwgImZ1dGFf'
    'd2l0aF9mZW1ib3kiOiAiZnV0YW5hcmkiLCAiZnV0YV93aXRoX2Z1dGEiOiAiZnV0YW5hcmkiLCAiZnV0YWRvbSI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaS9jdW50Ym95IjogIm'
    'Z1dGFuYXJpIiwgImZ1dGFuYXJpL2ZlbWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaS9mZW1ib3kiOiAiZnV0YW5hcmkiLCAiZnV0YW5hcmkvZnV0YSI6ICJmdXRhbmFyaSIs'
    'ICJmdXRhbmFyaV9wZW5ldHJhdGVkIjogImZ1dGFuYXJpIiwgImZ1dGFuYXJpX3BlbmV0cmF0aW5nIjogImZ1dGFuYXJpIiwgImZ1dGFuYXJpX3BvdiI6ICJmdXRhbmFyaSIsIC'
    'JmdXRhbmFyaV90cmFuc2Zvcm1hdGlvbiI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaXphdGlvbiI6ICJmdXRhbmFyaSIsICJmdXRhc3ViIjogImZ1dGFuYXJpIiwgIm1pbmlmdXRh'
    'IjogImZ1dGFuYXJpIiwgInNvbGVfZnV0YSI6ICJmdXRhbmFyaSIsICJzb2xvX2Z1dGEiOiAiZnV0YW5hcmkiLCAiYmFsbF9nYWciOiAiZ2FnIiwgImJhbGxnYWciOiAiZ2FnIi'
    'wgImJhbWJvb19nYWciOiAiZ2FnIiwgImJpdF9nYWciOiAiZ2FnIiwgImJpdGVfZ2FnIjogImdhZyIsICJibGFja19iYWxsX2dhZyI6ICJnYWciLCAiYmx1ZV9iYWxsX2dhZyI6'
    'ICJnYWciLCAiYm9uZV9nYWciOiAiZ2FnIiwgImNsZWF2ZV9nYWciOiAiZ2FnIiwgImNsb3RoX2dhZyI6ICJnYWciLCAiY29ja19nYWciOiAiZ2FnIiwgImRlbnRhbF9nYWciOi'
    'AiZ2FnIiwgImRpbGRvX2dhZyI6ICJnYWciLCAiZ2FnX2JhbGwiOiAiZ2FnIiwgImdhZ19ib25kYWdlIjogImdhZyIsICJnYWdfaGFybmVzcyI6ICJnYWciLCAiZ2FnX21hc2si'
    'OiAiZ2FnIiwgImdhZ2dlZCI6ICJnYWciLCAiZ2FnZ2luZyI6ICJnYWciLCAiaGFuZGdhZyI6ICJnYWciLCAiaGFybmVzc19iYWxsX2dhZyI6ICJnYWciLCAiaGFybmVzc19iaX'
    'RfZ2FnIjogImdhZyIsICJoYXJuZXNzX2JpdGVfZ2FnIjogImdhZyIsICJoYXJuZXNzX2dhZyI6ICJnYWciLCAiaGFybmVzc19yaW5nX2dhZyI6ICJnYWciLCAiaW1wcm92aXNl'
    'ZF9nYWciOiAiZ2FnIiwgIm1vdXRoX2dhZyI6ICJnYWciLCAibXV6emxlX2dhZyI6ICJnYWciLCAib25haG9sZV9nYWciOiAiZ2FnIiwgIm9wZW5fbW91dGhfZ2FnIjogImdhZy'
    'IsICJvdG1fZ2FnIjogImdhZyIsICJvdmVyX3RoZV9tb3V0aF9nYWciOiAiZ2FnIiwgIm92ZXJfdGhlX25vc2VfZ2FnIjogImdhZyIsICJwYW5lbF9nYWciOiAiZ2FnIiwgInBh'
    'bnR5X2dhZyI6ICJnYWciLCAicGlua19iYWxsX2dhZyI6ICJnYWciLCAicGx1Z19nYWciOiAiZ2FnIiwgInB1cnBsZV9iYWxsX2dhZyI6ICJnYWciLCAicmVkX2JhbGxfZ2FnIj'
    'ogImdhZyIsICJyaW5nX2dhZyI6ICJnYWciLCAicm9wZV9nYWciOiAiZ2FnIiwgInJvcGVnYWciOiAiZ2FnIiwgInNoYXJlZF9nYWciOiAiZ2FnIiwgInN0dWZmZWRfbW91dGhf'
    'Z2FnIjogImdhZyIsICJ0YXBlX2dhZyI6ICJnYWciLCAidGVudGFjbGVfZ2FnIjogImdhZyIsICJ3ZWJfZ2FnIjogImdhZyIsICJ3aGl0ZV9iYWxsX2dhZyI6ICJnYWciLCAiZ2'
    'FuZ19iYW5nIjogImdhbmdiYW5nIiwgImdhbmdfcmFwZSI6ICJnYW5nYmFuZyIsICJnYW5ncmFwZSI6ICJnYW5nYmFuZyIsICJhbmFsX2dhcGUiOiAiZ2FwZSIsICJiaWdfZ2Fw'
    'ZSI6ICJnYXBlIiwgImdhcGluZyI6ICJnYXBlIiwgImdhcGluZ19hbnVzIjogImdhcGUiLCAiZ2FwaW5nX2FzcyI6ICJnYXBlIiwgImdhcGluZ19jbG9hY2EiOiAiZ2FwZSIsIC'
    'JnYXBpbmdfbmlwcGxlIjogImdhcGUiLCAiZ2FwaW5nX25pcHBsZXMiOiAiZ2FwZSIsICJnYXBpbmdfcHVzeXkiOiAiZ2FwZSIsICJnYXBpbmdfdXJldGhyYSI6ICJnYXBlIiwg'
    'Imh1Z2VfZ2FwZSI6ICJnYXBlIiwgImJhcmEiOiAiZ2F5IiwgImJhcmFfdGlkZGllcyI6ICJnYXkiLCAiYmFyYV90aXRzIjogImdheSIsICJiYXJha2EiOiAiZ2F5IiwgImJhcm'
    'FraW5nIjogImdheSIsICJiYXJhbHVzdCI6ICJnYXkiLCAiYmFyYXN1aXNob3UiOiAiZ2F5IiwgImJhcmF5b3QiOiAiZ2F5IiwgImJhcmF6b2t1IjogImdheSIsICJiaXNleHVh'
    'bF9tYWxlIjogImdheSIsICJnYXlfYW5hbF9tYXN0dXJiYXRpb24iOiAiZ2F5IiwgImdheV9iYXIiOiAiZ2F5IiwgImdheV9iZWFyIjogImdheSIsICJnYXlfYmxvd2pvYiI6IC'
    'JnYXkiLCAiZ2F5X2RlbmlhbCI6ICJnYXkiLCAiZ2F5X2RvY2tpbmciOiAiZ2F5IiwgImdheV9kb21pbmF0aW9uIjogImdheSIsICJnYXlfaGFuZGpvYiI6ICJnYXkiLCAiZ2F5'
    'X2hhcmVtIjogImdheSIsICJnYXlfb3JneSI6ICJnYXkiLCAiZ2F5X3Bvcm5zdGFyIjogImdheSIsICJnYXlfcHJpZGUiOiAiZ2F5IiwgImdheV9wcmlkZV9jb2xvcnMiOiAiZ2'
    'F5IiwgImdheV9zZXgiOiAiZ2F5IiwgImdheV9zb3VuZCI6ICJnYXkiLCAiZ2F5X3RvX3N0cmFpZ2h0IjogImdheSIsICJnYXlfd2l0aF93b21hbiI6ICJnYXkiLCAiZ2F5X3dy'
    'ZXN0bGluZyI6ICJnYXkiLCAiZ2F5dG9yIjogImdheSIsICJtZW5fa2lzc2luZyI6ICJnYXkiLCAiZ2lyYWZmZSI6ICJnaXJhZmZpZCIsICJnbHByeV9ob2xlIjogImdsb3J5aG'
    '9sZSIsICJnb29naXJsIjogImdvb19naXJsIiwgInNsaW1lX2dpcmwiOiAiZ29vX2dpcmwiLCAic2xpbWVnaXJsIjogImdvb19naXJsIiwgImdvdGhpZmllZCI6ICJnb3RoIiwg'
    'Im1hcmUiOiAiaG9yc2UiLCAicG9ueSI6ICJob3JzZSIsICJzdGFsbGlvbiI6ICJob3JzZSIsICJoeWVuYSI6ICJoeWFlbmlkIiwgImlndWFuYSI6ICJpZ3VhbmlkIiwgImNsb2'
    '5lY2VzdCI6ICJpbmNlc3QiLCAiaW1wbGllZF9pbmNlc3QiOiAiaW5jZXN0IiwgIm1vbWNlc3QiOiAiaW5jZXN0IiwgInNlbGZjZXN0IjogImluY2VzdCIsICJ0d2luY2VzdCI6'
    'ICJpbmNlc3QiLCAiY3VtX2luZmxhdGlvbiI6ICJpbmZsYXRpb24iLCAiY3VtZmxhdGlvbiI6ICJpbmZsYXRpb24iLCAiZWdnX2luZmxhdGlvbiI6ICJpbmZsYXRpb24iLCAic2'
    'xpbWVfaW5mbGF0aW9uIjogImluZmxhdGlvbiIsICJpbmp1cmUiOiAiaW5qdXJ5IiwgImluanVyZWQiOiAiaW5qdXJ5IiwgImluanVyZXMiOiAiaW5qdXJ5IiwgImFyYWNobmlk'
    'IjogImluc2VjdCIsICJhcnRocm9wb2QiOiAiaW5zZWN0IiwgImJlZSI6ICJpbnNlY3QiLCAiYmVlcyI6ICJpbnNlY3QiLCAiY2VudGlwZWRlIjogImluc2VjdCIsICJjb2Nrcm'
    '9hc2giOiAiaW5zZWN0IiwgImVhcnRod29ybSI6ICJpbnNlY3QiLCAiZ2FzdHJvcG9kIjogImluc2VjdCIsICJob3JuZXQiOiAiaW5zZWN0IiwgImluc2VjdG9pZCI6ICJpbnNl'
    'Y3QiLCAibGVlY2giOiAiaW5zZWN0IiwgImxlZWNoZXMiOiAiaW5zZWN0IiwgImxvY3VzdCI6ICJpbnNlY3QiLCAibG9jdXN0cyI6ICJpbnNlY3QiLCAibWFnZ290IjogImluc2'
    'VjdCIsICJtYWdnb3RzIjogImluc2VjdCIsICJtYW50aXMiOiAiaW5zZWN0IiwgIm1vc3F1aXRvIjogImluc2VjdCIsICJtb3RoIjogImluc2VjdCIsICJxdWVlbl9iZWUiOiAi'
    'aW5zZWN0IiwgInNwaWRlciI6ICJpbnNlY3QiLCAidGFyYW50dWxhIjogImluc2VjdCIsICJ2ZXNwaWQiOiAiaW5zZWN0IiwgIndhc3AiOiAiaW5zZWN0IiwgIndhc3BzIjogIm'
    'luc2VjdCIsICJ3b3JtIjogImluc2VjdCIsICJ3b3JtcyI6ICJpbnNlY3QiLCAia2FpX3NhIjogImthaXNhIiwgImJsYWNrX2xhdGV4IjogImxhdGV4IiwgImxhdGV4X2JvZHlz'
    'dWl0IjogImxhdGV4IiwgImxhdGV4X2Nsb3RoaW5nIjogImxhdGV4IiwgImxhdGV4X2RyZXNzIjogImxhdGV4IiwgImxhdGV4X2dsb3ZlcyI6ICJsYXRleCIsICJsYXRleF9sZW'
    'dnaW5ncyI6ICJsYXRleCIsICJsYXRleF9sZWd3ZWFyIjogImxhdGV4IiwgImxhdGV4X3N0b2NraW5ncyI6ICJsYXRleCIsICJsYXRleF9zdWl0IjogImxhdGV4IiwgImxhdGV4'
    'X3RoaWdoaGlnaHRzIjogImxhdGV4IiwgInJ1YmJlciI6ICJsYXRleCIsICJydWJiZXJfYm9vdHMiOiAibGF0ZXgiLCAicnViYmVyX2Nsb3RoaW5nIjogImxhdGV4IiwgInJ1Ym'
    'Jlcl9nbG92ZXMiOiAibGF0ZXgiLCAicnViYmVyX3N1aXQiOiAibGF0ZXgiLCAibGV6ZG9tIjogImxlc2JpYW4iLCAibGV6c3ViIjogImxlc2JpYW4iLCAieXVyaSI6ICJsZXNi'
    'aWFuIiwgImxpb25lc3MiOiAibGlvbiIsICJtYXJpb19nb2xmIjogIm1hcmlvIiwgIm1hcmlvX2thcnQiOiAibWFyaW8iLCAibWFyaW9fcGFydHkiOiAibWFyaW8iLCAibWFyaW'
    '9fdGVubmlzIjogIm1hcmlvIiwgInBhcGVyX21hcmlvIjogIm1hcmlvIiwgInN1cGVyX21hcmlvIjogIm1hcmlvIiwgInN1cGVyX21hcmlvXzY0IjogIm1hcmlvIiwgIm15X2xp'
    'dHRsZV9wb255IjogIm1scCIsICJteV9saXR0bGVfcG9ueV9mcmllbmRzaGlwX2lzX21hZ2ljIjogIm1scCIsICJteV9saXR0bGVfcG9ueV90aGVfbW92aWUiOiAibWxwIiwgIm'
    'dhcmdveWxlIjogIm1vbnN0ZXIiLCAiZ2FyZ295bGVzIjogIm1vbnN0ZXIiLCAibW91c2VnaXJsIjogIm1vdXNlX2dpcmwiLCAibXVzdGVsYSI6ICJtdXN0ZWxpZCIsICJtdXN0'
    'ZWxpbmUiOiAibXVzdGVsaWQiLCAibmFydXRvOl90aGVfbGFzdCI6ICJuYXJ1dG8iLCAibmFydXRvX2JvbWIiOiAibmFydXRvIiwgIm5hcnV0b19zaGlwcHVuZGVuIjogIm5hcn'
    'V0byIsICJuaWVyOl9hdXRvbWF0YSI6ICJuaWVyIiwgIm5pZXJfcmVwbGljYW50IjogIm5pZXIiLCAia2FsZG9yZWkiOiAibmlnaHRfZWxmIiwgIm51bWJ1aF81IjogIm51bWJh'
    'aF81IiwgImJsb3dqb2IiOiAib3JhbCIsICJmYWNlX2Z1Y2siOiAib3JhbCIsICJmYWNlX2Z1Y2tpbmciOiAib3JhbCIsICJmYWNlZnVjayI6ICJvcmFsIiwgImZlbGxhdGlvIj'
    'ogIm9yYWwiLCAib3JhbF9jcmVhbXBpZSI6ICJvcmFsIiwgIm9yYWxfaW5zZXJ0aW9uIjogIm9yYWwiLCAib3JhbF9rbm90dGluZyI6ICJvcmFsIiwgIm9yYWxfbWFzdHVyYmF0'
    'aW9uIjogIm9yYWwiLCAib3JhbF9wZW5ldHJhdGlvbiI6ICJvcmFsIiwgIm9yYWxfcmFwZSI6ICJvcmFsIiwgIm9yYWxfc2V4IjogIm9yYWwiLCAic3BpdHJvYXN0IjogIm9yYW'
    'wiLCAic3Vja2luZyI6ICJvcmFsIiwgInRvbmd1ZV9qb2IiOiAib3JhbCIsICJ0b25ndWVqb2IiOiAib3JhbCIsICIzc29tZSI6ICJvcmd5IiwgIjRzb21lIjogIm9yZ3kiLCAi'
    'NXNvbWUiOiAib3JneSIsICI2c29tZSI6ICJvcmd5IiwgImZpdmVzb21lIjogIm9yZ3kiLCAiZm91cnNvbWUiOiAib3JneSIsICJncm91cF9zZXgiOiAib3JneSIsICJzaXhzb2'
    '1lIjogIm9yZ3kiLCAidGhyZWVzb21lIjogIm9yZ3kiLCAicGVyc29uYV8zX3BvcnRhYmxlIjogInBlcnNvbmFfMyIsICJwZXJzb25hXzRfYXJlbmEiOiAicGVyc29uYV80Iiwg'
    'InBlcnNvbmFfNF90aGVfZ29sZGVuIjogInBlcnNvbmFfNCIsICJwZXJzb25hXzVfcm95YWwiOiAicGVyc29uYV81IiwgInBldGdpcnRsIjogInBldF9naXJsIiwgImFzc2lzdG'
    'VkX3BlZSI6ICJwaXNzaW5nIiwgImRyaW5raW5nX3BlZSI6ICJwaXNzaW5nIiwgIm1vdXRoX3BlZSI6ICJwaXNzaW5nIiwgInBhbnR5X3BlZSI6ICJwaXNzaW5nIiwgInBlZWlu'
    'ZyI6ICJwaXNzaW5nIiwgInNpdHRpbmdfcGVlIjogInBpc3NpbmciLCAic3RhbmRpbmdfcGVlIjogInBpc3NpbmciLCAidXJpbmF0aW5nIjogInBpc3NpbmciLCAidXJpbmF0aW'
    '9uIjogInBpc3NpbmciLCAidXJpbmVfaW5fYXNzIjogInBpc3NpbmciLCAidXJpbmVfaW5fbW91dGgiOiAicGlzc2luZyIsICJ1cmluZV9wb29sIjogInBpc3NpbmciLCAidXJp'
    'bmVfc3RyZWFtIjogInBpc3NpbmciLCAiZGlnaW1vbiI6ICJwb2tlbW9uIiwgImVzcGVvbiI6ICJwb2tlbW9uIiwgImZsYXJlb24iOiAicG9rZW1vbiIsICJnYXJkZXZvaXIiOi'
    'AicG9rZW1vbiIsICJnbGFjZW9uIjogInBva2Vtb24iLCAiam9sdGVvbiI6ICJwb2tlbW9uIiwgImxvcHVubnkiOiAicG9rZW1vbiIsICJwb2tlX2JhbGwiOiAicG9rZW1vbiIs'
    'ICJwb2tlYmFsbCI6ICJwb2tlbW9uIiwgInBva2Vtb25fYnciOiAicG9rZW1vbiIsICJwb2tlbW9uX2J3MiI6ICJwb2tlbW9uIiwgInBva2Vtb25fZHBwdCI6ICJwb2tlbW9uIi'
    'wgInBva2Vtb25fZm9jdXMiOiAicG9rZW1vbiIsICJwb2tlbW9uX2dvIjogInBva2Vtb24iLCAicG9rZW1vbl9nc2MiOiAicG9rZW1vbiIsICJwb2tlbW9uX2hnc3MiOiAicG9r'
    'ZW1vbiIsICJwb2tlbW9uX21hc3RlcnMiOiAicG9rZW1vbiIsICJwb2tlbW9uX29ubHkiOiAicG9rZW1vbiIsICJwb2tlbW9uX29yYXMiOiAicG9rZW1vbiIsICJwb2tlbW9uX3'
    'JnYnkiOiAicG9rZW1vbiIsICJwb2tlbW9uX3JzZSI6ICJwb2tlbW9uIiwgInBva2Vtb25fc20iOiAicG9rZW1vbiIsICJwb2tlbW9uX3NzIjogInBva2Vtb24iLCAicG9rZW1v'
    'bl9zdiI6ICJwb2tlbW9uIiwgInBva2Vtb25feHkiOiAicG9rZW1vbiIsICJwb2tlbW9ycGgiOiAicG9rZW1vbiIsICJwb2tlcGhpbGlhIjogInBva2Vtb24iLCAicG9rw6ltb2'
    '4iOiAicG9rZW1vbiIsICJwb2vDqXBoaWxpYSI6ICJwb2tlbW9uIiwgInJlbmFtb24iOiAicG9rZW1vbiIsICJzbmVhc2xlciI6ICJwb2tlbW9uIiwgInN5bHZlb24iOiAicG9r'
    'ZW1vbiIsICJ1bWJyZW9uIjogInBva2Vtb24iLCAidmFwb3Jlb24iOiAicG9rZW1vbiIsICJwb255Z2lybCI6ICJwb255X2dpcmwiLCAicG9ueV9wbGF5IjogInBvbnlwbGF5Ii'
    'wgInByZWduYW5jeSI6ICJwcmVnbmFudCIsICJidW5ueSI6ICJyYWJiaXQiLCAibGVwb3JpZCI6ICJyYWJiaXQiLCAicmFiYml0X2dpcmwiOiAicmFiYml0X2dpcmwiLCAicmFi'
    'Yml0Z2lybCI6ICJyYWJiaXRfZ2lybCIsICJyYXRnaXJsIjogInJhdF9naXJsIiwgInJvYm90Z2lybCI6ICJyb2JvdF9naXJsIiwgInJ1bGU2MyI6ICJydWxlXzYzIiwgImNvcH'
    'JvcGhhZ2lhIjogInNjYXQiLCAiZXhjZXNzaXZlX3NjYXQiOiAic2NhdCIsICJmZWNlcyI6ICJzY2F0IiwgInBvb3AiOiAic2NhdCIsICJwb29waW5nIjogInNjYXQiLCAic2Nh'
    'dF9lYXRpbmciOiAic2NhdCIsICJzY2F0X3BpbGUiOiAic2NhdCIsICJzaGl0IjogInNjYXQiLCAic2hpdHRpbmciOiAic2NhdCIsICJzaGFkb3dfZWxmIjogInNoYWRvd19lbG'
    'YiLCAic2hhcmtfZ2lybCI6ICJzaGFya19naXJsIiwgInNoYXJrZ2lybCI6ICJzaGFya19naXJsIiwgImVuc2xhdmVkIjogInNsYXZlIiwgImVuc2xhdmVkX3JveWFsIjogInNs'
    'YXZlIiwgInNsYXZlX2JveSI6ICJzbGF2ZSIsICJzbGF2ZWJveSI6ICJzbGF2ZSIsICJzbGF2ZWdpcmwiOiAic2xhdmUiLCAic2xhdmVzIjogInNsYXZlIiwgInRhbWVkIjogIn'
    'NsYXZlIiwgImdvbyI6ICJzbGltZSIsICJnb29fYm95IjogInNsaW1lIiwgImdvb19jcmVhdHVyZSI6ICJzbGltZSIsICJnb29faGFpciI6ICJzbGltZSIsICJnb29faHVtYW5v'
    'aWQiOiAic2xpbWUiLCAiZ29vX21vbnN0ZXIiOiAic2xpbWUiLCAiZ29vX3RlbnRhY2xlIjogInNsaW1lIiwgImdvb190ZW50YWNsZXMiOiAic2xpbWUiLCAiZ29vX3RyYW5zZm'
    '9ybWF0aW9uIjogInNsaW1lIiwgImdvb2V5IjogInNsaW1lIiwgInNsaW1lX2JveSI6ICJzbGltZSIsICJzbGltZV9oYWlyIjogInNsaW1lIiwgInNsaW1lX21vbnN0ZXIiOiAi'
    'c2xpbWUiLCAic2xpbWVib3kiOiAic2xpbWUiLCAic2xpbXkiOiAic2xpbWUiLCAiaGVhbF9zbHV0IjogInNsdXQiLCAiaGVhbHNsdXQiOiAic2x1dCIsICJzbHV0X2JlbHQiOi'
    'Aic2x1dCIsICJzbHV0X2NhcCI6ICJzbHV0IiwgInNsdXRfY29sbGFyIjogInNsdXQiLCAic2x1dF9raXR0eSI6ICJzbHV0IiwgInNsdXRfb3duZXIiOiAic2x1dCIsICJzbHV0'
    'X3ByaW50IjogInNsdXQiLCAid2VuY2giOiAic2x1dCIsICJ3aG9yZSI6ICJzbHV0IiwgImNvYnJhIjogInNuYWtlIiwgInB5dGhvbiI6ICJzbmFrZSIsICJzcXVpcnRpbmciOi'
    'Aic3F1aXJ0IiwgIm9kb3IiOiAic3RpbmsiLCAic21lbGx5IjogInN0aW5rIiwgInNtZWxseV9hc3MiOiAic3RpbmsiLCAic21lbGx5X2NvY2siOiAic3RpbmsiLCAic21lbGx5'
    'X2ZlZXQiOiAic3RpbmsiLCAic3RpbmtfbGluZXMiOiAic3RpbmsiLCAic3Rpbmt5IjogInN0aW5rIiwgInN0aW5reV9mZWV0IjogInN0aW5rIiwgImhldGVybyI6ICJzdHJhaW'
    'dodCIsICJoZXRlcm9fc2V4IjogInN0cmFpZ2h0IiwgImhldGVyb3NleHVhbCI6ICJzdHJhaWdodCIsICJyZWNlaXZpbmdfcG92IjogInRha2VyX3BvdiIsICJzdWJtaXNzaXZl'
    'X3BvdiI6ICJ0YWtlcl9wb3YiLCAiZm94X3RhdXIiOiAidGF1ciIsICJmb3h0YXVyIjogInRhdXIiLCAid29sZl90YXVyIjogInRhdXIiLCAid29sZnRhdXIiOiAidGF1ciIsIC'
    'J0ZWtrZW5fNV9kYXJrX3Jlc3VycmVjdGlvbiI6ICJ0ZWtrbiIsICJ0ZWtrZW5fdGFnX3RvdXJuYW1lbnQiOiAidGVra24iLCAidGVra2VuX3RhZ190b3VybmFtZW50XzIiOiAi'
    'dGVra24iLCAidGVudGFjbGVfX2luX21vdXRoIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX2ZlbGxhdGlvIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX2dyYWIiOiAidGVudGFjbG'
    'UiLCAidGVudGFjbGVfaGFpciI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9pbl9hbnVzIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX2luX2FzcyI6ICJ0ZW50YWNsZSIsICJ0ZW50'
    'YWNsZV9pbl9wdXNzeSI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9tb25zdGVyIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX29uX2ZlbWFsZSI6ICJ0ZW50YWNsZSIsICJ0ZW50YW'
    'NsZV9vbl9mdXRhIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX29uX21hbGUiOiAidGVudGFjbGUiLCAidGVudGFjbGVfcGVuZXRyYXRpb24iOiAidGVudGFjbGUiLCAidGVudGFj'
    'bGVfcGl0IjogInRlbnRhY2xlIiwgInRlbnRhY2xlX3JhcGUiOiAidGVudGFjbGUiLCAidGVudGFjbGVfc2V4IjogInRlbnRhY2xlIiwgInRlbnRhY2xlam9iIjogInRlbnRhY2'
    'xlIiwgInRlbnRhY2xlc19vbl9mZW1hbGUiOiAidGVudGFjbGUiLCAidGVudGFjbGVzX29uX2Z1dGEiOiAidGVudGFjbGUiLCAidGVudGFjbGVzX29uX21hbGUiOiAidGVudGFj'
    'bGUiLCAidGllZF9hcm1zIjogInRpZWRfdXAiLCAidGllZF9iYWxscyI6ICJ0aWVkX3VwIiwgInRpZWRfZG93biI6ICJ0aWVkX3VwIiwgInRpZWRfZmVldCI6ICJ0aWVkX3VwIi'
    'wgInRpZWRfaGFpciI6ICJ0aWVkX3VwIiwgInRpZWRfaGFuZHMiOiAidGllZF91cCIsICJ0aWVkX2xlZ3MiOiAidGllZF91cCIsICJ0aWVkX3BlbmlzIjogInRpZWRfdXAiLCAi'
    'dGllZF90b2VzIjogInRpZWRfdXAiLCAidG9ydHVyZV9jaGFtYmVyIjogInRvcnR1cmUiLCAidG9ydHVyZV9kZXZpY2UiOiAidG9ydHVyZSIsICJ0b3J0dXJlX3JhY2siOiAidG'
    '9ydHVyZSIsICJ0b3J0dXJlZCI6ICJ0b3J0dXJlIiwgInRvcnR1cmVyIjogInRvcnR1cmUiLCAidG9ydHVyZXMiOiAidG9ydHVyZSIsICJ0b3J0dXJpbmciOiAidG9ydHVyZSIs'
    'ICJhbWJpZ3VvdXNfZ2VuZGVyIjogInRyYW5zIiwgImNyb3NzZ2VuZGVyIjogInRyYW5zIiwgImdlbmRlcl9iZW5kZXIiOiAidHJhbnMiLCAiZ2VuZGVyX3RyYW5zb2ZybWF0aW'
    '9uIjogInRyYW5zIiwgImdlbmRlcmJlbmQiOiAidHJhbnMiLCAiZ2VuZGVyYmVuZGVyIjogInRyYW5zIiwgImdlbmRlcmJlbnQiOiAidHJhbnMiLCAiZ2VuZGVyc3dhcCI6ICJ0'
    'cmFucyIsICJtYWxlX2hlcm0iOiAidHJhbnMiLCAibWFsZWhlcm0iOiAidHJhbnMiLCAibWFuX2Jvb2JzIjogInRyYW5zIiwgIm1hbl90aXRzIjogInRyYW5zIiwgIm1hbmJvb2'
    'JzIjogInRyYW5zIiwgIm10YV9jcm9zc2dlbmRlciI6ICJ0cmFucyIsICJtdGFfdHJhbnNmb3JtYXRpb24iOiAidHJhbnMiLCAibXRmIjogInRyYW5zIiwgIm10Zl9jcm9zc2dl'
    'bmRlciI6ICJ0cmFucyIsICJtdGZfdHJhbnNmb3JtYXRpb24iOiAidHJhbnMiLCAibXRnX2Nyb3NzZ2VuZGVyIjogInRyYW5zIiwgIm10Z190cmFuc2Zvcm1hdGlvbiI6ICJ0cm'
    'FucyIsICJtdGhfY3Jvc3NnZW5kZXIiOiAidHJhbnMiLCAibXRoX3RyYW5zZm9ybWF0aW9uIjogInRyYW5zIiwgIm10aV9jcm9zc2dlbmRlciI6ICJ0cmFucyIsICJtdGlfdHJh'
    'bnNmb3JtYXRpb24iOiAidHJhbnMiLCAidHViZV9mZWVkaW5nIjogInR1YmUiLCAidHViZV9nYWciOiAidHViZSIsICJ0dWJlX2luX2FzcyI6ICJ0dWJlIiwgInR1YmVfaW5fbW'
    '91dGgiOiAidHViZSIsICJ0dWJlcyI6ICJ0dWJlIiwgInVnbHlfYmFzdGFyZCI6ICJ1Z2x5IiwgInVnbHlfZmVtYWxlIjogInVnbHkiLCAidWdseV9mdXRhIjogInVnbHkiLCAi'
    'dWdseV9tYWxlIjogInVnbHkiLCAidWdseV9tYW4iOiAidWdseSIsICJ1cmV0aHJhbCI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX2JlYWRzIjogInVyZXRocmEiLCAidXJldGhyYW'
    'xfYnVsZ2UiOiAidXJldGhyYSIsICJ1cmV0aHJhbF9maW5nZXJpbmciOiAidXJldGhyYSIsICJ1cmV0aHJhbF9maXN0aW4iOiAidXJldGhyYSIsICJ1cmV0aHJhbF9pbnNlcnRp'
    'b24iOiAidXJldGhyYSIsICJ1cmV0aHJhbF9saWNraW5nIjogInVyZXRocmEiLCAidXJldGhyYWxfb3ZpcG9zaXRpb24iOiAidXJldGhyYSIsICJ1cmV0aHJhbF9wZW5ldHJhdG'
    'lvbiI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX3BsdWciOiAidXJldGhyYSIsICJ1cmV0aHJhbF9zZXgiOiAidXJldGhyYSIsICJ2aW9sYXRlZCI6ICJ2aW9sZW5jZSIsICJ2aW9s'
    'YXRpb24iOiAidmlvbGVuY2UiLCAidmlvbGVudCI6ICJ2aW9sZW5jZSIsICJhbmFsX3ZvcmUiOiAidm9yZSIsICJjb2NrX3ZvcmUiOiAidm9yZSIsICJkZXZvdXJlZCI6ICJ2b3'
    'JlIiwgImRldm91cmluZyI6ICJ2b3JlIiwgImRpZ2VzdGlvbiI6ICJ2b3JlIiwgIm1hc3Nfdm9yZSI6ICJ2b3JlIiwgIm9yYWxfdm9yZSI6ICJ2b3JlIiwgInBsYW50X3ZvcmUi'
    'OiAidm9yZSIsICJwb3N0X3ZvcmUiOiAidm9yZSIsICJzb2Z0X3ZvcmUiOiAidm9yZSIsICJ2b3JlX3NleCI6ICJ2b3JlIiwgIndhcmhhbW1lcl80MDAwMCI6ICJ3YXJoYW1tZX'
    'IiLCAid2FyaGFtbWVyXzQwayI6ICJ3YXJoYW1tZXIiLCAid29sZmdpcmwiOiAid29sZl9naXJsIiwgIndvdyI6ICJ3b3JsZF9vZl93YXJjcmFmdCIsICJ4cmF5X3ZpZXciOiAi'
    'eHJheSIsICJ6ZWJyb2lkIjogInplYnJhIiwgInpvbWJpZV9mdXRhIjogInpvbWJpZSIsICJ6b21iaWVzIjogInpvbWJpZSJ9'
)
TAG_ALIASES = loads(b64decode(TAG_ALIASES_STR))  # type: Dict[str, str]

__UPDATE_TAG_ALIASES__ = False
if __UPDATE_TAG_ALIASES__:
    from base64 import b64encode
    [TAG_ALIASES.pop(k) for k in []]
    TAG_ALIASES.update({
    })
    TAG_ALIASES = {
        k: v
        for k, v in
        sorted(sorted(TAG_ALIASES.items(), key=lambda item: item[0]), key=lambda item: item[1])
    }  # type: Dict[str, str]
    TAG_ALIASES_STR = b64encode(str(TAG_ALIASES).replace('\'', '"').encode()).decode()


def append_filtered_tags(add_string: str, tags_str: str, re_tags_to_process: Pattern, re_tags_to_exclude: Pattern) -> str:
    if len(tags_str) == 0:
        return add_string

    tags_list = tags_str.split(' ')
    tags_toadd_list = []  # type: List[str]

    for tag in tags_list:
        tag = tag.replace('-', '').replace('\'', '')
        if TAG_ALIASES.get(tag) is None and re_fullmatch(re_tags_to_process, tag) is None:
            continue

        # digital_media_(artwork)
        aser_match = re_fullmatch(r'^([^(]+)\(([^)]+)\).*$', tag)
        aser_valid = False
        if aser_match:
            major_skip_match1 = re_fullmatch(re_tags_exclude_major1, aser_match.group(1))
            major_skip_match2 = re_fullmatch(re_tags_exclude_major2, aser_match.group(2))
            if major_skip_match1 or major_skip_match2:
                continue
            stag = trim_undersores(aser_match.group(1))
            if len(stag) >= 14:
                continue
            tag = stag
            aser_valid = True

        tag = trim_undersores(tag)
        alias = TAG_ALIASES.get(tag)
        if alias:
            tag = alias

        if re_fullmatch(re_tags_to_exclude, tag):
            continue

        do_add = True
        if len(tags_toadd_list) > 0:
            nutag = re_sub(r'[^a-z]+', '', re_sub(re_numbered_or_counted_tag, r'\1', tag))
            # try and see
            # 1) if this tag can be consumed by existing tags
            # 2) if this tag can consume existing tags
            for i in reversed(range(len(tags_toadd_list))):
                t = re_sub(re_numbered_or_counted_tag, r'\1', tags_toadd_list[i].lower())
                nut = re_sub(r'[^a-z]+', '', t)
                if len(nut) >= len(nutag) and (nutag in nut):
                    do_add = False
                    break
            if do_add:
                for i in reversed(range(len(tags_toadd_list))):
                    t = re_sub(re_numbered_or_counted_tag, r'\1', tags_toadd_list[i].lower())
                    nut = re_sub(r'[^a-z]+', '', t)
                    if len(nutag) >= len(nut) and (nut in nutag):
                        if aser_valid is False and tags_toadd_list[i][0].isupper():
                            aser_valid = True
                        del tags_toadd_list[i]
        if do_add:
            if aser_valid:
                for i, c in enumerate(tag):  # type: int, str
                    if (i == 0 or tag[i - 1] == UNDERSCORE) and c.isalpha():
                        tag = f'{tag[:i]}{c.upper()}{tag[i + 1:]}'
            tags_toadd_list.append(tag)

    return f'{add_string}{UNDERSCORE}{re_sub(re_replace_symbols, UNDERSCORE, UNDERSCORE.join(sorted(tags_toadd_list)))}'

#
#
#########################################
