# coding=UTF-8
"""
Author: trickerer (https://github.com/trickerer, https://github.com/trickerer01)
"""
#########################################
#
#

# native
from base64 import b64decode
from json import loads
from re import compile as re_compile
from typing import Pattern, Dict, List

# internal
from app_gui_defines import UNDERSCORE
from app_re import re_replace_symbols, re_tags_exclude_major1, re_tags_exclude_major2, re_numbered_or_counted_tag
from app_utils import trim_undersores

__all__ = ('append_filtered_tags',)

re_meta_group = re_compile(r'^([^(]+)\(([^)]+)\).*?$')
re_not_a_letter = re_compile(r'[^a-z]+')


TAG_ALIASES_STR = (
    'eyJidW5ueV9ib3kiOiAiMStib3lzIiwgIm1hbGUiOiAiMStib3lzIiwgIm1hbGVfc29sbyI6ICIxK2JveXMiLCAibWFsZWRvbSI6ICIxK2JveXMiLCAibWFsZXN1YiI6ICIxK2'
    'JveXMiLCAibW9uc3Rlcl9ib3kiOiAiMStib3lzIiwgIm9yY19tYWxlIjogIjErYm95cyIsICIxMDFfZGFsbWF0aWFuX3N0cmVldCI6ICIxMDFfZGFsbWF0aWFucyIsICIybWFs'
    'ZSI6ICIyYm95cyIsICIybWFsZXMiOiAiMmJveXMiLCAiM21hbGUiOiAiM2JveXMiLCAiNjlfcG9zZSI6ICI2OSIsICI2OV9wb3NpdGlvbiI6ICI2OSIsICI2OV9zdGFuZGluZy'
    'I6ICI2OSIsICJzdGFuZGluZ182OSI6ICI2OSIsICJhbnl0aGluZ19kaWZmdXNpb24iOiAiYWlfZ2VuZXJhdGVkIiwgImNoaWxsX2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQi'
    'LCAiaGVudGFpX2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQiLCAibGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJtYWlfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZC'
    'IsICJuYWlfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJwaXJhdGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJybnN0YWJsZV9kaWZmdXNpb24iOiAiYWlfZ2Vu'
    'ZXJhdGVkIiwgInNlbnN1YWxfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJzdGFibGVfZGlmZnVzaW9uIjogImFpX2dlbmVyYXRlZCIsICJ0YWJsZV9kaWZmdXNpb24iOi'
    'AiYWlfZ2VuZXJhdGVkIiwgIndhaWZ1X2RpZmZ1c2lvbiI6ICJhaV9nZW5lcmF0ZWQiLCAieXVraV9kaWZmdXNpb24iOiAiYWlfZ2VuZXJhdGVkIiwgInhlbm9tb3JwaCI6ICJh'
    'bGllbiIsICJhbmFsX3NleCI6ICJhbmFsIiwgImFuYWxpbmd1cyI6ICJhbmFsIiwgImFuaWxpbmd1cyI6ICJhbmFsIiwgInJlY3R1bSI6ICJhbmFsIiwgInNzYmJ3IjogImJidy'
    'IsICJiZHNtX2NvbGxhciI6ICJiZHNtIiwgImJkc21fZ2VhciI6ICJiZHNtIiwgImJkc21faGFybmVzcyI6ICJiZHNtIiwgImJkc21fb3V0Zml0IjogImJkc20iLCAiYmRzbV9y'
    'b29tIjogImJkc20iLCAiYmRzbV9zdWl0IjogImJkc20iLCAiYnNkbSI6ICJiZHNtIiwgIm1hc29jaGlzbSI6ICJiZHNtIiwgIm1hc29jaGlzdCI6ICJiZHNtIiwgImFsbGlnYX'
    'RvciI6ICJiZWFzdCIsICJhbmltYWwiOiAiYmVhc3QiLCAiZmVyYWwiOiAiYmVhc3QiLCAiZmVyYWxfb25fZmVyYWwiOiAiYmVhc3QiLCAiZmVyYWxfcGVuZXRyYXRlZCI6ICJi'
    'ZWFzdCIsICJmZXJhbF9wZW5ldHJhdGluZyI6ICJiZWFzdCIsICJtYW1tYWwiOiAiYmVhc3QiLCAibWVwaGl0aWQiOiAiYmVhc3QiLCAib2NlbG90IjogImJlYXN0IiwgInByb2'
    'N5b25pZCI6ICJiZWFzdCIsICJyZXB0aWxlIjogImJlYXN0IiwgInJvZGVudCI6ICJiZWFzdCIsICJlZ2dfYnVsZ2UiOiAiYmVsbHlfYnVsZ2UiLCAic3RvbWFjaF9idWxnZSI6'
    'ICJiZWxseV9idWxnZSIsICJmZW1hbGVfb25fZmVyYWwiOiAiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9hbnRocm8iOiAiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9mZW1hbGUiOi'
    'AiYmVzdGlhbGl0eSIsICJmZXJhbF9vbl9odW1hbiI6ICJiZXN0aWFsaXR5IiwgImZlcmFsX29uX21hbGUiOiAiYmVzdGlhbGl0eSIsICJodW1hbl9vbl9mZXJhbCI6ICJiZXN0'
    'aWFsaXR5IiwgIm1hbGVfb25fZmVyYWwiOiAiYmVzdGlhbGl0eSIsICJ6b29waGlsaWEiOiAiYmVzdGlhbGl0eSIsICJiaW1ib19hbnRocm8iOiAiYmltYm8iLCAiYmltYm9fYm'
    '9keSI6ICJiaW1ibyIsICJiaW1ib19mdXRhbmFyaSI6ICJiaW1ibyIsICJiaW1ib19saXAiOiAiYmltYm8iLCAiYmltYm9fbGlwcyI6ICJiaW1ibyIsICJiaW1ib19zdWNjdWJ1'
    'cyI6ICJiaW1ibyIsICJiaW1ib2VkIjogImJpbWJvIiwgImJpbWJvZmljYXRpb24iOiAiYmltYm8iLCAiYmltYm9maWVkIjogImJpbWJvIiwgImJpbWJvcyI6ICJiaW1ibyIsIC'
    'JiaWtlc3VpdCI6ICJib2R5c3VpdCIsICJiaW9zdWl0IjogImJvZHlzdWl0IiwgImJpdGNoX3N1aXQiOiAiYm9keXN1aXQiLCAiYml0Y2hzdWl0IjogImJvZHlzdWl0IiwgImJ1'
    'bm55X3N1aXQiOiAiYm9keXN1aXQiLCAiYnVubnlzdWl0IjogImJvZHlzdWl0IiwgImNhdF9zdWl0IjogImJvZHlzdWl0IiwgImNhdHN1aXQiOiAiYm9keXN1aXQiLCAiZ2ltcF'
    '9zdWl0IjogImJvZHlzdWl0IiwgImdpbXBzdWl0IjogImJvZHlzdWl0IiwgInBsdWdfc3VpdCI6ICJib2R5c3VpdCIsICJwbHVnc3VpdCI6ICJib2R5c3VpdCIsICJzd2ltX3N1'
    'aXQiOiAiYm9keXN1aXQiLCAic3dpbXN1aXQiOiAiYm9keXN1aXQiLCAiemVyb19zdWl0IjogImJvZHlzdWl0IiwgInplcm9zdWl0IjogImJvZHlzdWl0IiwgImJvdW5kIjogIm'
    'JvbmRhZ2UiLCAiYm91bmRfYXJtcyI6ICJib25kYWdlIiwgImJvdW5kX2ZlZXQiOiAiYm9uZGFnZSIsICJib3VuZF9oYW5kcyI6ICJib25kYWdlIiwgImJvdW5kX2xlZ3MiOiAi'
    'Ym9uZGFnZSIsICJib3VuZF9uZWNrIjogImJvbmRhZ2UiLCAiYm91bmRfcGVuaXMiOiAiYm9uZGFnZSIsICJib3VuZF90b19iZWQiOiAiYm9uZGFnZSIsICJib3VuZF90b19jaG'
    'FpciI6ICJib25kYWdlIiwgImJvdW5kX3dyaXN0cyI6ICJib25kYWdlIiwgImJyZWFzdF9ib25kYWdlIjogImJvbmRhZ2UiLCAiY2hhaXJfYm9uZGFnZSI6ICJib25kYWdlIiwg'
    'Im11bW1pZmljYXRpb24iOiAiYm9uZGFnZSIsICJtdW1taWZpZWQiOiAiYm9uZGFnZSIsICJwcmVkaWNhbWVudF9ib25kYWdlIjogImJvbmRhZ2UiLCAicmVzdHJhaW4iOiAiYm'
    '9uZGFnZSIsICJyZXN0cmFpbmVkIjogImJvbmRhZ2UiLCAicmVzdHJhaW50IjogImJvbmRhZ2UiLCAicmVzdHJhaW50cyI6ICJib25kYWdlIiwgInJpYmJvbl9ib25kYWdlIjog'
    'ImJvbmRhZ2UiLCAicm9wZV9ib25kYWdlIjogImJvbmRhZ2UiLCAic2hpYmFyaSI6ICJib25kYWdlIiwgInN0ZWVsX2JvbmRhZ2UiOiAiYm9uZGFnZSIsICJzdHJhcHBhZG8iOi'
    'AiYm9uZGFnZSIsICJzdHJhcHBlZF9kb3duIjogImJvbmRhZ2UiLCAic3VzcGVuZGVkIjogImJvbmRhZ2UiLCAic3VzcGVuc2lvbiI6ICJib25kYWdlIiwgInN1c3BlbnNpb25f'
    'Ym9uZGFnZSI6ICJib25kYWdlIiwgInRhaWxfYm9uZGFnZSI6ICJib25kYWdlIiwgInRhcGVfYm9uZGFnZSI6ICJib25kYWdlIiwgIndlYl9ib25kYWdlIjogImJvbmRhZ2UiLC'
    'AiYm92aW5lIjogImJvdmlkIiwgImNhbmluIjogImNhbmlkIiwgImNhbmluZSI6ICJjYW5pZCIsICJjYW5pcyI6ICJjYW5pZCIsICJjb2xsaWUiOiAiY2FuaWQiLCAiZGlyZV93'
    'b2xmIjogImNhbmlkIiwgImRvYmVybWFuIjogImNhbmlkIiwgImh1c2t5IjogImNhbmlkIiwgImxhYnJhZG9yIjogImNhbmlkIiwgIm1hbGFtdXRlIjogImNhbmlkIiwgIm1hc3'
    'RpZmYiOiAiY2FuaWQiLCAicGl0X2J1bGwiOiAiY2FuaWQiLCAicGl0YnVsbCI6ICJjYW5pZCIsICJwb29kbGUiOiAiY2FuaWQiLCAicmV0cmlldmVyIjogImNhbmlkIiwgInNh'
    'bW95ZWQiOiAiY2FuaWQiLCAic3BhbmllbCI6ICJjYW5pZCIsICJ3b2xmIjogImNhbmlkIiwgIndvbGZkb2ciOiAiY2FuaWQiLCAiYWJkdWN0ZWQiOiAiY2FwdHVyZWQiLCAiYW'
    'JkdWN0aW9uIjogImNhcHR1cmVkIiwgImFycmVzdGVkIjogImNhcHR1cmVkIiwgImNhZ2VkIjogImNhcHR1cmVkIiwgImNhcHRpdmUiOiAiY2FwdHVyZWQiLCAiY2FwdHVyZSI6'
    'ICJjYXB0dXJlZCIsICJjaGFpbmVkIjogImNhcHR1cmVkIiwgImRldGFpbmVkIjogImNhcHR1cmVkIiwgImphaWxlZCI6ICJjYXB0dXJlZCIsICJraWRuYXAiOiAiY2FwdHVyZW'
    'QiLCAia2lkbmFwcGVkIjogImNhcHR1cmVkIiwgImtpZG5hcHBpbmciOiAiY2FwdHVyZWQiLCAic2hhY2tsZWQiOiAiY2FwdHVyZWQiLCAidHJhcHBlZCI6ICJjYXB0dXJlZCIs'
    'ICJjYXRnaXJsIjogImNhdF9naXJsIiwgImRlZXJfdGF1ciI6ICJjZW50YXVyIiwgImRlZXJ0YXVyIjogImNlbnRhdXIiLCAiY2VydmluZSI6ICJjZXJ2aWQiLCAiYmx1ZV9jdW'
    '0iOiAiY3VtIiwgImN1bV9iYXRoIjogImN1bSIsICJjdW1fYmVsbHkiOiAiY3VtIiwgImN1bV9idWJibGUiOiAiY3VtIiwgImN1bV9idWNrZXQiOiAiY3VtIiwgImN1bV9jb3Zl'
    'cmVkIjogImN1bSIsICJjdW1fZHJpbmtpbmciOiAiY3VtIiwgImN1bV9kcmlwIjogImN1bSIsICJjdW1fZHJpcHBpbmciOiAiY3VtIiwgImN1bV9maWxsZWQiOiAiY3VtIiwgIm'
    'N1bV9mbG9vZCI6ICJjdW0iLCAiY3VtX2Zyb21fYXNzIjogImN1bSIsICJjdW1fZnJvbV9wdXNzeSI6ICJjdW0iLCAiY3VtX2dsYXplIjogImN1bSIsICJjdW1faHVuZ3J5Ijog'
    'ImN1bSIsICJjdW1faW5fYW51cyI6ICJjdW0iLCAiY3VtX2luX2FzcyI6ICJjdW0iLCAiY3VtX2luX2Nsb3RoZXMiOiAiY3VtIiwgImN1bV9pbl9jb25kb20iOiAiY3VtIiwgIm'
    'N1bV9pbl9jb250YWluZXIiOiAiY3VtIiwgImN1bV9pbl9oYWlyIjogImN1bSIsICJjdW1faW5fbW91dGgiOiAiY3VtIiwgImN1bV9pbl9ub3NlIjogImN1bSIsICJjdW1faW5f'
    'cHVzc3kiOiAiY3VtIiwgImN1bV9pbl90aHJvYXQiOiAiY3VtIiwgImN1bV9pbl91dGVydXMiOiAiY3VtIiwgImN1bV9pbnNpZGUiOiAiY3VtIiwgImN1bV9qYXIiOiAiY3VtIi'
    'wgImN1bV9raXNzIjogImN1bSIsICJjdW1fbGVhayI6ICJjdW0iLCAiY3VtX2xlYWtpbmciOiAiY3VtIiwgImN1bV9saWNrIjogImN1bSIsICJjdW1fbWlsa2luZyI6ICJjdW0i'
    'LCAiY3VtX29uX2FzcyI6ICJjdW0iLCAiY3VtX29uX2JhbGxzIjogImN1bSIsICJjdW1fb25fYm9keSI6ICJjdW0iLCAiY3VtX29uX2JyZWFzdHMiOiAiY3VtIiwgImN1bV9vbl'
    '9idXR0IjogImN1bSIsICJjdW1fb25fY2hlc3QiOiAiY3VtIiwgImN1bV9vbl9jbG90aGVzIjogImN1bSIsICJjdW1fb25fZmFjZSI6ICJjdW0iLCAiY3VtX29uX2ZlZXQiOiAi'
    'Y3VtIiwgImN1bV9vbl9ncm91bmQiOiAiY3VtIiwgImN1bV9vbl9oYWlyIjogImN1bSIsICJjdW1fb25faGFuZCI6ICJjdW0iLCAiY3VtX29uX2xlZyI6ICJjdW0iLCAiY3VtX2'
    '9uX3BlbmlzIjogImN1bSIsICJjdW1fb25fc2VsZiI6ICJjdW0iLCAiY3VtX29uX3N0b21hY2giOiAiY3VtIiwgImN1bV9vbl90b25ndWUiOiAiY3VtIiwgImN1bV9wb29sIjog'
    'ImN1bSIsICJjdW1fcHVkZGxlIjogImN1bSIsICJjdW1fcmluZyI6ICJjdW0iLCAiY3VtX3Nob3QiOiAiY3VtIiwgImN1bV9zcGF0dGVyIjogImN1bSIsICJjdW1fc3F1aXJ0Ij'
    'ogImN1bSIsICJjdW1fc3RhaW4iOiAiY3VtIiwgImN1bV9zdHJhbmQiOiAiY3VtIiwgImN1bV9zdHJpbmciOiAiY3VtIiwgImN1bV9zd2FsbG93IjogImN1bSIsICJjdW1fc3dh'
    'cCI6ICJjdW0iLCAiY3VtZHJpcCI6ICJjdW0iLCAiY3VtZHVtcCI6ICJjdW0iLCAiY3VtbHViZSI6ICJjdW0iLCAiY3VtbWluZyI6ICJjdW0iLCAiY3VtcG9vbCI6ICJjdW0iLC'
    'AiY3Vtc2VhIjogImN1bSIsICJjdW1zaG90IjogImN1bSIsICJjdW1zbHV0IjogImN1bSIsICJjdW1zdHJpbmciOiAiY3VtIiwgImdyZWVuX2N1bSI6ICJjdW0iLCAicHJlY3Vt'
    'IjogImN1bSIsICJ0aGlja19jdW0iOiAiY3VtIiwgImhhbmFfc29uZyI6ICJkLnZhIiwgImRhbmdhbnJvbnBhX3YzIjogImRhbmdhbnJvbnBhIiwgIm5ld19kYW5nYW5yb25wYV'
    '92MyI6ICJkYW5nYW5yb25wYSIsICJzdXBlcl9kYW5nYW5yb25wYV8yIjogImRhbmdhbnJvbnBhIiwgImRyb3dfZWxmIjogImRhcmtfZWxmIiwgImR1bm1lciI6ICJkYXJrX2Vs'
    'ZiIsICJkdW5tZXJfZWxmIjogImRhcmtfZWxmIiwgImRlYWQiOiAiZGVhdGgiLCAicm9lX2RlZXIiOiAiZGVlciIsICJkZWx0YXJ1bmVfY2hhcHRlcl8xIjogImRlbHRhcnVuZS'
    'IsICJkZWx0YXJ1bmVfY2hhcHRlcl8yIjogImRlbHRhcnVuZSIsICJkZWx0YXJ1bmVfY2hhcHRlcl8zIjogImRlbHRhcnVuZSIsICJkZW1vbl9ib3kiOiAiZGVtb24iLCAiZGVt'
    'b25faHVtYW5vaWQiOiAiZGVtb24iLCAiZGVtb25zIjogImRlbW9uIiwgImRldmlsIjogImRlbW9uIiwgImRldmlsX2dpcmwiOiAiZGVtb24iLCAiZXJlZGFyIjogImRlbW9uIi'
    'wgImRlbW9uX2dpcmwiOiAiZGVtb25lc3MiLCAiZGVtb25fZ2lybHMiOiAiZGVtb25lc3MiLCAiZGVtb25naXJsIjogImRlbW9uZXNzIiwgImRlbW9uZ2lybHMiOiAiZGVtb25l'
    'c3MiLCAiZGVycF9leWVzIjogImRlcnAiLCAiZG9nZ2lybCI6ICJkb2dfZ2lybCIsICJkd2FyZl9mZW1hbGUiOiAiZHdhcmYiLCAiZWVsX2luX2FzcyI6ICJlZWwiLCAiZWVsX2'
    'luX3B1c3N5IjogImVlbCIsICJlZWxfaW5fdXJldGhyYSI6ICJlZWwiLCAiZWVsX2luc2VydGlvbiI6ICJlZWwiLCAiZWdnX2JpcnRoIjogImVnZyIsICJlZ2dfZnJvbV9hc3Mi'
    'OiAiZWdnIiwgImVnZ19mcm9tX21vdXRoIjogImVnZyIsICJlZ2dfZnJvbV9wdXNzeSI6ICJlZ2ciLCAiZWdnX2ltcGxhbnRhdGlvbiI6ICJlZ2ciLCAiZWdnX2luX2FzcyI6IC'
    'JlZ2ciLCAiZWdnX2luX21vdXRoIjogImVnZyIsICJlZ2dfaW5fcHVzc3kiOiAiZWdnIiwgImVnZ19pbnNlcnRpb24iOiAiZWdnIiwgImVnZ19sYXlpbmciOiAiZWdnIiwgImVn'
    'Z25hbnQiOiAiZWdnIiwgImVnZ3NfaW5fc3RvbWFjaCI6ICJlZ2ciLCAib3JhbF9lZ2dfaW1wbGFudGF0aW9uIjogImVnZyIsICJlbHZlcyI6ICJlbGYiLCAiaGlnaF9lbGYiOi'
    'AiZWxmIiwgIndvb2RfZWxmIjogImVsZiIsICJlcXVpbmUiOiAiZXF1aWQiLCAiZmFjZV9zaXR0aW5nIjogImZhY2VzaXR0aW5nIiwgImZhY2VzaXQiOiAiZmFjZXNpdHRpbmci'
    'LCAiZmFjZXNpdHRpbmdfcG92IjogImZhY2VzaXR0aW5nIiwgImN1bV9mYXJ0IjogImZhcnQiLCAiZmFjZV9mYXJ0IjogImZhcnQiLCAiZmFjZWZhcnQiOiAiZmFydCIsICJmYX'
    'J0X2Nsb3VkIjogImZhcnQiLCAiZmFydF9mZXRpc2giOiAiZmFydCIsICJmYXJ0X2luX2ZhY2UiOiAiZmFydCIsICJmYXJ0X2luX21vdXRoIjogImZhcnQiLCAiZmFydF9vbl9k'
    'aWNrIjogImZhcnQiLCAiZmFydF9vbl9mYWNlIjogImZhcnQiLCAiZmFydF9zbmlmZmluZyI6ICJmYXJ0IiwgImZhcnRpbmdfaW5fZmFjZSI6ICJmYXJ0IiwgImZhcnRpbmdfaW'
    '5fbW91dGgiOiAiZmFydCIsICJmYXJ0aW5nX29uX2ZhY2UiOiAiZmFydCIsICJmYXJ0am9iIjogImZhcnQiLCAiZmFydHMiOiAiZmFydCIsICJmZWxpbmUiOiAiZmVsaWQiLCAi'
    'ZmVsaXMiOiAiZmVsaWQiLCAiZmVtYm95c3ViIjogImZlbWJveSIsICJhbmFsX2Zpc3RpbmciOiAiZmlzdGluZyIsICJhdXRvZmlzdGluZyI6ICJmaXN0aW5nIiwgImRlZXBfZm'
    'lzdGluZyI6ICJmaXN0aW5nIiwgImRvdWJsZV9maXN0aW5nIjogImZpc3RpbmciLCAic2VsZl9maXN0aW5nIjogImZpc3RpbmciLCAidmFnaW5hbF9maXN0aW5nIjogImZpc3Rp'
    'bmciLCAiZm94Z2lybCI6ICJmb3hfZ2lybCIsICJibGFja19mdXIiOiAiZnVyIiwgImJsdWVfZnVyIjogImZ1ciIsICJib2R5X2Z1ciI6ICJmdXIiLCAiYnJvd25fZnVyIjogIm'
    'Z1ciIsICJkYXJrX2Z1ciI6ICJmdXIiLCAiZ3JheV9mdXIiOiAiZnVyIiwgImdyZWVuX2Z1ciI6ICJmdXIiLCAiZ3JleV9mdXIiOiAiZnVyIiwgIm9yYW5nZV9mdXIiOiAiZnVy'
    'IiwgInBpbmtfZnVyIjogImZ1ciIsICJwdXJwbGVfZnVyIjogImZ1ciIsICJyZWRfZnVyIjogImZ1ciIsICJ0YW5fZnVyIjogImZ1ciIsICJ3ZXRfZnVyIjogImZ1ciIsICJ3aG'
    'l0ZV9mdXIiOiAiZnVyIiwgInllbGxvd19mdXIiOiAiZnVyIiwgImFudGhyb19mb2N1cyI6ICJmdXJyeSIsICJhbnRocm9fb25fYW50aHJvIjogImZ1cnJ5IiwgImFudGhyb19v'
    'bl9mZXJhbCI6ICJmdXJyeSIsICJhbnRocm9fb25seSI6ICJmdXJyeSIsICJmdXJyZWRfZHJhZ29uIjogImZ1cnJ5IiwgImZ1cnJpZmljYXRpb24iOiAiZnVycnkiLCAiZnVycn'
    'lfYXNzIjogImZ1cnJ5IiwgImZ1cnJ5X2JyZWFzdHMiOiAiZnVycnkiLCAiZnVycnlfZWFycyI6ICJmdXJyeSIsICJmdXJyeV9mZW1hbGUiOiAiZnVycnkiLCAiZnVycnlfaW50'
    'ZXJzZXgiOiAiZnVycnkiLCAiZnVycnlfbWFsZSI6ICJmdXJyeSIsICJmdXJyeV9vbmx5IjogImZ1cnJ5IiwgImZ1cnJ5X3RhaWwiOiAiZnVycnkiLCAiZnVycnlmaWNhdGlvbi'
    'I6ICJmdXJyeSIsICJtYW1tYWxfaHVtYW5vaWQiOiAiZnVycnkiLCAic2NhbGllIjogImZ1cnJ5IiwgInNleHlmdXIiOiAiZnVycnkiLCAid29yZ2VuIjogImZ1cnJ5IiwgInlp'
    'ZmYiOiAiZnVycnkiLCAieWlmZmluZyI6ICJmdXJyeSIsICJmdXRhX3dpdGhfbWFsZSI6ICJmdXRhX29uX21hbGUiLCAiZnV0YW5hcmkvbWFsZSI6ICJmdXRhX29uX21hbGUiLC'
    'AiZGVtb25fZnV0YSI6ICJmdXRhbmFyaSIsICJlbGZfZnV0YSI6ICJmdXRhbmFyaSIsICJmdXRhL2N1bnRib3kiOiAiZnV0YW5hcmkiLCAiZnV0YS9mZW1hbGUiOiAiZnV0YW5h'
    'cmkiLCAiZnV0YS9mZW1ib3kiOiAiZnV0YW5hcmkiLCAiZnV0YS9mdXRhIjogImZ1dGFuYXJpIiwgImZ1dGEvbWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhXyI6ICJmdXRhbmFyaS'
    'IsICJmdXRhX2JhbGxzIjogImZ1dGFuYXJpIiwgImZ1dGFfY29jayI6ICJmdXRhbmFyaSIsICJmdXRhX2ZvY3VzIjogImZ1dGFuYXJpIiwgImZ1dGFfZ2lhbnRlc3MiOiAiZnV0'
    'YW5hcmkiLCAiZnV0YV9pc19iaWdnZXIiOiAiZnV0YW5hcmkiLCAiZnV0YV9pc19zbWFsbGVyIjogImZ1dGFuYXJpIiwgImZ1dGFfbWlsZiI6ICJmdXRhbmFyaSIsICJmdXRhX2'
    '9uX2ZlbWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhX29uX2Z1dGEiOiAiZnV0YW5hcmkiLCAiZnV0YV9vbl90b3AiOiAiZnV0YW5hcmkiLCAiZnV0YV9vbmx5IjogImZ1dGFuYXJp'
    'IiwgImZ1dGFfcG92IjogImZ1dGFuYXJpIiwgImZ1dGFfc2Fuc19iYWxscyI6ICJmdXRhbmFyaSIsICJmdXRhX3NhbnNfcHVzc3kiOiAiZnV0YW5hcmkiLCAiZnV0YV9zb2xvIj'
    'ogImZ1dGFuYXJpIiwgImZ1dGFfc3ViIjogImZ1dGFuYXJpIiwgImZ1dGFfd2lmZSI6ICJmdXRhbmFyaSIsICJmdXRhX3dpdGhfZmVtYWxlIjogImZ1dGFuYXJpIiwgImZ1dGFf'
    'd2l0aF9mZW1ib3kiOiAiZnV0YW5hcmkiLCAiZnV0YV93aXRoX2Z1dGEiOiAiZnV0YW5hcmkiLCAiZnV0YWRvbSI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaS9jdW50Ym95IjogIm'
    'Z1dGFuYXJpIiwgImZ1dGFuYXJpL2ZlbWFsZSI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaS9mZW1ib3kiOiAiZnV0YW5hcmkiLCAiZnV0YW5hcmkvZnV0YSI6ICJmdXRhbmFyaSIs'
    'ICJmdXRhbmFyaV9wZW5ldHJhdGVkIjogImZ1dGFuYXJpIiwgImZ1dGFuYXJpX3BlbmV0cmF0aW5nIjogImZ1dGFuYXJpIiwgImZ1dGFuYXJpX3BvdiI6ICJmdXRhbmFyaSIsIC'
    'JmdXRhbmFyaV90cmFuc2Zvcm1hdGlvbiI6ICJmdXRhbmFyaSIsICJmdXRhbmFyaXphdGlvbiI6ICJmdXRhbmFyaSIsICJmdXRhc3ViIjogImZ1dGFuYXJpIiwgIm1pbmlmdXRh'
    'IjogImZ1dGFuYXJpIiwgInNvbGVfZnV0YSI6ICJmdXRhbmFyaSIsICJzb2xvX2Z1dGEiOiAiZnV0YW5hcmkiLCAiYmFsbF9nYWciOiAiZ2FnIiwgImJhbGxnYWciOiAiZ2FnIi'
    'wgImJhbWJvb19nYWciOiAiZ2FnIiwgImJpdF9nYWciOiAiZ2FnIiwgImJpdGVfZ2FnIjogImdhZyIsICJibGFja19iYWxsX2dhZyI6ICJnYWciLCAiYmx1ZV9iYWxsX2dhZyI6'
    'ICJnYWciLCAiYm9uZV9nYWciOiAiZ2FnIiwgImNsZWF2ZV9nYWciOiAiZ2FnIiwgImNsb3RoX2dhZyI6ICJnYWciLCAiY29ja19nYWciOiAiZ2FnIiwgImRlbnRhbF9nYWciOi'
    'AiZ2FnIiwgImRpbGRvX2dhZyI6ICJnYWciLCAiZ2FnX2JhbGwiOiAiZ2FnIiwgImdhZ19ib25kYWdlIjogImdhZyIsICJnYWdfaGFybmVzcyI6ICJnYWciLCAiZ2FnX21hc2si'
    'OiAiZ2FnIiwgImdhZ2dlZCI6ICJnYWciLCAiZ2FnZ2luZyI6ICJnYWciLCAiaGFuZGdhZyI6ICJnYWciLCAiaGFybmVzc19iYWxsX2dhZyI6ICJnYWciLCAiaGFybmVzc19iaX'
    'RfZ2FnIjogImdhZyIsICJoYXJuZXNzX2JpdGVfZ2FnIjogImdhZyIsICJoYXJuZXNzX2dhZyI6ICJnYWciLCAiaGFybmVzc19yaW5nX2dhZyI6ICJnYWciLCAiaW1wcm92aXNl'
    'ZF9nYWciOiAiZ2FnIiwgIm1vdXRoX2dhZyI6ICJnYWciLCAibXV6emxlX2dhZyI6ICJnYWciLCAib25haG9sZV9nYWciOiAiZ2FnIiwgIm9wZW5fbW91dGhfZ2FnIjogImdhZy'
    'IsICJvdG1fZ2FnIjogImdhZyIsICJvdmVyX3RoZV9tb3V0aF9nYWciOiAiZ2FnIiwgIm92ZXJfdGhlX25vc2VfZ2FnIjogImdhZyIsICJwYW5lbF9nYWciOiAiZ2FnIiwgInBh'
    'bnR5X2dhZyI6ICJnYWciLCAicGlua19iYWxsX2dhZyI6ICJnYWciLCAicGx1Z19nYWciOiAiZ2FnIiwgInB1cnBsZV9iYWxsX2dhZyI6ICJnYWciLCAicmVkX2JhbGxfZ2FnIj'
    'ogImdhZyIsICJyaW5nX2dhZyI6ICJnYWciLCAicm9wZV9nYWciOiAiZ2FnIiwgInJvcGVnYWciOiAiZ2FnIiwgInNoYXJlZF9nYWciOiAiZ2FnIiwgInN0dWZmZWRfbW91dGhf'
    'Z2FnIjogImdhZyIsICJ0YXBlX2dhZyI6ICJnYWciLCAidGVudGFjbGVfZ2FnIjogImdhZyIsICJ3ZWJfZ2FnIjogImdhZyIsICJ3aGl0ZV9iYWxsX2dhZyI6ICJnYWciLCAiZ2'
    'FuZ19iYW5nIjogImdhbmdiYW5nIiwgImdhbmdfcmFwZSI6ICJnYW5nYmFuZyIsICJnYW5ncmFwZSI6ICJnYW5nYmFuZyIsICJnYW5ncmFwZWQiOiAiZ2FuZ2JhbmciLCAiYW5h'
    'bF9nYXBlIjogImdhcGUiLCAiYmlnX2dhcGUiOiAiZ2FwZSIsICJnYXBpbmciOiAiZ2FwZSIsICJnYXBpbmdfYW51cyI6ICJnYXBlIiwgImdhcGluZ19hc3MiOiAiZ2FwZSIsIC'
    'JnYXBpbmdfY2xvYWNhIjogImdhcGUiLCAiZ2FwaW5nX25pcHBsZSI6ICJnYXBlIiwgImdhcGluZ19uaXBwbGVzIjogImdhcGUiLCAiZ2FwaW5nX3B1c3l5IjogImdhcGUiLCAi'
    'Z2FwaW5nX3VyZXRocmEiOiAiZ2FwZSIsICJodWdlX2dhcGUiOiAiZ2FwZSIsICJiYXJhIjogImdheSIsICJiYXJhX3RpZGRpZXMiOiAiZ2F5IiwgImJhcmFfdGl0cyI6ICJnYX'
    'kiLCAiYmFyYWthIjogImdheSIsICJiYXJha2luZyI6ICJnYXkiLCAiYmFyYWx1c3QiOiAiZ2F5IiwgImJhcmFzdWlzaG91IjogImdheSIsICJiYXJheW90IjogImdheSIsICJi'
    'YXJhem9rdSI6ICJnYXkiLCAiYmlzZXh1YWxfbWFsZSI6ICJnYXkiLCAiZ2F5X2FuYWxfbWFzdHVyYmF0aW9uIjogImdheSIsICJnYXlfYmFyIjogImdheSIsICJnYXlfYmVhci'
    'I6ICJnYXkiLCAiZ2F5X2Jsb3dqb2IiOiAiZ2F5IiwgImdheV9kZW5pYWwiOiAiZ2F5IiwgImdheV9kb2NraW5nIjogImdheSIsICJnYXlfZG9taW5hdGlvbiI6ICJnYXkiLCAi'
    'Z2F5X2hhbmRqb2IiOiAiZ2F5IiwgImdheV9oYXJlbSI6ICJnYXkiLCAiZ2F5X29yZ3kiOiAiZ2F5IiwgImdheV9wb3Juc3RhciI6ICJnYXkiLCAiZ2F5X3ByaWRlIjogImdheS'
    'IsICJnYXlfcHJpZGVfY29sb3JzIjogImdheSIsICJnYXlfc2V4IjogImdheSIsICJnYXlfc291bmQiOiAiZ2F5IiwgImdheV90b19zdHJhaWdodCI6ICJnYXkiLCAiZ2F5X3dp'
    'dGhfd29tYW4iOiAiZ2F5IiwgImdheV93cmVzdGxpbmciOiAiZ2F5IiwgImdheXRvciI6ICJnYXkiLCAibWVuX2tpc3NpbmciOiAiZ2F5IiwgImdpcmFmZmUiOiAiZ2lyYWZmaW'
    'QiLCAiZ2xwcnlfaG9sZSI6ICJnbG9yeWhvbGUiLCAiZ29vZ2lybCI6ICJnb29fZ2lybCIsICJzbGltZV9naXJsIjogImdvb19naXJsIiwgInNsaW1lZ2lybCI6ICJnb29fZ2ly'
    'bCIsICJnb3RoaWZpZWQiOiAiZ290aCIsICJtYXJlIjogImhvcnNlIiwgInBvbnkiOiAiaG9yc2UiLCAic3RhbGxpb24iOiAiaG9yc2UiLCAiaHllbmEiOiAiaHlhZW5pZCIsIC'
    'JpZ3VhbmEiOiAiaWd1YW5pZCIsICJjbG9uZWNlc3QiOiAiaW5jZXN0IiwgImltcGxpZWRfaW5jZXN0IjogImluY2VzdCIsICJtb21jZXN0IjogImluY2VzdCIsICJzZWxmY2Vz'
    'dCI6ICJpbmNlc3QiLCAidHdpbmNlc3QiOiAiaW5jZXN0IiwgImN1bV9pbmZsYXRpb24iOiAiaW5mbGF0aW9uIiwgImN1bWZsYXRpb24iOiAiaW5mbGF0aW9uIiwgImVnZ19pbm'
    'ZsYXRpb24iOiAiaW5mbGF0aW9uIiwgInNsaW1lX2luZmxhdGlvbiI6ICJpbmZsYXRpb24iLCAiaW5qdXJlIjogImluanVyeSIsICJpbmp1cmVkIjogImluanVyeSIsICJpbmp1'
    'cmVzIjogImluanVyeSIsICJhcmFjaG5pZCI6ICJpbnNlY3QiLCAiYXJ0aHJvcG9kIjogImluc2VjdCIsICJiZWUiOiAiaW5zZWN0IiwgImJlZXMiOiAiaW5zZWN0IiwgImNlbn'
    'RpcGVkZSI6ICJpbnNlY3QiLCAiY29ja3JvYXNoIjogImluc2VjdCIsICJlYXJ0aHdvcm0iOiAiaW5zZWN0IiwgImdhc3Ryb3BvZCI6ICJpbnNlY3QiLCAiaG9ybmV0IjogImlu'
    'c2VjdCIsICJpbnNlY3RvaWQiOiAiaW5zZWN0IiwgImxlZWNoIjogImluc2VjdCIsICJsZWVjaGVzIjogImluc2VjdCIsICJsb2N1c3QiOiAiaW5zZWN0IiwgImxvY3VzdHMiOi'
    'AiaW5zZWN0IiwgIm1hZ2dvdCI6ICJpbnNlY3QiLCAibWFnZ290cyI6ICJpbnNlY3QiLCAibWFudGlzIjogImluc2VjdCIsICJtb3NxdWl0byI6ICJpbnNlY3QiLCAibW90aCI6'
    'ICJpbnNlY3QiLCAicXVlZW5fYmVlIjogImluc2VjdCIsICJzcGlkZXIiOiAiaW5zZWN0IiwgInRhcmFudHVsYSI6ICJpbnNlY3QiLCAidmVzcGlkIjogImluc2VjdCIsICJ3YX'
    'NwIjogImluc2VjdCIsICJ3YXNwcyI6ICJpbnNlY3QiLCAid29ybSI6ICJpbnNlY3QiLCAid29ybXMiOiAiaW5zZWN0IiwgImthaV9zYSI6ICJrYWlzYSIsICJibGFja19sYXRl'
    'eCI6ICJsYXRleCIsICJsYXRleF9ib2R5c3VpdCI6ICJsYXRleCIsICJsYXRleF9jbG90aGluZyI6ICJsYXRleCIsICJsYXRleF9kcmVzcyI6ICJsYXRleCIsICJsYXRleF9nbG'
    '92ZXMiOiAibGF0ZXgiLCAibGF0ZXhfbGVnZ2luZ3MiOiAibGF0ZXgiLCAibGF0ZXhfbGVnd2VhciI6ICJsYXRleCIsICJsYXRleF9zdG9ja2luZ3MiOiAibGF0ZXgiLCAibGF0'
    'ZXhfc3VpdCI6ICJsYXRleCIsICJsYXRleF90aGlnaGhpZ2h0cyI6ICJsYXRleCIsICJydWJiZXIiOiAibGF0ZXgiLCAicnViYmVyX2Jvb3RzIjogImxhdGV4IiwgInJ1YmJlcl'
    '9jbG90aGluZyI6ICJsYXRleCIsICJydWJiZXJfZ2xvdmVzIjogImxhdGV4IiwgInJ1YmJlcl9zdWl0IjogImxhdGV4IiwgImxlemRvbSI6ICJsZXNiaWFuIiwgImxlenN1YiI6'
    'ICJsZXNiaWFuIiwgInl1cmkiOiAibGVzYmlhbiIsICJsaW9uZXNzIjogImxpb24iLCAibWFyaW9fZ29sZiI6ICJtYXJpbyIsICJtYXJpb19rYXJ0IjogIm1hcmlvIiwgIm1hcm'
    'lvX3BhcnR5IjogIm1hcmlvIiwgIm1hcmlvX3Rlbm5pcyI6ICJtYXJpbyIsICJwYXBlcl9tYXJpbyI6ICJtYXJpbyIsICJzdXBlcl9tYXJpbyI6ICJtYXJpbyIsICJzdXBlcl9t'
    'YXJpb182NCI6ICJtYXJpbyIsICJteV9saXR0bGVfcG9ueSI6ICJtbHAiLCAibXlfbGl0dGxlX3BvbnlfZnJpZW5kc2hpcF9pc19tYWdpYyI6ICJtbHAiLCAibXlfbGl0dGxlX3'
    'BvbnlfdGhlX21vdmllIjogIm1scCIsICJnYXJnb3lsZSI6ICJtb25zdGVyIiwgImdhcmdveWxlcyI6ICJtb25zdGVyIiwgIm1vdXNlZ2lybCI6ICJtb3VzZV9naXJsIiwgIm11'
    'c3RlbGEiOiAibXVzdGVsaWQiLCAibXVzdGVsaW5lIjogIm11c3RlbGlkIiwgIm5hcnV0bzpfdGhlX2xhc3QiOiAibmFydXRvIiwgIm5hcnV0b19ib21iIjogIm5hcnV0byIsIC'
    'JuYXJ1dG9fc2hpcHB1bmRlbiI6ICJuYXJ1dG8iLCAibmllcjpfYXV0b21hdGEiOiAibmllciIsICJuaWVyX3JlcGxpY2FudCI6ICJuaWVyIiwgImthbGRvcmVpIjogIm5pZ2h0'
    'X2VsZiIsICJudW1idWhfNSI6ICJudW1iYWhfNSIsICJibG93am9iIjogIm9yYWwiLCAiZmFjZV9mdWNrIjogIm9yYWwiLCAiZmFjZV9mdWNraW5nIjogIm9yYWwiLCAiZmFjZW'
    'Z1Y2siOiAib3JhbCIsICJmZWxsYXRpbyI6ICJvcmFsIiwgIm9yYWxfY3JlYW1waWUiOiAib3JhbCIsICJvcmFsX2luc2VydGlvbiI6ICJvcmFsIiwgIm9yYWxfa25vdHRpbmci'
    'OiAib3JhbCIsICJvcmFsX21hc3R1cmJhdGlvbiI6ICJvcmFsIiwgIm9yYWxfcGVuZXRyYXRpb24iOiAib3JhbCIsICJvcmFsX3JhcGUiOiAib3JhbCIsICJvcmFsX3NleCI6IC'
    'JvcmFsIiwgInNwaXRyb2FzdCI6ICJvcmFsIiwgInN1Y2tpbmciOiAib3JhbCIsICJ0b25ndWVfam9iIjogIm9yYWwiLCAidG9uZ3Vlam9iIjogIm9yYWwiLCAiM3NvbWUiOiAi'
    'b3JneSIsICI0c29tZSI6ICJvcmd5IiwgIjVzb21lIjogIm9yZ3kiLCAiNnNvbWUiOiAib3JneSIsICJmaXZlc29tZSI6ICJvcmd5IiwgImZvdXJzb21lIjogIm9yZ3kiLCAiZ3'
    'JvdXBfc2V4IjogIm9yZ3kiLCAic2l4c29tZSI6ICJvcmd5IiwgInRocmVlc29tZSI6ICJvcmd5IiwgInBlcnNvbmFfM19wb3J0YWJsZSI6ICJwZXJzb25hXzMiLCAicGVyc29u'
    'YV80X2FyZW5hIjogInBlcnNvbmFfNCIsICJwZXJzb25hXzRfdGhlX2dvbGRlbiI6ICJwZXJzb25hXzQiLCAicGVyc29uYV81X3JveWFsIjogInBlcnNvbmFfNSIsICJwZXRnaX'
    'J0bCI6ICJwZXRfZ2lybCIsICJhc3Npc3RlZF9wZWUiOiAicGlzc2luZyIsICJkcmlua2luZ19wZWUiOiAicGlzc2luZyIsICJtb3V0aF9wZWUiOiAicGlzc2luZyIsICJwYW50'
    'eV9wZWUiOiAicGlzc2luZyIsICJwZWVpbmciOiAicGlzc2luZyIsICJzaXR0aW5nX3BlZSI6ICJwaXNzaW5nIiwgInN0YW5kaW5nX3BlZSI6ICJwaXNzaW5nIiwgInVyaW5hdG'
    'luZyI6ICJwaXNzaW5nIiwgInVyaW5hdGlvbiI6ICJwaXNzaW5nIiwgInVyaW5lX2luX2FzcyI6ICJwaXNzaW5nIiwgInVyaW5lX2luX21vdXRoIjogInBpc3NpbmciLCAidXJp'
    'bmVfcG9vbCI6ICJwaXNzaW5nIiwgInVyaW5lX3N0cmVhbSI6ICJwaXNzaW5nIiwgImRpZ2ltb24iOiAicG9rZW1vbiIsICJlc3Blb24iOiAicG9rZW1vbiIsICJmbGFyZW9uIj'
    'ogInBva2Vtb24iLCAiZ2FyZGV2b2lyIjogInBva2Vtb24iLCAiZ2xhY2VvbiI6ICJwb2tlbW9uIiwgImpvbHRlb24iOiAicG9rZW1vbiIsICJsb3B1bm55IjogInBva2Vtb24i'
    'LCAicG9rZV9iYWxsIjogInBva2Vtb24iLCAicG9rZWJhbGwiOiAicG9rZW1vbiIsICJwb2tlbW9uX2J3IjogInBva2Vtb24iLCAicG9rZW1vbl9idzIiOiAicG9rZW1vbiIsIC'
    'Jwb2tlbW9uX2RwcHQiOiAicG9rZW1vbiIsICJwb2tlbW9uX2ZvY3VzIjogInBva2Vtb24iLCAicG9rZW1vbl9nbyI6ICJwb2tlbW9uIiwgInBva2Vtb25fZ3NjIjogInBva2Vt'
    'b24iLCAicG9rZW1vbl9oZ3NzIjogInBva2Vtb24iLCAicG9rZW1vbl9tYXN0ZXJzIjogInBva2Vtb24iLCAicG9rZW1vbl9vbmx5IjogInBva2Vtb24iLCAicG9rZW1vbl9vcm'
    'FzIjogInBva2Vtb24iLCAicG9rZW1vbl9yZ2J5IjogInBva2Vtb24iLCAicG9rZW1vbl9yc2UiOiAicG9rZW1vbiIsICJwb2tlbW9uX3NtIjogInBva2Vtb24iLCAicG9rZW1v'
    'bl9zcyI6ICJwb2tlbW9uIiwgInBva2Vtb25fc3YiOiAicG9rZW1vbiIsICJwb2tlbW9uX3h5IjogInBva2Vtb24iLCAicG9rZW1vcnBoIjogInBva2Vtb24iLCAicG9rZXBoaW'
    'xpYSI6ICJwb2tlbW9uIiwgInBva8OpbW9uIjogInBva2Vtb24iLCAicG9rw6lwaGlsaWEiOiAicG9rZW1vbiIsICJyZW5hbW9uIjogInBva2Vtb24iLCAic25lYXNsZXIiOiAi'
    'cG9rZW1vbiIsICJzeWx2ZW9uIjogInBva2Vtb24iLCAidW1icmVvbiI6ICJwb2tlbW9uIiwgInZhcG9yZW9uIjogInBva2Vtb24iLCAicG9ueWdpcmwiOiAicG9ueV9naXJsIi'
    'wgInBvbnlfcGxheSI6ICJwb255cGxheSIsICJwcmVnbmFuY3kiOiAicHJlZ25hbnQiLCAiYnVubnkiOiAicmFiYml0IiwgImxlcG9yaWQiOiAicmFiYml0IiwgInJhYmJpdF9n'
    'aXJsIjogInJhYmJpdF9naXJsIiwgInJhYmJpdGdpcmwiOiAicmFiYml0X2dpcmwiLCAicmF0Z2lybCI6ICJyYXRfZ2lybCIsICJyb2JvdGdpcmwiOiAicm9ib3RfZ2lybCIsIC'
    'JydWxlNjMiOiAicnVsZV82MyIsICJjb3Byb3BoYWdpYSI6ICJzY2F0IiwgImV4Y2Vzc2l2ZV9zY2F0IjogInNjYXQiLCAiZmVjZXMiOiAic2NhdCIsICJwb29wIjogInNjYXQi'
    'LCAicG9vcGluZyI6ICJzY2F0IiwgInNjYXRfZWF0aW5nIjogInNjYXQiLCAic2NhdF9waWxlIjogInNjYXQiLCAic2hpdCI6ICJzY2F0IiwgInNoaXR0aW5nIjogInNjYXQiLC'
    'Aic2hhZG93X2VsZiI6ICJzaGFkb3dfZWxmIiwgInNoYXJrX2dpcmwiOiAic2hhcmtfZ2lybCIsICJzaGFya2dpcmwiOiAic2hhcmtfZ2lybCIsICJlbnNsYXZlZCI6ICJzbGF2'
    'ZSIsICJlbnNsYXZlZF9yb3lhbCI6ICJzbGF2ZSIsICJzbGF2ZV9ib3kiOiAic2xhdmUiLCAic2xhdmVib3kiOiAic2xhdmUiLCAic2xhdmVnaXJsIjogInNsYXZlIiwgInNsYX'
    'ZlcyI6ICJzbGF2ZSIsICJ0YW1lZCI6ICJzbGF2ZSIsICJnb28iOiAic2xpbWUiLCAiZ29vX2JveSI6ICJzbGltZSIsICJnb29fY3JlYXR1cmUiOiAic2xpbWUiLCAiZ29vX2hh'
    'aXIiOiAic2xpbWUiLCAiZ29vX2h1bWFub2lkIjogInNsaW1lIiwgImdvb19tb25zdGVyIjogInNsaW1lIiwgImdvb190ZW50YWNsZSI6ICJzbGltZSIsICJnb29fdGVudGFjbG'
    'VzIjogInNsaW1lIiwgImdvb190cmFuc2Zvcm1hdGlvbiI6ICJzbGltZSIsICJnb29leSI6ICJzbGltZSIsICJzbGltZV9ib3kiOiAic2xpbWUiLCAic2xpbWVfaGFpciI6ICJz'
    'bGltZSIsICJzbGltZV9tb25zdGVyIjogInNsaW1lIiwgInNsaW1lYm95IjogInNsaW1lIiwgInNsaW15IjogInNsaW1lIiwgImhlYWxfc2x1dCI6ICJzbHV0IiwgImhlYWxzbH'
    'V0IjogInNsdXQiLCAic2x1dF9iZWx0IjogInNsdXQiLCAic2x1dF9jYXAiOiAic2x1dCIsICJzbHV0X2NvbGxhciI6ICJzbHV0IiwgInNsdXRfa2l0dHkiOiAic2x1dCIsICJz'
    'bHV0X293bmVyIjogInNsdXQiLCAic2x1dF9wcmludCI6ICJzbHV0IiwgIndlbmNoIjogInNsdXQiLCAid2hvcmUiOiAic2x1dCIsICJjb2JyYSI6ICJzbmFrZSIsICJweXRob2'
    '4iOiAic25ha2UiLCAic3F1aXJ0aW5nIjogInNxdWlydCIsICJvZG9yIjogInN0aW5rIiwgInNtZWxseSI6ICJzdGluayIsICJzbWVsbHlfYXNzIjogInN0aW5rIiwgInNtZWxs'
    'eV9jb2NrIjogInN0aW5rIiwgInNtZWxseV9mZWV0IjogInN0aW5rIiwgInN0aW5rX2xpbmVzIjogInN0aW5rIiwgInN0aW5reSI6ICJzdGluayIsICJzdGlua3lfZmVldCI6IC'
    'JzdGluayIsICJoZXRlcm8iOiAic3RyYWlnaHQiLCAiaGV0ZXJvX3NleCI6ICJzdHJhaWdodCIsICJoZXRlcm9zZXh1YWwiOiAic3RyYWlnaHQiLCAicmVjZWl2aW5nX3BvdiI6'
    'ICJ0YWtlcl9wb3YiLCAic3VibWlzc2l2ZV9wb3YiOiAidGFrZXJfcG92IiwgImZveF90YXVyIjogInRhdXIiLCAiZm94dGF1ciI6ICJ0YXVyIiwgIndvbGZfdGF1ciI6ICJ0YX'
    'VyIiwgIndvbGZ0YXVyIjogInRhdXIiLCAidGVra2VuXzVfZGFya19yZXN1cnJlY3Rpb24iOiAidGVra24iLCAidGVra2VuX3RhZ190b3VybmFtZW50IjogInRla2tuIiwgInRl'
    'a2tlbl90YWdfdG91cm5hbWVudF8yIjogInRla2tuIiwgInRlbnRhY2xlX19pbl9tb3V0aCI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9mZWxsYXRpbyI6ICJ0ZW50YWNsZSIsIC'
    'J0ZW50YWNsZV9ncmFiIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX2hhaXIiOiAidGVudGFjbGUiLCAidGVudGFjbGVfaW5fYW51cyI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9p'
    'bl9hc3MiOiAidGVudGFjbGUiLCAidGVudGFjbGVfaW5fcHVzc3kiOiAidGVudGFjbGUiLCAidGVudGFjbGVfbW9uc3RlciI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9vbl9mZW'
    '1hbGUiOiAidGVudGFjbGUiLCAidGVudGFjbGVfb25fZnV0YSI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9vbl9tYWxlIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX3BlbmV0cmF0'
    'aW9uIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX3BpdCI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZV9yYXBlIjogInRlbnRhY2xlIiwgInRlbnRhY2xlX3NleCI6ICJ0ZW50YWNsZS'
    'IsICJ0ZW50YWNsZWpvYiI6ICJ0ZW50YWNsZSIsICJ0ZW50YWNsZXNfb25fZmVtYWxlIjogInRlbnRhY2xlIiwgInRlbnRhY2xlc19vbl9mdXRhIjogInRlbnRhY2xlIiwgInRl'
    'bnRhY2xlc19vbl9tYWxlIjogInRlbnRhY2xlIiwgInRpZWRfYXJtcyI6ICJ0aWVkX3VwIiwgInRpZWRfYmFsbHMiOiAidGllZF91cCIsICJ0aWVkX2Rvd24iOiAidGllZF91cC'
    'IsICJ0aWVkX2ZlZXQiOiAidGllZF91cCIsICJ0aWVkX2hhaXIiOiAidGllZF91cCIsICJ0aWVkX2hhbmRzIjogInRpZWRfdXAiLCAidGllZF9sZWdzIjogInRpZWRfdXAiLCAi'
    'dGllZF9wZW5pcyI6ICJ0aWVkX3VwIiwgInRpZWRfdG9lcyI6ICJ0aWVkX3VwIiwgInRvcnR1cmVfY2hhbWJlciI6ICJ0b3J0dXJlIiwgInRvcnR1cmVfZGV2aWNlIjogInRvcn'
    'R1cmUiLCAidG9ydHVyZV9yYWNrIjogInRvcnR1cmUiLCAidG9ydHVyZWQiOiAidG9ydHVyZSIsICJ0b3J0dXJlciI6ICJ0b3J0dXJlIiwgInRvcnR1cmVzIjogInRvcnR1cmUi'
    'LCAidG9ydHVyaW5nIjogInRvcnR1cmUiLCAiYW1iaWd1b3VzX2dlbmRlciI6ICJ0cmFucyIsICJjcm9zc2dlbmRlciI6ICJ0cmFucyIsICJnZW5kZXJfYmVuZGVyIjogInRyYW'
    '5zIiwgImdlbmRlcl90cmFuc29mcm1hdGlvbiI6ICJ0cmFucyIsICJnZW5kZXJiZW5kIjogInRyYW5zIiwgImdlbmRlcmJlbmRlciI6ICJ0cmFucyIsICJnZW5kZXJiZW50Ijog'
    'InRyYW5zIiwgImdlbmRlcnN3YXAiOiAidHJhbnMiLCAibWFsZV9oZXJtIjogInRyYW5zIiwgIm1hbGVoZXJtIjogInRyYW5zIiwgIm1hbl9ib29icyI6ICJ0cmFucyIsICJtYW'
    '5fdGl0cyI6ICJ0cmFucyIsICJtYW5ib29icyI6ICJ0cmFucyIsICJtdGFfY3Jvc3NnZW5kZXIiOiAidHJhbnMiLCAibXRhX3RyYW5zZm9ybWF0aW9uIjogInRyYW5zIiwgIm10'
    'ZiI6ICJ0cmFucyIsICJtdGZfY3Jvc3NnZW5kZXIiOiAidHJhbnMiLCAibXRmX3RyYW5zZm9ybWF0aW9uIjogInRyYW5zIiwgIm10Z19jcm9zc2dlbmRlciI6ICJ0cmFucyIsIC'
    'JtdGdfdHJhbnNmb3JtYXRpb24iOiAidHJhbnMiLCAibXRoX2Nyb3NzZ2VuZGVyIjogInRyYW5zIiwgIm10aF90cmFuc2Zvcm1hdGlvbiI6ICJ0cmFucyIsICJtdGlfY3Jvc3Nn'
    'ZW5kZXIiOiAidHJhbnMiLCAibXRpX3RyYW5zZm9ybWF0aW9uIjogInRyYW5zIiwgInR1YmVfZmVlZGluZyI6ICJ0dWJlIiwgInR1YmVfZ2FnIjogInR1YmUiLCAidHViZV9pbl'
    '9hc3MiOiAidHViZSIsICJ0dWJlX2luX21vdXRoIjogInR1YmUiLCAidHViZXMiOiAidHViZSIsICJ1Z2x5X2Jhc3RhcmQiOiAidWdseSIsICJ1Z2x5X2ZlbWFsZSI6ICJ1Z2x5'
    'IiwgInVnbHlfZnV0YSI6ICJ1Z2x5IiwgInVnbHlfbWFsZSI6ICJ1Z2x5IiwgInVnbHlfbWFuIjogInVnbHkiLCAidXJldGhyYWwiOiAidXJldGhyYSIsICJ1cmV0aHJhbF9iZW'
    'FkcyI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX2J1bGdlIjogInVyZXRocmEiLCAidXJldGhyYWxfZmluZ2VyaW5nIjogInVyZXRocmEiLCAidXJldGhyYWxfZmlzdGluIjogInVy'
    'ZXRocmEiLCAidXJldGhyYWxfaW5zZXJ0aW9uIjogInVyZXRocmEiLCAidXJldGhyYWxfbGlja2luZyI6ICJ1cmV0aHJhIiwgInVyZXRocmFsX292aXBvc2l0aW9uIjogInVyZX'
    'RocmEiLCAidXJldGhyYWxfcGVuZXRyYXRpb24iOiAidXJldGhyYSIsICJ1cmV0aHJhbF9wbHVnIjogInVyZXRocmEiLCAidXJldGhyYWxfc2V4IjogInVyZXRocmEiLCAidmlv'
    'bGF0ZWQiOiAidmlvbGVuY2UiLCAidmlvbGF0aW9uIjogInZpb2xlbmNlIiwgInZpb2xlbnQiOiAidmlvbGVuY2UiLCAiYW5hbF92b3JlIjogInZvcmUiLCAiY29ja192b3JlIj'
    'ogInZvcmUiLCAiZGV2b3VyZWQiOiAidm9yZSIsICJkZXZvdXJpbmciOiAidm9yZSIsICJkaWdlc3Rpb24iOiAidm9yZSIsICJtYXNzX3ZvcmUiOiAidm9yZSIsICJvcmFsX3Zv'
    'cmUiOiAidm9yZSIsICJwbGFudF92b3JlIjogInZvcmUiLCAicG9zdF92b3JlIjogInZvcmUiLCAic29mdF92b3JlIjogInZvcmUiLCAidm9yZV9zZXgiOiAidm9yZSIsICJ3YX'
    'JoYW1tZXJfNDAwMDAiOiAid2FyaGFtbWVyIiwgIndhcmhhbW1lcl80MGsiOiAid2FyaGFtbWVyIiwgIndvbGZnaXJsIjogIndvbGZfZ2lybCIsICJ3b3ciOiAid29ybGRfb2Zf'
    'd2FyY3JhZnQiLCAieHJheV92aWV3IjogInhyYXkiLCAiemVicm9pZCI6ICJ6ZWJyYSIsICJ6b21iaWVfZnV0YSI6ICJ6b21iaWUiLCAiem9tYmllcyI6ICJ6b21iaWUifQ=='
)
TAG_ALIASES = loads(b64decode(TAG_ALIASES_STR))  # type: Dict[str, str]


def append_filtered_tags(base_string: str, tags_str: str, re_tags_to_process: Pattern, re_tags_to_exclude: Pattern) -> str:
    if len(tags_str) == 0:
        return base_string

    tags_list = tags_str.split(' ')
    tags_toadd_list = []  # type: List[str]

    for tag in tags_list:
        tag = tag.replace('-', '').replace('\'', '')
        if TAG_ALIASES.get(tag) is None and re_tags_to_process.fullmatch(tag) is None:
            continue

        # digital_media_(artwork)
        aser_match = re_meta_group.fullmatch(tag)
        aser_valid = False
        if aser_match:
            major_skip_match1 = re_tags_exclude_major1.fullmatch(aser_match.group(1))
            major_skip_match2 = re_tags_exclude_major2.fullmatch(aser_match.group(2))
            if major_skip_match1 or major_skip_match2:
                continue
            stag = trim_undersores(aser_match.group(1))
            if len(stag) >= 14:
                continue
            tag = stag
            aser_valid = True

        tag = trim_undersores(tag)
        alias = TAG_ALIASES.get(tag)
        if alias:
            tag = alias

        if re_tags_to_exclude.fullmatch(tag):
            continue

        do_add = True
        if len(tags_toadd_list) > 0:
            nutag = re_not_a_letter.sub('', re_numbered_or_counted_tag.sub(r'\1', tag))
            # try and see
            # 1) if this tag can be consumed by existing tags
            # 2) if this tag can consume existing tags
            for i in reversed(range(len(tags_toadd_list))):
                t = re_numbered_or_counted_tag.sub(r'\1', tags_toadd_list[i].lower())
                nut = re_not_a_letter.sub('', t)
                if len(nut) >= len(nutag) and (nutag in nut):
                    do_add = False
                    break
            if do_add:
                for i in reversed(range(len(tags_toadd_list))):
                    t = re_numbered_or_counted_tag.sub(r'\1', tags_toadd_list[i].lower())
                    nut = re_not_a_letter.sub('', t)
                    if len(nutag) >= len(nut) and (nut in nutag):
                        if aser_valid is False and tags_toadd_list[i][0].isupper():
                            aser_valid = True
                        del tags_toadd_list[i]
        if do_add:
            if aser_valid:
                for i, c in enumerate(tag):  # type: int, str
                    if (i == 0 or tag[i - 1] == UNDERSCORE) and c.isalpha():
                        tag = f'{tag[:i]}{c.upper()}{tag[i + 1:]}'
            tags_toadd_list.append(tag)

    return f'{base_string}{UNDERSCORE}{re_replace_symbols.sub(UNDERSCORE, UNDERSCORE.join(sorted(tags_toadd_list)))}'

#
#
#########################################
