# coding=UTF-8
"""
Author: trickerer (https://github.com/trickerer, https://github.com/trickerer01)
"""
#########################################
#
#

# native
from enum import IntEnum, unique, auto
from typing import Optional, Set

# Buttons
STATE_READONLY = 'readonly'
STATE_DISABLED = 'disabled'
STATE_NORMAL = 'normal'
BUT_RETURN = '<Return>'
BUT_ESCAPE = '<Escape>'
BUT_DELETE = '<Delete>'
BUT_CTRL_A = '<Control-a>'
BUT_CTRL_S = '<Control-s>'
BUT_CTRL_O = '<Control-o>'
BUT_CTRL_L = '<Control-l>'
BUT_CTRL_SHIFT_D = '<Control-Shift-D>'
BUT_CTRL_SHIFT_C = '<Control-Shift-C>'
# BUT_MOUSE_L = '<Button-1>'
# BUT_MOUSE_MID = '<Button-2>'
# BUT_MOUSE_R = '<Button-3>'
BUT_F1 = '<F1>'
BUT_F2 = '<F2>'
BUT_F3 = '<F3>'
BUT_F4 = '<F4>'
BUT_F5 = '<F5>'
BUT_F6 = '<F6>'
BUT_ALT_F4 = '<Alt-F4>'
# Colors
#  Color enum
COLOR_WHITE = 'white'
# COLOR_BLACK = 'black'
# COLOR_GRAY = 'gray'
COLOR_LIGHTGRAY = 'lightgray'
COLOR_DARKGRAY = 'darkgray'
COLOR_BROWN1 = 'brown1'  # red-ish (for warnings)
COLOR_PALEGREEN = 'palegreen'
# COLOR_STEELBLUE = 'lightsteelblue4'
# COLOR_TOOLTIP_DEFAULT = '#ffffdd'  # whiteish
#  Color defines
# BUT_TOOLTIP_BG_DEFAULT = COLOR_WHITE
# Abbrev
STICKY_ALLDIRECTIONS = 'wens'
STICKY_HORIZONTAL = 'we'
# STICKY_VERTICAL = 'ns'
# STICKY_HORIZONTAL_N = 'wen'
# STICKY_HORIZONTAL_S = 'wes'
STICKY_VERTICAL_W = 'wns'
# STICKY_VERTICAL_E = 'ens'
# Combobox
OPTION_VALUES_VIDEOS = ('Don\'t download', 'Prefer MP4', 'Prefer Webm')
OPTION_VALUES_IMAGES = ('Don\'t download', 'Prefer low res', 'Prefer high res')
OPTION_VALUES_PARCHI = ('Don\'t download', 'Download everything')
OPTION_VALUES_THREADING = ('1 Thread', '2 Threads', '3 Threads', '4 Threads', '5 Threads', '6 Threads', '7 Threads', '8 Threads')
OPTION_VALUES_PROXYTYPE = ('http', 'socks5')
OPTION_CMD_VIDEOS = ('-skip_vid', '', '-webm')
OPTION_CMD_IMAGES = ('-skip_img', '-lowres', '')
OPTION_CMD_PARCHI = ('', '-include_parchi')
OPTION_CMD_THREADING_CMD = '-threads'
OPTION_CMD_THREADING = ('1', '2', '3', '4', '5', '6', '7', '8')
OPTION_CMD_COOKIES = '-cookies'
OPTION_CMD_HEADERS = '-headers'
OPTION_CMD_PROXY = '-proxy'
OPTION_CMD_IGNORE_PROXY = ('', '-noproxy')
OPTION_CMD_PROXY_NO_DOWNLOAD = ('', '-proxynodown')
OPTION_CMD_TIMEOUT = '-timeout'
OPTION_CMD_RETRIES = '-retries'
OPTION_CMD_FNAMEPREFIX = ('', '-prefix')
OPTION_CMD_DOWNMODE_CMD = '-dmode'
OPTION_CMD_DOWNLIMIT_CMD = '-dlimit'
OPTION_CMD_DOWNMODE = ('', '1', '2')
OPTION_CMD_SAVE_TAGS = ('', '-dump_tags')
OPTION_CMD_SAVE_SOURCES = ('', '-dump_sources')
OPTION_CMD_SAVE_COMMENTS = ('', '-dump_comments')
OPTION_CMD_APPEND_SOURCE_AND_TAGS = ('', '-append_info')
OPTION_CMD_WARN_NONEMPTY_DEST = ('', '-warn_nonempty')
OPTION_CMD_DATEAFTER = '-mindate'
OPTION_CMD_DATEBEFORE = '-maxdate'
OPTION_CMD_PATH = '-path'
OPTION_CMD_MODULE = '-module'
# Sizes
# BORDER_SIZE_DEFAULT = 4
PADDING_DEFAULT = 2
PADDING_ROOTFRAME_I = PADDING_DEFAULT
# COLUMN_WIDTH_DEFAULT = 20
GLOBAL_COLUMNCOUNT = 100
GLOBAL_ROWCOUNT = 100
COLUMNSPAN_MAX = GLOBAL_COLUMNCOUNT
ROWSPAN_MAX = GLOBAL_ROWCOUNT
WINDOW_MINSIZE = [614, 273]
# Timers
TOOLTIP_DELAY_DEFAULT = 500
GUI2_UPDATE_DELAY_DEFAULT = 300
THREAD_CHECK_PERIOD_DEFAULT = 300
# Fonts
FONT_LUCIDA_MEDIUM = ('Lucida Grande', 10)
FONT_SANS_SMALL = ('Microsoft Sans Serif', 8)
FONT_SANS_MEDIUM = ('Microsoft Sans Serif', 10)
# Formats & patterns
SLASH = '/'
UNDERSCORE = '_'
NEWLINE = '\n'
NEWLINE_X2 = '\n\n'


# icons enum
@unique
class Icons(IntEnum):
    ICON_RUXX = 0
    ICON_RX = auto()
    ICON_RN = auto()
    ICON_RS = auto()
    ICON_OPEN = auto()
    ICON_SAVE = auto()
    ICON_DELETE = auto()
    ICON_ADD = auto()
    ICON_TEXT = auto()

    def __str__(self) -> str:
        return f'{self.__class__.__name__}.{self._name_} ({self.value:d})'


# existing config vars
@unique
class Options(IntEnum):
    OPT_ISLOGOPEN = 0
    OPT_VIDSETTING = auto()
    OPT_IMGSETTING = auto()
    OPT_PARCHISETTING = auto()
    OPT_THREADSETTING = auto()
    OPT_DOWNLOAD_MODE = auto()
    OPT_DOWNLOAD_LIMIT = auto()
    OPT_DATEMIN = auto()
    OPT_DATEMAX = auto()
    OPT_TAGS = auto()
    OPT_PATH = auto()
    OPT_LASTPATH = auto()  # unbound, internal
    OPT_PROGRESS = auto()
    OPT_STATUS = auto()
    OPT_FNAMEPREFIX = auto()
    OPT_ISPROXYOPEN = auto()
    OPT_PROXYSTRING = auto()
    OPT_PROXYSTRING_TEMP = auto()
    OPT_PROXYTYPE = auto()
    OPT_PROXYTYPE_TEMP = auto()
    OPT_ISTIMEOUTOPEN = auto()
    OPT_TIMEOUTSTRING = auto()
    OPT_TIMEOUTSTRING_TEMP = auto()
    OPT_ISRETRIESOPEN = auto()
    OPT_RETRIESSTRING = auto()
    OPT_RETRIESSTRING_TEMP = auto()
    OPT_MODULE = auto()
    OPT_IGNORE_PROXY = auto()
    OPT_PROXY_NO_DOWNLOAD = auto()
    OPT_ISHCOOKIESOPEN = auto()
    OPT_COOKIE_ADD_STR = auto()
    OPT_HEADER_ADD_STR = auto()
    OPT_SAVE_TAGS = auto()
    OPT_SAVE_SOURCES = auto()
    OPT_SAVE_COMMENTS = auto()
    OPT_ISCONSOLELOGOPEN = auto()
    OPT_APPEND_SOURCE_AND_TAGS = auto()
    OPT_WARN_NONEMPTY_DEST = auto()
    OPT_ISABOUTOPEN = auto()
    OPT_ISSAVESETTINGSOPEN = auto()
    OPT_ISLOADSETTINGSOPEN = auto()
    OPT_WINDOW_POSITION = auto()
    OPT_ACTION_DOWNLOAD = auto()  # unbound, internal
    OPT_ACTION_CHECKTAGS = auto()  # unbound, internal
    OPT_ACTION_OPEN_DWN_FOLDER = auto()  # unbound, internal

    def __str__(self) -> str:
        return f'{self.__class__.__name__}.{self._name_} ({self.value:d})'


# array
CVARS = {
    Options.OPT_ISLOGOPEN: 'isLogOpen',
    Options.OPT_VIDSETTING: 'vidsetting',
    Options.OPT_IMGSETTING: 'imgsetting',
    Options.OPT_PARCHISETTING: 'parchisetting',
    Options.OPT_THREADSETTING: 'threadsetting',
    Options.OPT_DOWNLOAD_MODE: 'downloadmode',
    Options.OPT_DOWNLOAD_LIMIT: 'downloadlimit',
    Options.OPT_DATEMIN: 'dateafter',
    Options.OPT_DATEMAX: 'datebefore',
    Options.OPT_TAGS: 'tags',
    Options.OPT_PATH: 'path',
    Options.OPT_LASTPATH: 'curpath',
    Options.OPT_PROGRESS: 'progress',
    Options.OPT_STATUS: 'status',
    Options.OPT_FNAMEPREFIX: 'fnameprefix',
    Options.OPT_ISPROXYOPEN: 'isProxyOpen',
    Options.OPT_PROXYSTRING: 'proxyString',
    Options.OPT_PROXYSTRING_TEMP: 'proxyStringTemp',
    Options.OPT_PROXYTYPE: 'proxyType',
    Options.OPT_PROXYTYPE_TEMP: 'proxyTypeTemp',
    Options.OPT_ISTIMEOUTOPEN: 'isTimeoutOpen',
    Options.OPT_TIMEOUTSTRING: 'timeoutString',
    Options.OPT_TIMEOUTSTRING_TEMP: 'timeoutStringTemp',
    Options.OPT_ISRETRIESOPEN: 'isRetriesOpen',
    Options.OPT_RETRIESSTRING: 'retriesString',
    Options.OPT_RETRIESSTRING_TEMP: 'retriesStringTemp',
    Options.OPT_MODULE: 'module',
    Options.OPT_IGNORE_PROXY: 'ingoreProxy',
    Options.OPT_PROXY_NO_DOWNLOAD: 'proxyDownload',
    Options.OPT_ISHCOOKIESOPEN: 'isCookiesOpen',
    Options.OPT_COOKIE_ADD_STR: 'cookieAddStr',
    Options.OPT_HEADER_ADD_STR: 'headerAddStr',
    Options.OPT_SAVE_TAGS: 'saveTags',
    Options.OPT_SAVE_SOURCES: 'saveSources',
    Options.OPT_SAVE_COMMENTS: 'saveComments',
    Options.OPT_ISCONSOLELOGOPEN: 'isConsoleOpen',
    Options.OPT_APPEND_SOURCE_AND_TAGS: 'appendSourceAndTags',
    Options.OPT_ISABOUTOPEN: 'isAboutOpen',
    Options.OPT_WARN_NONEMPTY_DEST: 'warnNonEmptyFolder',
    Options.OPT_WINDOW_POSITION: 'windowPosition',
}
# end config vars


# global static objects for manipulation
# root
@unique
class Globals(IntEnum):
    GOBJECT_COMBOBOX_VIDEOS = 0
    GOBJECT_COMBOBOX_IMAGES = auto()
    GOBJECT_COMBOBOX_PARCHI = auto()
    GOBJECT_COMBOBOX_THREADING = auto()
    GOBJECT_FIELD_DATEMIN = auto()
    GOBJECT_FIELD_DATEMAX = auto()
    GOBJECT_FIELD_TAGS = auto()
    GOBJECT_BUTTON_CLEARTAGS = auto()
    GOBJECT_BUTTON_CHECKTAGS = auto()
    GOBJECT_FIELD_PATH = auto()
    GOBJECT_BUTTON_OPENFOLDER = auto()
    GOBJECT_BUTTON_DOWNLOAD = auto()
    GOBJECT_MODULE_ICON = auto()
    MAX_GOBJECTS = auto()

    def __str__(self) -> str:
        return f'{self.__class__.__name__}.{self._name_} ({self.value:d})'


gobjects = {
    Globals.GOBJECT_COMBOBOX_VIDEOS: None,
    Globals.GOBJECT_COMBOBOX_IMAGES: None,
    Globals.GOBJECT_COMBOBOX_PARCHI: None,
    Globals.GOBJECT_COMBOBOX_THREADING: None,
    Globals.GOBJECT_FIELD_DATEMIN: None,
    Globals.GOBJECT_FIELD_DATEMAX: None,
    Globals.GOBJECT_FIELD_TAGS: None,
    Globals.GOBJECT_BUTTON_CLEARTAGS: None,
    Globals.GOBJECT_BUTTON_CHECKTAGS: None,
    Globals.GOBJECT_FIELD_PATH: None,
    Globals.GOBJECT_BUTTON_OPENFOLDER: None,
    Globals.GOBJECT_BUTTON_DOWNLOAD: None,
    Globals.GOBJECT_MODULE_ICON: None,
}

gobject_orig_states = {
    Globals.GOBJECT_COMBOBOX_VIDEOS: STATE_READONLY,
    Globals.GOBJECT_COMBOBOX_IMAGES: STATE_READONLY,
    Globals.GOBJECT_COMBOBOX_PARCHI: STATE_READONLY,
    Globals.GOBJECT_COMBOBOX_THREADING: STATE_READONLY,
    Globals.GOBJECT_FIELD_DATEMIN: STATE_NORMAL,
    Globals.GOBJECT_FIELD_DATEMAX: STATE_NORMAL,
    Globals.GOBJECT_FIELD_TAGS: STATE_NORMAL,
    Globals.GOBJECT_BUTTON_CLEARTAGS: STATE_NORMAL,
    Globals.GOBJECT_BUTTON_CHECKTAGS: STATE_NORMAL,
    Globals.GOBJECT_FIELD_PATH: STATE_NORMAL,
    Globals.GOBJECT_BUTTON_OPENFOLDER: STATE_NORMAL,
    Globals.GOBJECT_BUTTON_DOWNLOAD: STATE_NORMAL,
    Globals.GOBJECT_MODULE_ICON: STATE_NORMAL,
}


# buttons to unfocus
BUTTONS_TO_UNFOCUS = (
    Globals.GOBJECT_BUTTON_DOWNLOAD,
)
# end buttons to unfocus


# menus
@unique
class Menus(IntEnum):
    MENU_FILE = 0
    MENU_EDIT = auto()
    MENU_CONNECTION = auto()
    MENU_TOOLS = auto()
    MENU_MODULE = auto()
    MENU_ACTIONS = auto()
    MENU_DEBUG = auto()
    MAX_MENUS = auto()

    def __str__(self) -> str:
        return f'{self.__class__.__name__}.{self._name_} ({self.value:d})'


class SubMenus(IntEnum):
    SAVE, LOAD, RESET, OPENFOLDER = 0, 1, 3, 5
    PREFIX, STAGS, SSOURCE, SCOMMENTS, EXTEND, WNONEMPTY = 0, 1, 2, 3, 4, 5
    RX, RN, RS = 0, 1, 2
    HEADERS, PROXY, TIMEOUT, RETRIES, DWPROXY, IGNOREPROXY = 0, 1, 2, 3, 4, 5
    DOWNLOAD, CHECKTAGS = 0, 2
    IDLIST, UNTAG, RETAG, SORT = 0, 2, 3, 5
    DFULL, DSKIP, DTOUCH, DLIMSET, DLIMRESET = 0, 1, 2, 3, 4

    def __str__(self) -> str:
        return f'{self.__class__.__name__}.{self._name_} ({self.value:d})'


class RuxxMenu:
    def __init__(self, indecies: Set[SubMenus]) -> None:
        self.menu = None  # type: Optional["Menu"]  # noqa F821
        self.statefuls = indecies

    def __bool__(self) -> bool:
        return not not self.menu


menu_items = {
    Menus.MENU_FILE: RuxxMenu({SubMenus.SAVE, SubMenus.LOAD, SubMenus.RESET}),
    Menus.MENU_EDIT: RuxxMenu({SubMenus.PREFIX, SubMenus.STAGS, SubMenus.SSOURCE, SubMenus.SCOMMENTS, SubMenus.EXTEND, SubMenus.WNONEMPTY}),
    Menus.MENU_MODULE: RuxxMenu({SubMenus.RX, SubMenus.RN, SubMenus.RS}),
    Menus.MENU_CONNECTION: RuxxMenu({SubMenus.HEADERS, SubMenus.PROXY, SubMenus.TIMEOUT, SubMenus.RETRIES, SubMenus.DWPROXY,
                                     SubMenus.IGNOREPROXY}),
    Menus.MENU_ACTIONS: RuxxMenu({SubMenus.DOWNLOAD, SubMenus.CHECKTAGS}),
    Menus.MENU_TOOLS: RuxxMenu({SubMenus.IDLIST, SubMenus.UNTAG, SubMenus.RETAG, SubMenus.SORT}),
    Menus.MENU_DEBUG: RuxxMenu({SubMenus.DFULL, SubMenus.DSKIP, SubMenus.DTOUCH, SubMenus.DLIMSET, SubMenus.DLIMRESET}),
}

menu_item_orig_states = {
    Menus.MENU_FILE: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
    Menus.MENU_EDIT: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
    Menus.MENU_MODULE: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
    Menus.MENU_CONNECTION: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
    Menus.MENU_ACTIONS: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
    Menus.MENU_TOOLS: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
    Menus.MENU_DEBUG: (STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL, STATE_NORMAL),
}
# end global static
# hotkeys
hotkeys = {
    Options.OPT_ISABOUTOPEN: BUT_F1,
    Options.OPT_ISLOGOPEN: BUT_F2,
    Options.OPT_ISHCOOKIESOPEN: BUT_F3,
    Options.OPT_ISPROXYOPEN: BUT_F4,
    Options.OPT_ISTIMEOUTOPEN: BUT_F5,
    Options.OPT_ISRETRIESOPEN: BUT_F6,
    Options.OPT_ISSAVESETTINGSOPEN: BUT_CTRL_S,
    Options.OPT_ISLOADSETTINGSOPEN: BUT_CTRL_O,
    Options.OPT_ACTION_DOWNLOAD: BUT_CTRL_SHIFT_D,
    Options.OPT_ACTION_CHECKTAGS: BUT_CTRL_SHIFT_C,
    Options.OPT_ACTION_OPEN_DWN_FOLDER: BUT_CTRL_L,
}
# end hotkeys
# tooltips
TOOLTIP_VIDEOS = (' Selected file type will be preferred during search.',
                  ' If file is unavailable, alternative type will be',
                  ' attempted automatically.')
TOOLTIP_IMAGES = (' Selected file type will be preferred during search.',
                  ' If file is unavailable, alternative type will be',
                  ' attempted automatically.',
                  ' Warning: low res variant of a gif may be unanimated!')
TOOLTIP_PARCHI = (' Download parent posts / child posts even if they don\'t match provided tags.',)
TOOLTIP_THREADING = (' Number of threads affects scan and download speed.',)
TOOLTIP_DATE = (' Date must be in \'dd-mm-yyyy\' format.',)
TOOLTIP_TAGS_CHECK = (' Validate tags (live).',)
TOOLTIP_HCOOKIE_DELETE = (' Delete selected (Del works too)',)
TOOLTIP_HCOOKIE_ADD_ENTRY = (' Must be in on of the valid formats:',
                             '  1) [name] [value]',
                             '  2) [name]:[value]',
                             '  3) [name],[value]')
TOOLTIP_INVALID_SYNTAX = ('Invalid syntax.',)
# end tooltips
# images cache
#  gif
IMG_OPEN_DATA = (
    'R0lGODlhEAAQAIMAMQAAAIAyGTJnMoBnMhkyZ4AyZzJnZ8DAwICAgP9jMWPOY//OADFjzv9jzmPR0f///ywAAAAAEAAQAAMEOvDISaulIN8KZu8bByLklnXI8ixnWyFrrKrglM'
    'pyLcFz62c31mBIJKJWgKJyJFQabUnnUPfzha7YSwQAOw=='
)
#  gif
IMG_SAVE_DATA = (
    'R0lGODlhEAAQAIMAMQAAAIAyGTJnMoBnMhkyZ4AyZzJnZ8DAwICAgP9jMWPOY//OADFjzv9jzmPR0f///ywAAAAAEAAQAAMEQvDISatEOGt9FXhgCH5A94khoJpo6rHtA7wH4s'
    'UybZ/tXNYKj2qoCv5swaTS2BEShzrjcxR1DqlHKRE7eXpXlvAkAgA7'
)
#  gif
IMG_DELETE_DATA = 'R0lGODlhDwAPAIIAMcDAwJ0AAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAAALAAAAAAPAA8AAgMUCLrc/jDKSWm4OOvNu/9aJY5kmQAAOw=='
#  gif
IMG_ADD_DATA = 'R0lGODlhDwAPAIIAMcDAwAC7AAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAAALAAAAAAPAA8AAgMeCLrRsRC6F+Os1mGpt7rcJI5kaZ5mBXrr1mKv2i0JADs='
#  gif
IMG_TEXT_DATA = (
    'R0lGODlhEAAQAIIAMQcHB42MjczLzPf390RCRLGxsXt9ezAwMCwAAAAAEAAQAAIDUSi23BxFjUnrEEAUY/vI0rAFpFFMmBBelFABxTbFZBG4F8hdav+qu54qgsrIRDYa7hPZeY'
    'rA5+/ocRV0TwGJcGhKVQCkYWkxhCMYgHq9PmgiCQA7'
)
#  gif
IMG_PROC_RX_DATA = (
    'R0lGODlhEAAQAIcAMf///zNmMwAAAAAzAJn/mQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAEAAQAAcIcwABBBhIsGBBgQEA'
    'KBQgwCAAhgMfMpRIcGHDAAwnQkwogCLGixQlekxokWNDiRczilTI8uFAlRlhQnRpkmDHjBhZ4qy4MeZGmxdf4hxAdADGAESREhCwdMDSpk8bDmAqgChVq02VXo3qlCqAqWDBVh'
    'ULICAAOw=='
)
#  gif
IMG_PROC_RN_DATA = (
    'R0lGODlhEAAQAIcAMfX16+Lm0M/dv8vauczYuMvXt8fUs8PMrLvGo7LAnLC+may4lJ+phpylhs/LtPvz5uDv1rXWoou3c5G0c5+3e5iydYmpaoKdXnqTUm6LR2+IQ3CCPVhqJ1'
    'BeHJGbW9zgtbfpyInWnIm9cqa+fq+/h6y7gqy7hKq8gq+5gK6yeauubqywbbCzbbetWZi3UqnRhYXNrFe0hbDPoL3UrJm+krHGneblzO3v2+vt2d/bwLPAkYy0eaTAidTFjK/H'
    'Z6XPeJDeyWzQr7ncuLzl06XSsL/Qo+rr1/z8+vv8+8zXxKy2jY6kcGaUX7axgLnIcarOeLX48qT25rLfv6nq4LblytHdqejsy/377//788vTt8C8jqyodlOARqmpcLjLbaXNdc'
    'L29b3x7bDgypfn36/n0rzWra7PrMDSucXQuaG4lbC8jaq1g1iETqipcLbLa6bMc8j39sb086vhz5Po5Lzx45fBpDeIcD+Ka0mNYzCCUYGqfbe9k1eCT6SmbrbLbKbNdMv19svz'
    '9qnj15Pq6rHp4ZLIrlKojWCngVyocVCjZZy+i7K7jk+BSqSocLfLbaTMc8Xy9cDw9qjl3ZHt74/h3Y7OuJTRtrHWuq3XrIzHj6nGjqG0f0mHTaSsc7PLaZ/Mcaj09432+aPj25'
    'b2947o4pbNu63Zydns3+Ht3ZzMrZnAiZyzcE+JT6Ctc6nOaZvQc3/h5U/a3Z3e1oHp6mDW1IbKwcLi3fT69/n9+q7Xy4TClnCvbkOFUp6zd6HUc5TSfGy+wjWoqpvXz1/Dxg2t'
    't1TFx8vn4+339e349brd02nDqC2rgzqVbKS8fZjXfIzVinzY3jvM0n/NwYTJwGbFwXfOxJ3czKfg1Kfe1JXWxHDJqF/AlXu/ipa+dXnPdo3clqHk5ULN0i+8ukfJx1LOz0LJyC'
    '/Hwi/FwDHBvTPAtzq+q0fBoVTMn1LJj0G7fX3ImNHn5IjMy1nL0FPR1VfU2VLS2UvR1EzQ0UzNzE7LyFPJxVfLwFnUvmbev27KraPQuywAAAAAEAAQAAcI/gABBBAwgEABAwcQ'
    'JFCwgEEDBw8gRJAwgUIFCxcwZNCwgUMHDx9AhBAxgkQJEydQpFCxgkULFy9gxJAxg0YNGzdw5NCxg0cPHz+ABBEyhEgRI0eQJFGyhEkTJ0+gRJEyhUoVK1ewZNGyhUsXL1/AhB'
    'EzhkwZM2fQpFGzhk0bN2/gxJEzh04dO3fw5NGzh08fP38ABRI0iFAhQ4cQJVK0iFEjR48gRZI0iVIlS5cwZdK0iVMnT59AhRI1ilQpU6dQpVK1ilUrV69gxZI1i1YtW7dw5dK1'
    'i1cvX7+ABRM2jFgxY8eQJVO2jFkzZ8+gRZM2jVo1a9ewZdO2jVs3b9/AJYUTN45cOXPn0KVTt45dO3fv4MWTN49ePXv38OXTt49fP3//BAQAOw=='
)
#  gif
IMG_PROC_RS_DATA = (
    'R0lGODlhEAAQAIcAMS9sMiFMIxxCHxIqEyxmMClgLTN1NyJOJB5GIBc2GS5qMaPQIjmpmTFyNRUwFidaKg8kESZYKS5nHExnFR9IInIyFSggDuhQIBJoQNlMHit8bRU6LBQuEC'
    'AyDiciGFGhvDdADxeMORAjGQ5AJhRvLdEeISRIaC6IeBuzSBUlDSheLDNxHho8HA0eDhklDCRUJxV8TRs4NBAjINZhYhaGVJ51F2I3MX5BPUdSSEVNEA01Fld0FuikHa1+GI+O'
    'FlRHEQ9JHhFeOhgYDVesyitkLiBbTRw4SQ8jDSk1Kjc0Dy1YhxiaYTZseAwsGDR4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAEAAQAAcIpACdCBxIsKDBggUI'
    'HDSoYsQGhQsHJqChQUDBABAgBBg4YAmDAQAGBrBRIsOPB04eAAlyIoaMCE4AIJkhxEKPBA0EkGhSZIgSB04K4LhBwUKNHCkchMDA4MMAmEE9IKjAw8eCIyhgDGBi5MVAAC0uJB'
    'EwQYIOFkREmLA4cCoCAB1WUBCoQIACggYOGAhQ9kBEgQ1cLOAQ8i8BEDs2/hVIQO/ixwEBADs='
)
#  gif
IMG_PROC_RUXX_DATA = (
    'R0lGODlhAAEAAYcAMQ8JCQuJGZQJRgdIDpmHUtTDqJFHG8qFRcVdFkdHIE8LH5ZlQcqLkFVIdggoCsqlcPzlklEoFxBoFYhIcKGlpo1oeivIMEYrcs5rGenFfWJmfuaIMR4niE'
    'dnPsloYYUtEjxLXqlLIOXKui5IGpKInmwpDmeHbi8oFHFGJ8mnkh2oJL4pULVnMgoGbuyrhuynVylnJM6JYm1IeY4nWbFqc+dpaeTj1CpYH3RngerUmC44E+iJa6mKqLh1QDAI'
    'DE84FJdVJq9ZJfa1WCmIJ9F4YNOYYpKl1kxJVbJIWzrmO8esxfz20tF2KG44Eo14hnZJRHNqom8obbmFW+nXxbGqyefHnghYES2pKpmVoY05V28JMQg5DOqaahF4GDNJPqqVcF'
    'pWeMu3qa1pTSd4J7vF6TM5Om5ZeqtaPVQ4M5BKQdLV6ReYH+uqb/O6ifjpz09YVIw6Ere2yuHa6DLWNHJlOtN5d81JWzEYFW85NpV3TS4pOt55IAgYCjNXPLNYXSG4KHZ2fUS6'
    'NKkZTS4HbHiGwlAXbjo4VnMbaFtorpEZPsmaikH1QE45Za55eLmkcIyZjEl4NayYpi8ZXMxZYJJaXfz4sbs4UzcobczG1eiXRKO32DlHn9uUSlFWK9m1dHFVMhIYfyeZJsm5y3'
    'NWTW85bW8XLmN2u6E6Mmx1TU0cHul6aaY4TpIXVuWZiXV3rd1tF6QpTC+7L1MqM24pMLWIeE5ZpTA4kE85gq56njTLNHyGf/bNuPzWirSmpIuFiVRnVqxIRDRmQigMOIp6ppaY'
    'xxd2NqicxiobeWR6bPrIfN1aYhUILZlmUk5JlxhoJolrlY4pN42Ku7R4VZRYRO+4cvv7+Wtakuq5qGpoYDMaLFJ2Vo5Yet2JiPzns8VrMfjbvfnHkbS44TzZOk34Rs06VzIogc'
    'jJ6UToPheIHRhIFRgoEVcseddpZ9iojaKm0hdYFxg5E7qWdNm4mDh3NhgYEXuRzd3K3uLl8vDq74c5Nt19LdiIPVdGJ9mma5hJaPWKKiwAAAAAAAEAAQcI/gBzzcklkKDBgwgL'
    'DlxYMKFDhgnnSJxowUKsK6GGwIAxAp46essAiATAx8EWKxICrFHx509FCy3/qFCxsubMlhXFnTs3rqfPnz93nhMnjmCso0iTHiw6sGhRhwgHQs0Vi6pBiUmSLNqadY4FmugkWL'
    'EyYMuWAQPevSs2JlSoWIHmEM2aRJxEgxYOSp2qVyHBvVL38u37t6FhoxGvHswrkKLFKxjnjenjpYy6jyNLnkWpkqXLmDJn0lyzUjROuTuBql4klKjBQEmVInRq8OnUwAmrWtWN'
    'NSvXJHNarunShSzas2nfwRgyBHLVuXWBF2XMmKFgq1EbAu4L8aDuxE0P/iP8Xvg6QQtevVb8A3nIvHl9bowoo4cePT74TQ6wQpy0Z9AzkSagfzehpxNPqo2zlVA7EWVbIFQpRd'
    '5SudjmXWJQTVihOHR1VRFNXUggVlkDwJNOOs44M8YQoVwBoV0cynXXYA59h1t329HIHWGCaThbduqtd5Fb7/VBWRkn6HHCCeroAA88avVXGkuiCajSlQK2FEteOuk0Dk9bsZZE'
    'aw5aWJWPtVWo42HXfXdmYx16KNMQYb0zQDolnvhOHzCs2OJRAtkl3Yy5VCcedhimWRhBTK2ZJm6OhkdboeitJxOR7wXzRmVHlOFpGTqMMIJyEoyBjkoCjrbGlQG02mqq/n9AuO'
    'E5Y0bH4a1lbqgoYogmapCG3Q02EYddefVHKGuM4YwEJ6ZjohcowlDMPG7B9tdEhGa3plSTGnZdm+Ap5qhitC1kaWgZudfBG+wewU8D/BxxxBt9BLPRGGN0caqrrp6Kjr7E/RsA'
    'OmuEwpJudkmUMLbYulZmrhYilBdjwg4GIXkTAScRTBgNUQwMe6bjBTzQelHvPMy1eAVvE3l76LiLWvdyxWv66JTDL7U0GnPvdfDLz2ZgEzQ22PysTQeQjAEDcRIQ10UAAHeRr4'
    'ghEmeqW1do+dLW621d28N15UpQIBYVavbEvCb0lHm3YVtRLCpkpHQf73hRmd0mBxMM/spYH/USQ93CzOiibBI+nrZqNhRxbmk+fF5opKGD7zw+/4INDjg4AYgTTuiiiwkmaKPN'
    'ezBI8I6IqEuw0eow3LBRqV3QaXDWoNUO2tZyjckgra4ttiXXhdpMONu5yLqYkBiFkqmReNsNQr178w0ZTnkBrubiMENkG/FoYi/4w0TBJNOqUHcBQzA+a4AK577wgAUF7z/yCO'
    'iQBHPDDXiipdYNyt3v/zv320jshlAw0RjwgP+pCFbCpCAyGWVLELTI2yiGoWAN5iWxYE9k3KM3EHiQER70oN6CMS0WGYx6BXHY4AR3mLVxa1vichR5bjaUp3xFBa7qgjPO5zNk'
    'AGIY/jyIRC+UEIciUoAC8ztaH070pCelYwQ3MBJl8AZF1y2NTgRblZVcNSDPoGcOWllEUGpoFIv8IYMwkWDZZhgzGl0MKZBJHiSGILqfgeGODcjjG0Sot2LQqTTUk8vNvDcume'
    'EIhjQKj+8Y1aUawoQmrUIdD3+xORJEgoiYsIcaMEEGTSDRBL84ghd0cBl46KAMI7DbERKwqQTgLT4CBBi/ZslFQKLHNwpSEGuG8kAJugR4fNkehVZ4JvbELV2QgEQdNaABMJgB'
    'DHlswBsa8Lw+oiOLLKlIoMT2K8TpaDvEM94KD4Ums32nTDUsinBaFSIJRLEDl2vfEDMph3vcwwZq/vCkLjSwKT0gSQ/+9IK83iCvI8CroEZandOaljqqEedV2bSAb7aiSzKe53'
    'ddg0nw1EYYv/TuV1eI2xrQMYQxvEd0yECGKwABBRxYwwwyyOMRQGCyFBXjVDf5wzYdxysKEo9HfjEcX36qGHB9rUuuGV8kRXQD9P0CGU7AwhDtIQd84MOem4QfIMwgL1l8qqCj'
    'AMMozDAKGcCUXZ3oAJ9KJyKUuFUscH1oZ1SgwInShShS4Zpeg3mbDfUug8iSnOrmoUwTuMIXvhjGMJ7xjG1YQwaMYITd0tGHZQ1sJb8UJMQuJNTBRIyQvjqIODuaNgels1BKhZ'
    'rqYNBDQJCAAkqg/qdV7yEHTIjCGCRwAlkbcAQZPKEBYzVDBXCwjWfgwAw4GIUGsPEGtbZOLWOJrnRR0jR9+SezWMFryxjGMIrpZrTikdHDjgIWprauAz58BBaMEQke8ICxMpDB'
    'LQzhzxNZoRhduK4CiZLOp1wsOxEDb1E7m7Yd8RUvEwKfUSA3MKnBgHLaAIQu3hdbqsrhwvYQBRUikVvjJhcHFXgG50Q8DFw4wcROGG7ROhCM+PCvWSN4Yjr4945lEUd2Of3lFx'
    'kmKDAy7DXFG5uwoJNUFfxLLE/sw1Mn3AsqKMEYxsDFMyZwC0YA1In3ze8aTiPI/rIwkYsC7cxkeFQHPe5Sa2CO/knngdIJG4MKorCHnOesBCX0or0k4AEJ9pxn97b3z+4lgS90'
    'gYyfqTU+JnulF6IYwNIF7JqwCiQYfaOVSmsMMRB8UzdtRCxaSUQmYSHLE73wBtf2Ig5xrjMuhrGNW6xDD5JQBzz28zTMKlBhSLWNpr8cQ8Y5hDZi1pE4AmGhtxlTbibtgDZS6o'
    'v11jnD0BaFKJQgil4M0dp2rnOdpz1tO2MBC7oAhDZ+8YZOPM9ulKHX8+rFutTJFbMuyV2Y5p0VGEVIQrtJW2/okos/jFQCaDGlF7DhBArEARNykPOTcWENUughG/RQx2Zu6sWM'
    '8ZTXfQ32gWlEscXdbC8XiZua/vXWQye0zxjanrMmNblJe2DCti9XuZxtGwck+gIQRSM3u0bxBjCwi9wdUKv9nivd6qok3mCcN73r8qvYIOpMvCHWIjTm7xCVRR1lOMIvCi6KKd'
    'wDH3KOsjUYcQGIO8ABA2gaabDr47CZGdMYH55DxCkz22jcs6bFq0XAosONaOoXmctzyu1xVXwswao2sIEcFF9VqzpeDmooQM0fcXOca8AMmBcaDrCx3J/9Qq33OxFa9sOfp2Uz'
    '6WJM/W9c80a4lM0q/71WnGAyHLI8KevYIMHBHQ92JbDaymZHuzPyG1FsDeqjNIuU4HIEFQHvBUKyMu1O5EQapu2pD+zCwQ95/mCMODe+GuAPP/jxUQ3yi/+qkY9DL7DgC85VAB'
    'CAGK4TMgd/HKDiZ/TywgjMYha08KczsbBASldvZpJvAiZ7xfIVw2En8OBPb4ADWBAGauAG42cPSkACOCADAEUP+vEOY7AGkHFrGSMjcuFr4cI4EHIjh1NBHvVNh3NOO7EgwCE+'
    'qxIiYyEy2DcKm3NJcWZ+4veDQFgNS4BP1bZ+e8Y5q5ZbSmhygIAMRUMvI+AkW6AftEYwZ/RFxKJZ9pY93PVI//IOzlIGIGAGThAJcTAF5ocPchAHPIADDWAIEKcODpAOTTMEBy'
    'OC3KVI5IEmRDVmQ0VgfdUQVfF6cxGDUzeD/kpVHFZwIqn0BmRYhnFmA0E4ieFnVZukYXcWCZqIBX4WRHpGArpwc4VGUJ7SRFuQDigBaSqARriDHo0hXomzEIOkXW4zPujgDHVT'
    'Bl7QANgwDBQgCvcQfrQVB1jwDGBAX5dxih7IIivzN8bXMsKWONjDG4njgt5SKZ51GICCMAcSJl2hM+x0gyJDatgACFIlCmrgg5QIhPhgAy5XAET0ZPKIclTQC8bQC/ADivDHXC'
    'DQKZ6iJ8tCUv4xJTKhY5rldg6ihWVCETqzKsWAi3bjiKaGcOSHfnFADLp1BPRVBiZyA1KDNVeIh9Dogn1YjebBh3+hTWgDFZCSb9wYJxoT/hwyEY6LOI5vQHDnSHjquI7jd08z'
    'J21ASW3cRkTWlo/htnlgIC94E0DVJTD8YksVQheHSIBZwSDFEhOQFBYwYCQ9B1WRQAWYoAb2VA33YA5xYAy6AAW8ZQj/aEUpE1K/k4fiAV57oXEluSsqCUw/Uo3dtBTQQRcTAY'
    '6qZQXvAEWd8AZQlZPfx5Pjd1WMR1UyN2e2JQpGRAEcdnObZwY6l1DLAldj4VCd8QcCGCa0Qhe0cg67NIO0x06rpWSUFFXdF5ZYpQadZAzRAAgaQE3NoxwwQFItImnY4iiTsjgp'
    '6IfOVyhBopfD9IKIwl3FYiyQZIOLyJWZgwU8SFVWxZjl/jdbaogPU1BV33Bh4qkGLodqcUAFlqlnnLN52HBo/LMfo+d/TXN0FsAhFOWNVTkmFTWDkKRa7uRUgOALJNBkcWAO5q'
    'AGCEoGZBAH7kACw4CbSUlTVeQ6V6MCV+CM25WNyqcdQLaXyKlX6oGcaiIzF1Q9GfOc69ROYIh9N+kElvRsOsmTFcl7NEqjF4agL4dq9Xhn7Kc5P2MkJ8J/U4gc/LEStzSAbicU'
    'uyQOjxRJYwFAPiNhUgVnL2cOCkoG4aAJ7uAOxBANw9BSPidK+qcWS4MOJySSyQdsQeUyUEFB4qJXf+OK47Q2bQqikwaYNOifakFqb6ABFeAEPEBt2LmO/tmpnbyXeAi6SS+HiZ'
    'HAfjj3C5QBD1N4dme3GRJgpvEWRneFVxzSGjK5KmJBmFG0ZBRwapzESeGQqpqgCVSwpcTQpQ/aTJ2iA6GSDh7YFqu4Y3chGI3CfCwpLhb0a1cBpy8RQ2JGNhD0GTsWJ9CJQypa'
    'mOwSTzzQCz24k5W4neWnneVnT/cknnM2bZroC06Yfx7hACVRqSihL7k6gudBQU9xEaAqjn3QAaigC4/QCy+Xr5gQDgy6pf7KpbB6XBoJKiZCh11wprr6Qr5iSCYJiH9YKRAbp7'
    'hBp4okMUdBPV9UlYfYrEsFQCZzkzjgC1+ZSYV6ftlprYRKloVnVRjm/nJKQAWOyk8g4Cl64BGy9kTLeELKqiVxlBTGNFI2eCI30AlPda8FEJb4ZKX9+qrE8K9ceptmwFtKcgIm'
    '8g76kjUB+GM/ooJ9FR4Vy1nLSSnEuiaBsyWfgV2dyjuI6G+sCUB9cJjlKLIHpwY2sJNpqK3nl601mnCY4G3iig1h6gWGYAheQFNrZSrYFCCjgSykgSyBRRzvUJOp9Auo4AsGR7'
    'eISpsMyrTEYARbGg7uYJvDkIFogIxVezVIF5zCmhATAxEKK0wJQZcKEacQKy69OhUTpGMGwl8xsjENqVpuq2QaMGEUEAay6XjZKoR4+4MVWYmP53LVhgX6eDlB44hv/gB09pIv'
    'D7W9TtO9CyUWYDhqNzlhcVAAdMutalBErxoN0fCq7gC64QBlXwoGVqYk6mCrEtAcZzSC5kGnAkG7ZgMpvqqhlJKc2gRmaiq2GKVNYPOcjwS0KfJOS/Y+B2cPdYuyy5u8zbudLD'
    'sFmHCe6ye9iMU58AcI9wcJrWM604USatHC03UnzhKR5TigEiiJwZigVNCl7Nu575uqoRsNz2AGjCALACVrymGmW/JjbGNDHxqnIhqLM1NO1lEpXmE2v+q/17E1GpKQHWIs/vYv'
    'KbKVUcpkFdx4GIy3GPx4tfXBL2tt7LWJg1Zo8ZE/Z4EcZ5E/oyekWyBw8xKyWHBw/jYQjLOVvp7EvvXgvqkaDlRgDIslxPSlB0bsDHaIdDHJUeVBrCrYKIqjoTkip2Dmh4O4ax'
    'vCrMHBdxLgDBIspcZQxmeMxmSpwc6rhrXlcjEnCrZlbeDWniNDqedqEmYhqZRqEmdnSln3gOZohnRbkfZkllyKBTtsDD2syLb5DNZwC0QMyaPSm1mTsEtcEMT6N4UBu833EEF1'
    'l+C0pjWCFIwURlwBnaBqOk3VpxowDNZZYSUbhBs8ifmMz4j3dVVVVVMgZ6IQCTe3KXLIByRBEiVxGZcRzA5wGafUj8jVbGBpD/ZEfveAoDWnwyTwqlSQyIvspWNXv5HMIvuLFd'
    'ni/hATwzUh6sl2UR4IISs+BazZI42DsY3Y0alipEuIWIPgazIgoAE44AokgHKadMbIq8/jp7cp27zPGweRoAtm4AV6gB+ZwQcR1yRNQrXqcAKnJIZHAAbaFw1vho71hL4L6g7f'
    'tsOfm8jT3HAXAFB6cCJXk8RK3DiF8c3pIXdt+quKxDblxIKcpc5xwV8+ESbG4tNjMQC6CALONAxkLQrm8HVKfbL4vNQZfH5TMNC+gA1HUB8hIRJYDVCekgC6WNoCJS9moAFQAN'
    'lvFg4HOpvpu9Hs277GoAkg/dZvWMRlUGOYWlequ5fffMCK8rUb11ElebuADXtVYTyGvdO/8cAB/jAie8wBZcAIDWANkA1n9aTP+5zZhtp7GHiMoM0Hy0DaAkVQbzAKncBcYXU5'
    '2kfUth0Okp2om3SexODMWPCq0JzIP0zNtxDXAHUikgyCInkXgdOuBlzFq+uHfaHJcbeCb7Jr/IUg3vhpOBQAY2EWD60HHIDd2m0MsE3Z+LwETA3ehmoPUD0MUTu4Hq4HgytNQb'
    'M5EsY5nqM5w+AKw0AItv3RCooJSrvRzsy+/e3DIU3NDUDSUDJ8BmPX3HU9EsPSxeqmvdaXET4ViwN1sAF9QTYrhqggcpLhYjGF+LEMknAJjGANUEDWZCCWk2jirYzi7JhhuAUI'
    '1tAAm2AIINQA/mCgAYBA1Or1BfiYid825F7Kvkbw2kVURKH7qvvtvtH8tFAw0qRtIkuDsHlod1EesZ5sYFNhIxx65RdyJhYxQxUuFAkYGlCz4ea6DK5+5rcQ4uEglsEo57a+nS'
    '6XwzmuAdYABtZQCxrgCkRdqqYaBgVwtGGA385MCMzO4+5LBdDuDhRgDM7cpVD2vtgeuot154zwyAQeO7bGzW+3GAqOjb/q4N4k6rshGy/yMOk0EOIzE+FYFq3+6pIQ61DQtG1e'
    '67eO4leV69QeDcI+8Gz90UibeIt3309LCMLe7O3rvsRgDExL1k2L7aAr6Y81sG3pDCTlRdxcseRRu8lnGKNl/tyfXDO8gjB+JTYZBDnkIyL0jtCuLgx6cAEysObGsO/83u/Le1'
    'WQRwYaJvFdOvQ8rAlAfk8nq4a0SQVGwOymYApQYAoNv8Pt2777Dc2fm+1eOgy9nuSeEmM7BO4e3zAluIIwvYJca42iFVprH43g864hF1jX9C8hAoZboA7mPfOFgN2tLeI6z/OG'
    'Spb2BHnmsK9ZGu3/ittkENs7j34LSgz14AqmgAiUjwhS7wo8vsP8HboWv6US76VQ8ExKaTcAdGPwtqza1aFVHrsOjjHKFyzGw+U/8vYfFXIjVQz4FSI71Dr4Q0onQA93cAfZIA'
    'vrIAM4MAwRP+u0DvjsKPhY/pXROFr4QJ/I1B8OWGqgtO7UZUkGXEoIT48ItQD+iBD1mO/skN75oLu+Oe5S02S497ND14TpbVf2BYbO+saXVv7gI388amTqvAuTACFuTi4LV1Ss'
    'QVdMwkIr797deHjjxggdOk6kypZKlixSo7Y940ElDhk1au6drJZS5UqV+FxWw8eSpcuT90qWJIOJTM6dOs39NLdTKJmgJWueVPMzjpF6hEwhqhU1KiJEplwRIhSNmBF37sJ9Dd'
    'fVHTFi0Ya5coVDA5g3b7z0ebiwC7o1Kv5YmDMnSd68ufzG8htYXOCBgQ3nGuy38GHGhhc3HrzYggWCsSwAvixY3DnO5xZ5/va8d46FPyrQoWM4YAs8eOnSjYCdQPYPNBHQzJKF'
    '58mECk5IRBJJ0iRKmStj3qt28mVxfEjVYAo6UrpQ6OaS2rMHdGc4oUCBhqNClpCrp1Cl1qJqtR7Zrl+9hu1KNtr8s4A0aHgDoo8XhzAkoAvFrsn2SmKvxHIBLBDDBjuwMcUcPG'
    'ygyCBkkDCCKpvMMg39EmczzsYBEcRFChyttAACkMCKLbZwoEV11NFDB9lk4wcFFJqwMY0npqGkN1p4AC4OTIxCDrniYGruqOWMay4pneKIQxMpoxwpJ3PkUEMOLdXIjgyw3AOP'
    'CiqMMaasaMij6jypqjKFkHq4eu8rKsIy/mYs+eZzxT4N+gDBC9fSWQhAFSbTy8DHABPMwsYGeuwwRCGjMBdG/Zqs0rvuskywD0McZxFPSzwIRRVZ5IMPeui54wQ9figDhU9efQ'
    'KIaYCQlRkxpGnkx156UYK74YxkLsmj7lkSSZueCycOsSjoSpM4woEuSy3v2dIcUcCLr0wzzRrPFSigoMq8TdY0xZR61jNCE7Co0KSrMt8lqyxC7APDizJ0aA3QuVQALK8CBRoM'
    'UQUTTazRByWFMMIFEWP4wAYrtfSyywDrcFMRPd2LtDVEHaBFAD5exgdhsrENj1c/mWaBBVgQoweXcc2Vlkgi6UVIko6SaQmXbDj215hc/qJJjuioiM+IrZqF9ko5iMVHyy7plP'
    'esZ7791pqqEbFGzanKdZMrdeeEr05iynR3LBLyBAOEMspgbYB3/gvlD0n/3SuwgRPlMOHHGnRwUkgPHA3iuyYbnMOKO704YxO7kEA1B/j42AfJfdAIjSd2XNnlA3o4oPMDpIiB'
    'lnjiiSQFkXT6VSaaer5JyeaExgTbeGd351nrlga6aaGvLdMsb60B3hoZgAcjeA2sMW+q9Lpub04x3SGbmK7mjC8aKMA4whA91HEAHrfHiNuCDv8V6C8EFUbYb4TTP+xuxiYtjO'
    '/1JSUU4gwpQ2yzJEIjkbRQU+yYOgAwOR8oQCOzwEMa/iixAGlIo3OcgCAEi1CEGIyOAYrgle2IhJLc6e453mkdlpJiDvBoy0zs8QpRssQ0oMnBHl4q03igkDUwNKMBN5SBDMyw'
    'Q2vgAAxqYpOb6iEW+EAPhXFyz5lw0IAynOBU3bNCF0JxhViMLwkdMsyj8KYw9UFIi/Iz2PvwMsbAVUoxeREIX0hjIlGlAx7qcOIdCmjAUswiCwpkhjSkcIAi9OMFf3xBETIxwQ'
    'kqwhG9SEEcRIG6XzGNWNR6jhp4UpSkjFBOdprd0dQFHS11sGlJCUtZhjFDMNzwFg0gRQOeoMNR4MAMarkPetJjriO6i3bv8VIoh7FEPWTjiVt4Gzqu/oCXAl2xfOdDpmPg5xiG'
    'JewwkSkMZfDXN0nxJS9jJIj9CFeaNWysC8VwxjvSUZGLpCIVdZxFPtKQBlvpcYKAFMILhBBPNrygHw9IgSJSkAIlhMFmrTuKCEc4FC9t55Jj0ZZWjjYnonTyZ0jCB5dEMSbfAU'
    '8GqOQHKS43Ckp0tAKtNAMYNBCuNmUlXmTKZHu4I5RwEGMY1mjABbKxDHrwwQGAGgIVK/avxSAKf3hhJsMkpKjAaDFvjhmjGadJGGs2VXB/gOpBunmiLjBOnLC5lyx+UAI85EOd'
    'aTjDraQRgwmywRNCoIYQkoFWtFKjH57oRzv2GYYwLJKRNymJCH8S/jsoOUsT7BKL0TIpPXewKxw/MUmxjJUUMoQHC3na4ShkcLnLTYNHC+gRJXDgyvtoIE+umI9CtTJa9qiLKE'
    'EJhzGiITxZCIMeALApoIRZRXEUE4uBgVg2gXqwx4TRQdAkSBkhFgvAPApgc0gjXwgS1VAFoKoMsYJrRuCFEaCBH014ggHSAISV3Qp0iujHW6lBjWSUd63lFUIGqOEJ9sqDru8V'
    'EiZQZ51K/qSgUSKaOwS7nrLMrk5gU+HSiDUTJGGJhI4dhhNwMAoG78iyllUZZhewWQqjZRgXDm2Go7Eed5jWvqmNxjNuYYiZAoAeDhjAf6iol3OQbyCYsYw0A1eY/kmVz7fJbG'
    'bB6lcpDX0xf8W84jVjwU2qpsgKA0DyFmDjhQTwgx+fkFV3OUdWLvTDrOM1b5azrF5qZKC976UrJoTknaCwFFt2OpebsFIPhar0sPZYYUyOtDrGKoECPHCCE5hBCcvS6gxBOAML'
    'wroAZmC2AjioACCegYMLN7rRWdFKV3byYWOMkhS99AFsb6pi2u7PmLjFjDZ329uDFfW3ikmq/TY0sA61+opBRtAfroAQxlnhyCtiETxiVIYaoWwBLTsABLnwAjaMt8vJyEAyeK'
    'FsZS972ebNQLTl4Ql5uJeuolDkVwrKnXXFpyndQsuayQI2+irnSDNBCiZEsasv/jSCAHkQw8qCEAQW1Lvev2YGM/JQAX5X4Bn//vcwntHo+RxtpTuB3ktj6stSbQGnKwayaC4k'
    'amymD3DO3GI0tYmpC+Vvp7XFogUCoYJQnAaAjnPRCU7wgxqNQmWceycb1GpeZ/PC5jdv9s1xnuwMTNvadIXStb4UJiNGo1vlKtdVIs2dIeHu3Ec6iQ0wEYZd0UIKjeiBvVmAAK'
    '6zwBv17kG+88CMfvcb4M9wBYaXrq5wtMssMC2DL08MjyhOUXz6+zSlKE6oCNF4fhgPbqpVbbiKgRyLxL1CKEJR61G1yAH0UDkaLIeyPDiwCH+cec51vnnO6zwZOZA2tcOQSCU8'
    '/st5Z05ot8AFBVNAAStk+crtFPv0lZxkCpiQRwriQQtpuGzrCMAACzAA/K+77Fb5zjcltrH8Qwd8GNEgAWE7HB9CQMEMRyjD9uDhcAlIUQWIKVCLO6TxvQN1qH9njPsOU378Id'
    'fVhh/IZRI/hDFIAAbiZM2LVK4HWaABBTtiBpjrB7QqL52DAF44QJvLgc47wAS0OWQLvZ9TAjEpotQ7C3AJFyhAi6VrugGjvTnDBxsogAJIgQeQAinoAW8IvuEDPgxwQW/wBuOT'
    'BjFIvsxivt5wAl+IBiwgCwtciz7BF4eLImG6CysaP0oJNfsZjUURqmZyFMZgPwkBmNriqcC5/oL5G4MxgIhxqgiLkDw0wIP/m4Y8koI+egHyajYIUMMGRMDOu7kEdEAI7Llqqy'
    'soya+E8h2qOZ7N0sAdrJ2cUIPZ+0DjsAF7IEHd25weCD6uGz4XxAAmUESX6QExoEE+4xGPwsFhIIFh4IHQOgtXuA8+GQHXcIiqCpB+ebUj1LsY06Yl5C0vMrUkFDVrajUqLCY1'
    'krVQoD8YkIgRSABfTADr4ofKooQ8srzLQ0ObY0MHdMM2VEacK69oi7YCsLY4mMCEusCqAZ7jgQJA0EEKEAmjkLNBnDMbEIECCANFiAEU/DrgY8QWfEQmgMSvE7QzOIMHK0ayaw'
    'QnwAUnEDiB/oMCH2IL/UgHh+g+QfmDWHC/WiwMWayUwGHCZXpC3bKMSyENiFlIW7zFvIiqIUAHGODFG5iRJmMwjkI+7yKrIii2ZGzGlmzGaJzGEQyD0hsTl7rA4CmeV8IBX/AF'
    'EqCAmhkSGxhHcjySQiyAdngAq/O934NHDNiDeJTHrGOBeQuBewwrMWiEfWyE3qgAazADayilPukDuHAGZ5gLdFABKpKUKewLJJSYwKu490E/R5GYirzI3MpIzgAyXDwIdBgDXg'
    'TGBPgEBquAPMgDd6MFWoiBlCwCFyg2mus8Zqs5zfM8Z5PMDACHDKgCmVSCXiAGHiCEqSGe4gGDV8ozLKCZ/kWaAqYhynMLwSkgQUWIBxSst65jRBd8BXnUTQzwBgSYt9+8Skps'
    'BDHgt20wAxlghOzxAj95h7LsgiGoC6gilIXsqfNpv6QKoxpzQr8IBGmSmMGpy2mqRZATDY7kJr/sRRoZzAUwTNFRBPBqh7hqBRdwASzTMssswPuUzPyczAe0uQzIgSrYTLrqhU'
    'jYxKoBAxlIUNN0Ah6Ih14oAEyYAp5pzacLQUNMR6vrvdrkOnjcA93UTRXcunlDALCbRGmgAWbYhgl4AkZAA+3Rg9ZozrmoC36ZTlrMItzSuxsDPAwRnNx6kPG8phI5zy4IySZr'
    'OUo4zHhIgXaQhza4hjaQ/tIpJa824E8tw9L81FL+9E+cC9AqyL0C3UQcIB4FfSUfKZ0RnIIpwAedqdByvL3R2z0pEAOtc0fcZII9+NDdXMQS5c0Y9ABKZAZ/eAJSkIUL0INEbQ'
    '0rMMtuEhC84Ivxk59p6iJTYx/fcshU8zu+qcjSUIFQ6QItFMkEcBWXywNaUIR2uIZr2AVw2IVd4IVWBYdkmNVny9JbpTksfTY31Myeo7p4IAEnWLSvLE1EcwKZSYEwEIEJdYOh'
    'fFOZsAE5EIHRUwQGkIINFT7hc8QP/VB90Ad5dMRwjUdAPYN1woONUFTveZsu6CbphNRIRaNY7NFcUD/AG9Kmakt6RbxP/u2mjSkyXuyETniyT2CGrEzVa6iCb/iGbmDYb4AAh+'
    'WFb9g8ZtMyNMwyW83VZqNMZtNMeWgH2cSzQ9uhzeoNEnjQAljWb2jWZ3XNprGHqUuBXlDM3uuBO3VBedwDfdiHPQXXcGWCR3yFrzsDYEgDPIgCWUjUGC3IYuiCAIjOweELQ/Et'
    'iczRea2mpiIQa/oLWSM5hHCuqmIcCZCIgO2ETyC0RpCCg92FhXWDJXDbblgChn3YysTVLMVYyIzMHEiG9ULK3XOCPHgGfnuGPAOSZF3WKWjb1nRWOLUHUaBWdZQGSBRXbmUCb9'
    '2HbwVRnH2Fb+VNQEuDfEADRmCEtSmD/oJ0hmKgizVwV3/Ri4y0WsBzH0bxl4gjkRcrjZILWyswsoaIiIClA/ZshHhQBBdgVZVtW7dF3kpwA7llRorF1bu1W5yz1fWCK9lMTCfY'
    'xzwjgS+gmQhd08RdApZt2XuYAnuYVrmKhxg4AHlUwZ/N08rVWZ29XMzVUz19hfsdvnLVkRZlhOXkD2c4SEeF2tatXSy6LfkBvOJ6JlcrEE/BmP75A9ztAltLsi1QjdcYgbKlA8'
    'OUgnjoBxcQgbV1g+OtBuRNXuaV3iu1TOjVzxU2r/HyBDbohyKYzcQkAFrAAu7lFWX93hIWX9qjCRso3zCITwpaX3B9yjyV331g4ib2/tb63QP8nQQEEIMzoAQZGIUGAAH9IEuz'
    'TF3pjNpCqcWjel2BMR8OQa5iGhEHHhGOJDl0cIZbYxHHUwcd8MVO2OA8iIcHUNUqEGHwXQkTrgSGdcb+TOG61c8sGy8h8CNCouHREV5ECoMCUIMJbdMfJsedmQIREAEX6AdO2I'
    'fdzE0lvtwmPoAm3oANgGL8/boUFVlsSJv9gAv/YNfohNRb/LQOCQQETuCOI7zaajE2HpGMiQVaewfHKZVSoYc6Zjk6oAMp+IIi8IQ2AAe2Pd7wxWYfroQlGORuiMMuzTnnzTK1'
    'slgsNTZPsKfwIqQH0Ke58t7VXFxMBmJ8+AYRuIZ2/igCUMZZDMjND23ifQDlgN6HVK7f+81ND+iBrEw0tciP/XiId6iqdv0DayKQ8dxOCGlIepVXwvO0JFjj2r3dLggn1khmE4'
    'O8CBDMDZaCB/AEcMgBhoVb5PVhlcDmt/XmyuQ8cza2NhACnja2n14vt7KnP+KE8Aqv9kLZNRXKmAhfeW5NG/iGKqAGNuCEDfjWV0jinF3iCApogv4HrK7fAyCCq8tebMCPPvET'
    'iIhou7iLMB5jcXCfeq1UyEAj8tzLwCE5+nuHEXgjufOBO0iFCPiBT1BpR/CEDEDAbtjmbXZbH87mE55b/9RYyUY2oP7pYsNs9oIrGQ6vof4jK1sv/gFVaqFsaqeuUDf4hl1oAz'
    'bIhMv90PvVzQPQh2CLAU6obQgaaFWGYn3YgMVMTFpwgkPDHrVJ63cYA4S8UYvmZUXhUUZJo1ZDLjVao1BYg7+cCB1ooowIbNpYTwLYYwDlBcWuBMaW6dKuadSOw/20zGg7Z85O'
    'Z6MugviEb6N+gaLOBD9CK8xcW+M1bfFdgm+YgjZwAUHyViZ4BX7WTSYOtnzOZwhK5X+o33/g7R0gq+tVsCw+AntJ69MdggChosmoJgbhG/UbquxsmOh2qm3iV78EyVGlDckLwy'
    'cw2zzoYJYGUAgY7/HmZhN27BK2ARvoBhvIgSFHtotVNp5TL7hS/mdHTsn0Td8YkE1H7odMQOfxSrYceNhrHsSHimfxxQc3UG1P4IIN2Nk8fcR4nO19WEwGx22r3gMI34NUhiAo'
    'pwWFNoNROALlfIt3gIFiGIKcukIfu2hfJqoz8rjxQ/Ft4iZ/DdUWJ9v/25FPKMbK+4J4MOwbx/EcJ28T1pklsAFP74YhBz2eK/Jog8D1WnIaDp3QOUG0PUEpsDrQKUNOMMP0Sr'
    'aI7QYStlAk4fWHcur/3oUqqKfW/lB+RvDKPeVgo3Wuzu04T+UN2IF9oPAYUOgFu6EtXs4+cIZgyMIOD3TjGnRmUh8pPPTIUPTmcq6F4PMb8N0Z1zc96uA9tvEh/l9DTdfxbf70'
    'H9d3IR9yafT3U18vzp6gWL/WBjJ4FMUVrIR3PnqAFzirW4cAhm1s19SZn2lToOn0LldcMAcHF+ACTnhifj5wEFVwCYqgf/ZWqybzfeicBiK7HRpubB9LPh+DP//2LTpj5g4ui2'
    'u1JlwjqToR6HqIDMbjDSYA0CmCB+gjzQZQel9DHM90xc71IHcDfR/yEdxML7Ns6pVhpQ+dA2ggShRU5DvJytOjeDDDY0vsmM5mmv7yt3eJZpV7uL94mPDv1K6CAW9tAz9wRxzl'
    'ZOcEPmJ2JibzwtdZse4BFCU7V6qhLUbrPrgBGKh5bycue12fe43uMd5afg16/iNDMgzG4wU4+gliry6TxiHnhQVswKdfQ4dd2ByYgqsfwQLwMs1mr7fCffguglhH0bEvRj/gs+'
    'DPN+8qQxtXNjVU7OO1+GZ9+2b9hi+HaqFEXKhu/ktm2S/fhWsQ8xgocHEdZSZgeTW37SLgo2Bjeav2Vn3QU3mcwX1TCzBImy02BP+ViJpXvCsAT4xmbny9rb+Iha4FiABdJEiw'
    'MmDAFng6RvD7RIeAlCL9qCVLxovXNwi8NObQePEjyG8YeeXIIaJKgZTyPKXw9OBBv5gyZRYpEi+GFGnSxIhhRunMtKBChZ5hRiOPlBgwhWSwuLFbtyVu3OCjavUbvm9TtHKV/v'
    'NN65StW7FSxVftLNq0atVWFXHNUxFOB5hgqIugLoZXTJjoY3Jgn9y4RQ4M3mdY357Ee7wxESONWQUcOKyBAdPMEOYyXrzcgAFjyBoVsf7EsmAh15xcqlGrFrc69Zwkc+aIm53a'
    'daBYV0KFQoduoBWDCOGl05GgEx2kRTxR3AjhOfTnJEHyclqdFzhwu6pkkLcyxQPwjh4UIV/TfJEYRZLm3NnzDNA0Z9LQp3+GEjOe0iLCpJbh4nNQdTOVG98UGNYUu4gwxYJh7Y'
    'LggyIsuKBWU5m1FoZqFSiCPO2kx4Q33tx1F157+bXPAQdwoh5hKv61D2KJ5RWiGHlUEJkG/paBcEtmZZQxwg3OjAGaClf8YdppsOXimmusqSZbElDOlkssVarQ22/OSPCOQenA'
    'A88IOnSCXB4EjEcNgNBVEl0OJOWQAZzJNFVRMuDI2YYn7bQT3kvx+BlDPFIEut4BgUpxaHs98ATfNPMBkUYIQADVaH6NCFqef05B1803nIIlgoIKnqRgFaCCWmoV4JwkIahyWL'
    'jEWvjAimFVDMrTyno9MMECBgj4itceTAT7YmDrrSjXBjHu8Upd3vDEjGRmgNFAA4xgZoiPXrwDQzHohLKGkUcmSRuTTq4WJbqzmaYbb+iM4Ywz78ibTjoj2HucQ2V+8YAn/zm3'
    'ZoAQlPQm/pxwUnPwwckcjKcLMcVTBC2ISnyAxPvpJI2iHiwKHxAhnBGCx5HCd4Zjh8bTD3NNUSfSLtvtco2E11RRhcwypzozzW1cI48L8rQhz8wPYoWPWURbVVVVaC2xRFZutZ'
    'MCTj2wwIKvI5bolz4prjjYYHIZptgre9Q19QILYDOKGdQ2cAsjF2TmRR9BdhuaCuLetmS5q6m2yCJR2mbBH3+sgU4xWr5Tb70LJbC4Q6iUOV6//kbnEcFw9usJc8wdzBwbbPRT'
    'Xgw4IaoTAT3kYXoPqKfunns8sXBGEB8HEULssbOg06UoR04ddtllcI3OPO/ss8/XGK/zz9S44IkLbLTj/oIL1xTQYFU2IC2WgQRa5QaDBaSgSE5SsxAE1STqJeyJKAbWIieGbQ'
    'A2XmVPQ4m0MqzNCP6GMKKZttyOgU5oApckcRCQgEtaTSxywbe+yQZwgltDMbZELzDpwDiLQ05yCPAFRzhid7wDx5vkkQHMYQ4mKOvHCzzxghd47nMrwsnFasSTGYphATNcQH5m'
    'OLXxjS8ICPAhEEPUgxTVRHdysggS6dQG5SmvH8tjnid+FsUMUEMeB2seCmvygph4QmYN8oocINSyXXyFQF9R0NNoQYudwIeHV9uLPrKGIhfJxWvJel9imDW+BUzjE094whGqhb'
    '/8HQFufYBXFwCoAtFY/oBcBTSgahIYC775bQ6AU0GWDqeQE1TwB2hoSAbN1EE4tekjdKJiCV+iShPOZIv9yAQn0kOx1PFkASxYwBlsWTZclg0+uPTlDlkgovL9CgNMMAwn+sEG'
    '5oAjA+C4jhKpIQRqeG6LnmODC9qxzOW1wQXU8ETnXlAEWG6tJu3wjoQgZKoxtuwrZ3TL99bYE2bAjny8Ygz6DpA1fRgmBi5y3z42gMdlYWB8QACCH4+ABvxV6wgOBQHctuWMRK'
    '5hDaQ5DQHP8Ui9JZCBDfyDCgZXOHqdAB4nOAEa0ICCfOVhg44gZZv+Q6fN7ekB8bDpnx52nmRyoqdFmGPqyMYCSRF1/gFBIGqjgJDUMwQzRHbpFbPCxs9MsJAi/roInZIxTSGs'
    'kAuZ6AcXiuDKzmluedRkgzjJaZh91KQI55SHKNxiD+PRFXja0U7LwLEzRcSDFo1gBjOmgcuphchEcdwnitb6l/YJtLGJoYtBP4ECPOABDZVlxBEwewQQ9KGzzihGItGxyNI4Uq'
    'PlkmQsKunAkHYBBjcI00llYVkUPIESeWjEBjE3sFJW5GCeqwmgJIaoQcWyuHVMERPEFwSjEvUMSgXKox7l3JER1ht4ycsrspuYDVB1mhUByTN7K80VfhWWmRgnCpVJ1rOu8AWZ'
    'yMRa56geRaQgBe0IA369wzPotaG//tnJzs/aoQi/ApYSQRls6o6pYBgdk5/xRWZjBSojgxoABShoQkoxq9k3gCAYwfjsGLpApCuUBm+mhWQkUWPJ1YZiCGNwbQJ0kFLK4iENOI'
    'TISzyxW4EdsYXpOZRO8iANIQu3UC5KUYqCOrUgMFlSR/1YxxrlMSfbkwV0MSZ2s/uKf2zgHysUwnepQychCAGt7n2vWDkhTmtybqtmfi8nNgAjJOMkHvS1r57a0YrnuaC//U2G'
    'n9mQnkY8hhIGbpQYEvwifvKlL4hda5wjLdC+7OqoQIBDEyqbUjQ89A0e9nAxhuCtUDASNY9sEgKpFLjALbLFY4BEB8bEDwujIA3z/mPGfm6KOZhmgGApBG57ZpifPNSoB1KgGJ'
    'JTtI+9WHfJTH52k0c25ZAxdWoYwKeWtZuYf3iZzGEGSUWWWOb2UlXNKNziC6iR7oO9gKvkljOK/EKxpKgxHgxQBL7bwYXOdU4IbfB3mYvAACn81Sfzm0Z+Uveiw8TRRHzRJ2A2'
    'wIlMcFegy6YLkw1gAExnmtOF7DCohyByUpO4NBilDd70tppFVrTFQ4AEzCFBB4cIRT/SAFR5MFeAghmMGllMkRQUZcOy1ZAnqjvAEOcyF131wBs7hDbUmeyxZ4/PusakSx6XtW'
    '1utxvMmrqInSpCZnWj1cwrVC/Cxi5NMp8ZlhtA/m4PdNKIuauRFgyoCRdQiFaucpULYT3ATgJrYErYUAzHVpH7Gh4sODoYMOaNs2H2UtDZabwJTeAHGn5QhiN0NhjFmMcQeGOk'
    '0iRQ5aZPcQB84+KXwxwVjsvD6S6WFAbEIN/8IiHuY9LTJLNADLfEpWBzmejUJZjpzC5oQYNJPgRQjck8tCfzr311JoRNu2Hj9nu9bR2sil3c0mTDNzmHsPFngMzl5/uZ25dkRd'
    'XoKHNPShH8/uX2voALciGCooKShsHX6AAx6OnEBVSw6MX5OFhPkZPbRV5dSF3lWR4aJMBmvIPnFQPJJdC4mMvprQZBwItntJ7jlA78xRKuFEEr/vTDS6QAB6XgS/SDT62f1DBX'
    'Ud1S77EA8eGTN/QABuDgU1HNtTFfiIiIdYmI9F2dMWld9SkGd31ZVlVHEmmVwiwRFR2MwfDcETkhmbHdCu0e0s0TflCCY9xcDHAB/ZHbPyxbDzDKNNgafhheRMTFe8mZjNQFHC'
    '3W4wEgg9GFr1CeATSBJ+lAGaTDO3yWt5CGqRHQlORCbiDi6YnDQchLZ3QAHXygFDwAuvFb53gIvvmJJj5MRBzX0i0ZxxRVLjXVDRIhXeCgDl7ZlclhiZjiXiwL1mEAEkpcd3nd'
    'd2UVLj6TLvJCU8wJLlZEU1zh2cmFTvSEUPyEY8TAPnhVuzXj/j9Q3LJNzTQ8ihoyg6XUHgudWbJQX17I4jEBRk+9klrBSLDYBQKEwMbxoR/Sy2cFgGgsSRKcgzzWBpVYQJXYo9'
    '40yRbs4710QgegAgEQQDK1GzUsUTctkwnexBoRAO4gm7L5RfI12VDBjlHJYHXl4PQ5nMMFS2IgRqPxBQEOICyKDfWhDzJRFcL8Yi6OxDfkQDfkQEZMBzQxITCWn8+5UNCJgf7Z'
    'Wg6pCBfwnbtlApeByPiEQH0EhRhYiiLExJuR43XtBTLF0lcBoJzFSHblYTr+QEnBQ3AUgzs2UhIs0DnIRi7YI2mQXj6KgwPsIzz8CAYZm1hNE0UsjM8pwnoQ/pyQFZvCKR2INN'
    '3zMZlROV+VCVFGmghHKsYeIEYcJWZHKksecSNdmIiy9VRVJYxKOkVGdIobCEhM8o4pAePBfM56PEZ82BrJ3JyadV1QDiUGNJkBpMGj5EdSPABZodV7xWGJLFYssaAdTppV9go6'
    'qqMObMEAWIFXHkls8M049I1rmOVo4OMBpYYDOIA6tCW+JIcUJBMb+BtFTFMLBQqh9UQt0WByOVwP/qXzVSRh8QqWGaZiHNb7xOce/IM+cFt9MuZj6oUcSiYyxcS6UdEvfoSASA'
    'WBCgh0OIdGeER1WE5MwJDB2Rqi9UAM1KIwCuUGgMjsGKVRItzcnUw7HAyZ/r0XYlyXMfHTAYZjT61Vl83nVQbnD0RAdRanBLjjH8yBclLSio3GPZZeIU7nlyhOvhibmm1nmZWZ'
    'oP2YouSHehbW8TXb5D0dD01N9OHgRvJFo8mnhHEbfW7pfIINs7Rnck1mMimT5ijMEgIIVLjB0qzpEghINxxodFzEm3yTCQKZGNwHUJDMEKXmFbKdhTIB81EehOKaFCwlXXIVxV'
    '0ZicgbYMQFAKaoQHFbHvXKxr1oSRHnjFpUbIQljuYoWqpGaqhGQoCJF1yQQyzAfuzDDnCC34VVTcwSxtxpMAmTU60ie1KNtQkTrToVmKJPYu7DHsjnP3Rpl3EZlwXrY5Ko/q6c'
    'SDiikBQG6EVkxICwKZtupptODkeMkCf0w00Q3DyRjGP4XxFspxWGaKL2ylEZgHThGi24VaZolXvJ2Srik4n6lB3GWbH+gypk1+xgWgRs5QBIwHHWaJQwkLogiWnozW3QixfUSx'
    '/gy6nakDQQweEBHdIpGZQi33XpIHsGYRBKX2FZV2T66naVbJcOK8p2qZc+5V7oplilEFO86/ZBgGayaTXAilRUgrUKSCUYaEl0Rz/wVbDNUNwRxrhK05ixnaS25uw8SlBYIy2g'
    'jDz0FttxQl+w7MIBoIocIMVpaYvuoVZupRVIAAAhZ2ycrbqUZQbmAgw4g2vdwA30wZh0/sJKweY0givx5e0NOt09kQh7suJeLCuIDC4+TV9GIiZi4lHKcpmE5dGX4gVj6GZ6TR'
    'OAVkQpRSsEpOma3my1bqa19mzPQkUOVMFK2BSQCVnRwl8RpGRW+WkZYpzH2AeuPcyHtu4LtE+T0mt87V77wNI/7AB96sMreENwlsC/lhQgOoMi2Y1tNC9rhOpqjIH0zgMMdACM'
    'LU7mzRYKqOtB7ZB1peJ1WV0raiT5mqfDnQ/JImaMIAYeDRRBQe7VneQKPaucrEzmpmkl2CzOag+BLI3Oim4VsISh5KVOiOu+WSZNalWIDuXUOJcaJuUkMoftwtLSXZthxZFiAa'
    'B5CSV9/g5vEKRjBESADiAvvHhL3ZiGbcjGI0HvarjcEMzDi8EtbIVwKkTALGTa9navMLkiib7RKyIuYqLPyBpTSLqn+i6m+3Jjs9TFXDgeC8klnVxHmgjIVGxu5/KvzvovAO+J'
    'neqEsf3fRFDE9nHfFQqlPjhdEKQhwkHtA7SDL8IrC85Fcu0nHEEaOE6cUFJcX3hDv+KB8Z5UBQGiBHRBRZ3wbKDLCiOQbgQCb4gc9b6WSakDPdwBJYew5XFv9BWhsAygKh5uo+'
    'nD+yzmYz2WiRAg1p0P+h6mYiLG496TMenmE4txFH8EzVJxVKipzappVWhPtXJKDnQIeNKQhHIC+LUB/oBsBDLTJKJmQl+8zqQgnHKgTOty1e4F7tUEixxt7cR5VZztcRAAgwF8'
    'wCzIQgSkgh58iRW8w4yKltmiy1gaYorFQiDM826I3BjICzw4AB/QAwAAACXX8A80gcYxmRwCcfmiD3wiaygzphBLXmQSMfkuXkOvYrO0LGB82VzeIi0HyLTiMoES6PbsskcvDV'
    'TQjOkKc3ZOhKYEjIKKHVeVIRG8jtN6oTTQQjwU80ypWxzL8ZUxCzbrplTiceSJSAicQj7MwiykQjaclDpsQXBk6gmjyyLIYxKgWpUk0DwHQj0PQbwghD7zwT5P8glEwCUbgA/V'
    'hbYh7isitLIgRsri/lFfcHJJMgtkom/5Ai4+MWt3WSYS2e+ARAVIB7aFDDa1tuk37MKtxEAjLEqiEcHRWgQEVIJkGygZI+rbSaNQ5Ic01IQ35TQ1OKocXxddJ6ZultfE4a7TnY'
    'FRi3MqpMIdnEBTO/Ug0yhYhuU8GlAg2GMsiENWazVvdEEXGMQ+fjUfnNQJBLRAA8FZZ9c/bFmXKubFGbHiqi8p74V+QuZBOzSWGRM+zcUBVhUuzqRz1OxIg7QuH42smMWacgo4'
    'uIAixAANeIAf+IEYeABh9ANkS7Z+9yzNknG8HoAzQ6gXNoJ64PRcBpz6SR5eoC8yueHt9lTWiAgwpMEpIHVrZwM9/tBDUxdnFwSARYHlVMujRkXSVR9QbrALBAEHQgw3dY4wch'
    'tACPiKlqHssPqmlW4k4sJ1XAsxRJekRl73U2ak/L5A+UWxRoPEgAq2eRO2rLApVOwCOLQDN8SAfPvBGfiBhC5HMjzHfocup2BVGaPI1BwUfUxDMo6rN7XBE45bXPA0iT4cOK7Z'
    'aS9baodAPkDDLJSCUt+BOmz42Hq4CtS2iEPSVV8Bb5O4blwJ4aj4QQyAQujADwQ0HMB4jM/4fDJu5JkI4AIxfpLvdRumRgIuHRvgXstyX5+ptFYxLqtp/1Yx0jDNmlorOHQTNx'
    'CBfE+CH0yCB4ShJ1hEl6/3VzCh/rtFowMPKg1IATcccEEqDLul6LL1MFSCY5q5V4KzADDY+VFf+B1ouAMUpxUEwFdagDiIuGkhegKhWm5XyRVcweAIBEEIxwB0kqSfQowjAHNj'
    'H8XJq+T9bVqrr5VKtEYe5uLp55sLS0BNXNf5IjQtIWam6S1LharzcnrHes9+w6y3wg7UwSRMAhJs/K7v25ZHtmQvQf5aKy/sgti51z6kjqXVhx+wABGEIRf0WUGKm+f0lKZDVV'
    '58o1RukVollzecATDc+TgrgGtr+D6OLSHXjamdWJNcNY+qnCT9AbuvgUAAhxXQC6SXQBPAAcjY+/V12RsymMaKNvWpta8aZths/vK/S97j7vweDDn9mtLCV8QzfcWAsPpmtmne'
    'E6isrLpUfHl7t4IqsMMk2AHi6zoR7FsGcPnIx7rgg4O6tY/UHNRrQsqVe0Ad7MDMs0F/FeS43e42ovVdWLRPURWcoUiICL0BHHUpyEI2LHV1cuU7JFIoXAFGbZQiR/0BoVpZgl'
    'RIXX06F0ekN8EHwAG923ti5jE0WnNBkQgRc2TaH/RjNZxHik0PB4tA8SnSWkcTLuHdu+lfj3+rL83f8z12tAHGF/7hJz47LL4L+Lp+d+5XNJMKDYbUfPApGHUaAIMfeABAENmx'
    'w4ULatTaIBTy4gUnTvr2vMIwEcMrJvv2OczU/o9TJof7mPTwdibNKTyzZKVKle3ECXXp0kmQgC6Uili5conTqRPnzVg3cebMuZOnBQt/VKxZE6CLhHcjRvyI0AQOnBBBELDbsD'
    'XT1g0gmWDwNnEsE4uvzjJRu0ft2ldsmbDVx2Qu3IoUK8bdtyETQyEZkiXjNZgwr8CHk4Eb/A3Ct25uukXu5jiyGzdLMGeGPBlcGxetdrBTZoc0aXYC2VDjBaFSJczVlsCG/K1K'
    'BjYcD7AIAiREmnynTvk748eDlB1cuLhI2EYItYWZMu1ji1ftgYycinj0iPGAN90k852UJYvlCXjw0r2D0SVUqJ9Dxc0JOn/+nPg6z50Tl2SO/tE/f5RiyqkRdPjhhyaaMOAqb5'
    'g44Kvo9pqrLQzUotAiszC8UC0N2WJrH30+jGsPvCayaI+9+npBCCEOK0wwxA5TbBfGHKuRRsouc0O2JWbLoYo2+tmhDnYmsYMcckhTRpUd+mljtdYyg60ay6bIIQNPipCihx6C'
    '6A24U9IABhjiPKijleQMCsy55x4akaLq9jnAIU444iROtVhgAYg0fMNjvAjKQy+d9Yao6b1c7LOPPqMQhU+//JKItL+jkmLqnRvSKfDABM8IggUmiPhqqw83oKutPeCyiMJVza'
    'Kwrbjo0kfWWdci0SIQO2LooMAKI+xFxMBRjJdvhi32m10a/nusm8w06yaHHOTBMgYiijTySDuUYWeHVqgBhzXXYguXxymqiLaIGHpggSTgoAFulTSQIE6KOopwgY2EkqEmmRWh'
    '20BCVxvMKIY57bRuS+/OmCYNPBgerzwddBhBvS6GUOEKo+Sbwz6ixMHJgoyJ0i+J/TTuD6mluriUQAObQMGAac7whggi9vJK1K1kRXXDDCfKEMO2MAJJurgwcFOiDvfixC9qAB'
    'OsVxjbSIwXGYvlZZfBZoTgMWZ5dMOGHArw5AEGiBDDD0vQtgTJbFVJLgOtwa1GyiVsmEIEeVKIRwppzjgDmC9hOWWVVYA5gwYaYmCgn3uj3nfFF7oauq0D/gImmDvK02VhgT3T'
    'eEK8CMg7QQd4RpAABppsiuVjje/bqdGSN94p0tk1pnQNdFLGVFN+XJ5GDBZk1mcHm/+xGSK73qSOQrnmmlXWWiUqUa/r+nmBaV57NQxGqYWVUbCrh92aWa/BLsARvc1GAhhLVj'
    'iSnEmUISK5NnJYNkq5l8BnigIKeCAeacTgN3cFLnCr8EfhaCCNGCiiH57AV2D4FR0JVcc6chpYBTHHhDz1TWEL81NKWiI6iRFqDf9ZnX1G9qjXvY5195kdfyaVFHQ4BVMrwwMK'
    '+HQGD/SACMLLxD+gA53ifSVVYblL9MLyKhBd5EPPG9GI0NIWXClNRdfL/t6vtjc1xYAjMcGyGmXsx6NufM18jqAFAP3GvhWsQG12qMGSWtEGcHSjNXODTd0KEAZF0KIRNDiD+l'
    'ZxCksUEEz+YAYzGkGLeDSwcY57TnQaFMkDWCcGQZvkAbaUSc0tQGGemwVKVKIHiEmsC6j7A8bmMLv8nCNj9JlPfF4oKdvNUAIwgdgPeJcGmImhhxvYAXReAMR+SedfRuxZXtZi'
    'quc9D1Z56VmDprg457ToadrbXmK62MXVOAYzlxkj2MLgiC8Q4JBpWAU0YLHGNrItOeDYRRjxVw086pGP6Vsf2k6xgsGFiRLMEIMUaPGAdlwPghHEyFwoV8GMXDIkahFJ/roCOA'
    '2FhQeUIIxY6UpZwlNqbGRJyM8iVigfnAQiKBw9xyJodxSlNMUp6RhBGdCAhifoMmY040uKhIgzWPlMIj5DGl1AUpe4pGUt+rCOQ17Qj7/o60WGceo1rxksxTBGMpXoURm/kAdK'
    '8GkVsPDqGpHkRoHEERzcfA1mbKCGMKQgErSggR/8gIS0oS2Q7/JHGiiRhzzQwhEP8ARTHccQCE3SqHHixCTjNMmQ9GCx6cpDwviUj0/OIhURiIDo0nGDjKrglB+L1CJOOg6Rzi'
    'cQRgGKTiJ1UpQmwT9LCYAErPAUHSQgpjP1ncw6Asy+QOegydzZz04Fq+aZ6okWehVG/rBTvX7sildOeypUoxZdqQ0LjJMBpzjzwIytZgEa6Fxj+9b2xlYo552XyQw+bCCCAiiB'
    'AX2EKxLkek9LACOQuuwnARTpV8AwNYJdAZFCL3jYhDZ2S3kSAyd9I9lPyiICZYjYOySw2T+U7LPjEK1QgmKB95xWHKtcrckAFIDXxjYdZaAtP56wywPoI7eQA6IljXo8VM3YLc'
    'HtEKzYQlS1FPY6DPkrYLUXZMToi8j5itFUtTYZCOyiXOKkRQWYkWB0JiKdYF0bO1Qx3jbMyH5e258eGYCLwyGhNEayg5iAkQZ/TGMBzMgDAeLhVwfuyzmC/UrQkCunxDaIsQ71'
    'xpbE/hBAkiT4kyWwLMTS04UurIGzRlHlIsbRqKD45CdAyckqXwhi1zrlKV4oA+9SvAAxHDWI2+GOrFY8qxnrjNXBbWZxzSKXoDmkeqkBbHMHc00WFblxwjIWOKDlCTNmd7vdhY'
    'YgBPHdaylDGXVQBTdccI1dzOgb35jC/tqhCAbUgQaTqFaZSVM4XU5Dr1KIcwMPwpyFQM7UyL3OQu+EyYZmsgcL6NvfTpGPD8wCDbJANIS7EABGbzSVHl2ESEfbk5HCp8O0489R'
    'ALQGRb+j0z84Ago+sYAFbOmo+6hkYuNUM5v5i8ZEu7HJnanEFV8HO0m1NUGxaE0WGZnmvPK1FjPQ/o4H0IIW2pUyNKgsiCqDN0l14Aa0r+HOXZDrGtdIAQMYQAMieRt+zPZ2EP'
    'zAwTa/2dwPeLkQ2CDYyGXkOnI6bMirM+8C96BvJDFAvvHQBAOVYQTpsIIEBM7ZjaY20h2bD1AsjROi0K52KpV4MSgOlQQk4BMZ37g0pCCFS05+1iLfyh42gCpVGdFoq0oL86yT'
    'ES4Uwccvb1pTYcTf7XUvWPlqRz/QxwyFcXcGQR+6le3gbXYcfbxNb7oL2tEKbtRhSETKljJqgPxJeGMSQehbm8UA+XOnhg1gfwEXupJ9shPMTnuOJGMP9ru+BQEYBjBAeH6ABk'
    'TfHe8Dx1jDcZJw/oUHHlGwK3jhkYIOdDhDZSNYfOPpQOMyCfIkTwoqSSOCaIgyj8aORnqOKC/eIlYwwiM4gQv6oXo84cdOD6r25ZqeS008oR/OBYD8wJzyobu86vbIoX3aCH52'
    'jxtaYbza4TOEb9uKjx1qIAdzUB9qgB28I4ACLQ8i7wuK4AEWhw3Cjt36pSs6wnLOTrHAL5O8A3j8wPnOoDdQQO5+QAfSYQDurhgEzoQ2hj9KypUULsPqjz9SilL0zxkGxP8Y7x'
    'OmIQD9SRp6QBqIYJIGJrcS0CtYzfOMKHpYpagwYgM0gvRc7scOYgMPY9c8EIsygBpCcAQ9IGGAIQvOKQVXABbY/sd9wAtJdM/oYFD4hG/4VAEHcTAHVWEVV5EJ2MEDWKAHxCAP'
    'ekAIpaAIirB6rk8JgSi3uC/0KCeS/AyivANhdgMIDAAF8EAHHAw97k7gSkh1UGiFzDDDVMcoVieWNOY/VqoL+O8G4JAfPuEJgIDN6hDyDuBc+DCIRqVUiqho4LFVJOJC9kBWUK'
    'QCX4D0jjADYQ6qbs1FDCMSb4MLpoUE6UtwumoV0gZJ3OdawmoS2IEdiE8VjI4iVaEHdfCNVnEHlmQV9QH8YnFLIi8eYgAXi6AfsA/7Si2IuC/k7qSx8iQmYREBvMP5khEFfuAE'
    '9GAL7M4ZwFCj4q9jRkv+ekJ1/k6ps7Ix0+YgFiJO0WgIDtEABZ5ADn0n+iRvYIrAcjKCiIhrpzDkLlpFuEQliBhicfjxINASMRzxH58mGQQyK9EFFtXnIBVyvsrs2+7S27IlIk'
    '8RFVNRI5dkII7jH3ZgH3aAh+iNAEsyHopg9CDnMUutCQ+wgvgsJKbQwPLEG2ARYZARD6TCJbbAC9uv0eov/oLC7+hDdZjyKFBJlWRplmRCtgokpvAgxXxHMQdmYAoTz0LPVOii'
    '5KDoiESEK4CpCJDQE1KDHzMgIdLNyG7NuVbDV5wDJafFA7wh69AMGNQn9/QSB5GP2Zgt97Al95Sh6sAT+XRwI48DOZBjN4mA/t56IPLMzSRxCjIhhwscIgYmT94OJk/sLYBi8s'
    '+8wTuAAAiaAA1SwSXUYQuswCfdz7NGCzVRk6Q07Cg7i3U8ClLiYw7+Iyma4h3SAR7KQA9Ah2HwSgzu8ABiYEVXVA8vySXxDERKDi3g8S0wD0VSBAklES0VMRKdA18QAntWAwKi'
    'U03YICtn5jonQTu1k8z8QPewjBVXUQfBczzBDVvAUyO35UxcgD25oDAViwikYUwVkzFJjwsYIk3ZjRMqST8xCfwGVHPU5Qz+E3jAT4N2Ix8iYCXuwAHQI8IGLhY4StKqsScqFB'
    'tPCD/OgfAMrykGAB7UgR6yIRVkAQ/yAWbG/tRN9VM+peEAJO9F8SxoSC4iArFD9OGm0vTlJJE5fTTdhIA5aI4wIGBWo1Mgv/QAPMADJuGPgMEOzmASiOM0AnMgvnQgpjT5RsNa'
    '3MfMmE1LubQgwq4992FmBnBMI68kEXFFHoch8NNN7dAyM2cBgmAaChRmzgBFGes9vSEIzq8EUuEOhIEeHMDuigEdGm1QW4koc+EmsPEaLQBRQkYpVWrEIDUbDDYVZuFSz1VMY2'
    'BvyDT67PBTj4pgDNFfICIsaNREtiJXqggtIzFfIlERm+NHqWlWTTbXqCEfY6AOrPNJg8BXgdUbToNY0WS8zuRLLzL5lPVIiA5b3mhb0IQN/uzFBa5vIKa1BzwAgBpBGhphPmtN'
    'Wx8HOtx0SzwARQ2sb8pRYSTK3v6soQgUDmZBARTAB+hhQd3QXv9jUAkVwxbFX/9VpAYv0yhlxLYgUu9AARA2H9Ig0HoAk8RUFgPtHPs2Hc1OI+yE5MwCLdACVU4VmFSkOdxSTd'
    'CSGpBQR1MDcp3LZIk0MJCQG3aACHR1EpAAWCeBBV5RMJGjINpgdT3jTDgSWXn2u8CrWZeEC7RsdSmXDZBjA2bmPWkg0MaUAJwWarf1XHAVgMRP0Dang8ixHDduSz5yXUMgH0qh'
    'FMaWHvQAHt7BGexVBbJxKKvR0v71X09T8DhKbj30USPV/gcmNWGB4AxY4D3fE4AOqX7zgABvERfpBDo+4kNybCKeaGNThLkOY792lA084QWoL0idRnOJlBckkQu4gQhekXSfdB'
    'I8YGZi4DhUd3U7g3XbU2djV9mQJCIHQssYxzN0t1hBF2nFgAbyYGkZ8wKZa0V0lxPENNAEjYMgq3M6x7bOdUtAxTtC4BQ+QGzH1jzSoV5DQQxbCTULlT6IEpYYVQUsBR5O4A58'
    'IBVKoQSsImYQE3DPgBKmgRmgzxbTUX8fYE4OKlWW50T4wi8cETFaFQlfIIFfDnsc2DCooUtXNnSpDoNnZgeKoBWElnWlKhk84zNWcTRWcI2SbY1yD8uA/lY5cDchuvRLe7dq/Q'
    'mGpc84p6k5wI4LPFUWE0aiUJlPOukJZkoORS2TNAgB/iYRSkELFOAO7kAHbgAGxmANmnij1taVSEqKC9X+tjEpYOAGdCCLVaIEPuAUQgB45k1dZG8ayPiQCPALDsBM9bf7Jmgt'
    '6jEjUgRzmyswEiIDb0OBdfRVeWWP3ZINPBd0A1mQBeI4+qEgLLkNfmR1C8JzPcCRIVnZJlkgkiOF+TmTBwJ0X7hqxaBpb9EInQMthWD0tIQZxriD+ESX+OQJpBLjtvZ5GUsMJq'
    'GIP+ADrLeyIoaXh2Dg/sM09bUaOwaKPaY/auc/QmEIknkETmBPS8CZ/g3AUwaUCP4soiQKr7bOWm8xHrCDcBNLQnQGRAxxnGcO9dzSOez4CG0tamSVVnnBNvrhj72NOyFyI5HD'
    'kIHPE+ShHaIlBdg6cRrBA+JqFb4r2cJqZrnhkFdXkVXYdoVkZnIVeG1xhiO6OUQwBugXozN6o32YldNgFCSKb/uT/E4hEXra0GZrl8dgpRlNBRLupV/JNEkLUSFOBW56DGDA/6'
    'Sipz9AQRCAJtUiTjkIlcvYzfBXPht28qAJmpALmFbk9HJNciXxNoQ7jzN3MDIgA/qhFWIgV/3ADkYXfn6WPT8jBbItBRwhEq47Hniuj7bBH5DAH1IQbcgsV+uAgw0i/roOulhV'
    'AXQZGoCsFReNkPoKe2+0a5XzYabwm5VZ+RMam81EDYDSpQqL2Ig/oATkLgF2mZfHQP8CoFFkeuHMMKblD+KQgrSHwLQ7IQH4YVOs4ipc+7Wn8AzK1Xl1+H6RWj4xKcWhaWJTxH'
    'qm+gMPwhOEoIHUOauh07hDcGW7jcySRBWJNQYVoQjigQd8gRZ8wRecIMlxoAK2YQL8IQug3IDgiziI71nzmnULgq8pkmX/GmJHMhcvUASzRBqqmZXDw8wZu5X7m4y3DkUDjQWa'
    'LwRIGg5ahh8SoBMS3BncMJjNkP5yooVEiimv4HbQoRhgIJk7gXdcRkGwAgGeCcS//kPEYUbjxIAZyPx+Z/EONX1wEWtO+qJ6RBkxrClfYrxyKZdyH8hpjhu5z4UGPAC+kAAUla'
    'R2bbcIGIAWSEDJcQAHNEADzMAMZCDYSYEUJiAL/MG7iYMGjg5Nrlyvs3wHuIEic7Vq7dBaPdUkTbJhyVz2niA8GIZh9HumRqG/HbvN6leH8+Rl5TwE4CAZ7TwBoCI9vNClo5g+'
    'YpooekKGiuEbw9FlgKDRpUdD4jTd55ROD0yHRU2HUdQOOd3sslK5RhZGrKlVT93U09ItV11ssuSt5MoSeNzHBZMbaAEXKgAHzAAMwKAZGOEWGGHlW37Yid3JD6cOGIAbmD0wuA'
    'jL/mMw2odk2v9aJCXvCziBCDn1kChBv7/dc7qdlaeBKreWEjTukBL+d1igtbuEXbPwBxIAYs5jC7ags1MzKIa5pFBrJ9iwGGArRDXF34OgRCKCcV+FImJSXTSHTrd2tv2pDu8w'
    '8ggXF5XrjiPeHyeX+oT2Xjz2uEPwAQzbD8RkcMJKFQOTG8SsAk6+AWzh8jnAEDjgEi7gAtbhFkgh2LfhcHAB6u5ZORI5WBb5S4fvFYkErllghziuAOWTvn2Olb896RlbDvGKza'
    'DejM344OE39r0BAXTD/LSwJSKVD/jAwQvV0oAiUTxqZJYyFm6nGAZgANRBHXb6B9rd0YsG88Qf/i7ifiLm/lztzd5kL2HOwJ8gNj7nE77pRIFlHMh+BTAonvBPnUcTv2EDDZAA'
    'wpIlO3aU1VCFkFsdGhXMyLhlqxwHUBSPcSh36cKtWzK2PauAi5YiRS7ktQGXDJxKcG3auHDRipuqOuw8TJrkx5sfFix69JDyU4oUadLyiGHGjNKnJ0/wPEHTlCnTaWkoTZu2AO'
    'uCBczObF1wRowYFt7KsggCxECTHxFO0KMHIG6uObnq2r17N9ZdceKSJDnHN9eVNcWsDHCgjt6dVCXgAEGAYc+/yf/26LPMZA+TzZsxmGUhxusZZlfPYBW9QAxRoVLiHXhQpJ9s'
    'NtRqJ7uNO3ey/tq12fj+/duTbNjxeng4A2yV8oGTDB5URYPhhIfljlFsQRHUsWMZOZoxU8EJrXgkTa4ExwslSxdcWu2gqezmJDt+EEzq6dOntB55pB1NOs0oaUj1BApSpfHJVV'
    'ctAMQZDjpImmmh8VSWNwgEYQAKTURwxx0+xCXXXCLiVVcgduk11xx9+ZXEHBaoEEphWzjAhzCLNRYCAntsQNlkG+ijD2eaacZZD970AFpook3joBgLgLZAUay5VkSVs/GGGy9a'
    'JsNLMhncxhs1wLHxgmz9VHkAUKH5kxwSliBhR3Ps1ESDH9tQN1EL2GGnXTnl3NKADNaERwsPirTjyUkpaaml/kotxcTNnDfZAScSSJyxE2j89SDWfwBOI5WBTCGo4FUNhvVgqg'
    '4+SeFZacGxoYcgxkWXXbXaZaIFuaBo14rnJCHOHIGogI4zA2zBxzIA+MAYHEFgwESPPu7DBLXUAhnkAZvl16lYYT25aqf9STNlDLH1w4Yn1OTW5Za4rdubby9wQS8nRXDCiVA+'
    'YQpMv6tYepMfHtS5zZ23XFBOdnz2uVEzgj7jREjxpIDoSeih1+h6bHCzw5wEkUOOJcDYEQIwDzrpKVLMLEDJKKWmUWqpqp7Bgqqn8sRTEGipFUEqss4qojgkDo1isL7yZcEV6B'
    'RzLB/0+OCDAjhGNlkmmfyT/skG+1hbLZD7AHnAAfnt5x+SONNMc2pHGdWIUPFY2Q+Wt23J6LttCCEmG1y8kMm9aabpk7f9+mOppX4gsQ3i062DsHULg1KOLbc4bI1HFTTSCHkP'
    'uEBNGxlgzGh6Lm2sCjvKfCzQCpac0i8w0zSIVcpfZTUNHVjVnhVYYDmoc+86n+F7EMDrnNZaHN4xq1y3Dn3iXir+BewcsSgtgRU0LsvsB3CEEBmPVl+9wQHUir/1Plr/uHUMYQ'
    'OVn9k5687V2qtJcS5t1HzZbui51SYEmfVyEjax+YQnmDqDpYCBBML5Y4HTIcXBqpMdinBAcs2wRuWe8QxchIQWDBhJutow/rfQpScZL9kBN2pwOnKsYIUrgAUsTnGKNMjQKtNY'
    'mey+4qT4ocwrwvtdyRAADASULHg7QwEK2BKBtyQPAHWhy/LyMjS+sChY01taOraQGB/cyFk64hHWsMaJfYiPfOYrH75iwIkYqFF9YduMN3AWBAZdRWWNINfbYqOuL3FJhO7aDT'
    'X6N69MAFCA7nuQHzCFBD8wsIEb8ZNEtMOBCW6igtbAoAZDggsGMKBKraANCEPIKEe5YAelS+EKBSEIWEADFjPIggxhpiCkiItTeWBB2cQCGgIGIQS7zFEIQkAyIQJxl2lBARx+'
    'wBa3wCV5y3sir3JhoroYzS+Akd5gnPEO/iy+ZTHa4x4TvPe9rQWwfOYTJL7sVaUqhXFrbvRG70pFCVk24gBvS9e68MfHLt0Gb77hgiDFyASzBOEsmArC4RS5SAcyzk/WieQEbd'
    'GMCkJhGLjgAQ80qUluFEGj6PIkKCGQHnC8RCbssIMKV4BKQQggETOARhZeKsM5isUoeWjffsTAKU4pCXhA+KVPfQnUEBggQ03gxw9OgNTE0IgPTOVD0JjXPGjORYp+CQyMupBN'
    'ByhmiwNlgj6uZrUNrJOc5/weF4pQJrTaC19f68xAQwAE18EMKauxkrrWlT9egLSPuwEkvg5ABCOdZZfAQ4JB/YDYCSxuoRCcSCRtAVFr/kw0GjwwhhJacdlWaLY99PrNukAZ0j'
    'ZoVhU1MOkpVSoIVrDiELPIQj5IkYYJMCk1+OkJTtvnPhYAAS1CDcEpfPtTnw5VQ8j8gQ50oA4sOmBGDmjuiKAazV018XksostgsDoAeGyTMSgIAQu8uoHvhXGQAMTX9zKxtzL5'
    'ph+BzNo+NIOBCxETlqOhgTRiEI+OZkCP+XTXH6kxryIA9I06CwFygBGERALDDxPwxwRIwbhLWCc7j50kIlxBiMoqQQnX4PBLNrsDenGBDUJoA15DB44MiJaUpkSlAF58iFLMIA'
    'qtdaWCwjKW9tUWSTh9UFqGCocgw/C3vx2qWlBg1OPq/mAL8NjCAI715Cc3UURPrIsFUKSrqVITWLsKRRckcJjE3CECJejud/fBifCecx9+u5d5M1GmF/wGXS/gW9Y2sIdXYAAD'
    '7wwBkyihGqFUyRPq8lLo9trH3rA3jWIbLDCA269ELtDBEL7AdkCxMEnW4sLRIIYxRHENe1xj1NeASStE3FnaZCljInWBQkqqQhfD+BCHiAIpsvAEGzsIZ7zutS7PAIQfw8GYQS'
    '42HAwQZCMaNQEjGEE60vEOK0h72laQQJVJhKJYXFlXc2DRIvxigT8Q6x3HEnMEImAAIPSknGH96znNW2c5p2veZOqH1f6B5z3s+UK8PNlqzIWu2vA3/p/vAvCZBkngXQKDda0D'
    'BgMrLYlj6AnToIjkJjbtimgYgwqisIc9dgHyUb+EPVwI8YhL/FkuXcwlMamDMtyEUgGwQgC0rnUU8ECKJ0wAZsCm2UB1RlAWTKKHwvuxEZuA9KQjHVZN0BA/EsDsEbzjHRKgug'
    'S6gPWsP/W5UNS2Bbjd7UV8u0UWCAU6wIyst0TgByhQd7XOuwO2lpcTdc4EmezHGzLZeQP5ji8C5IvjQAO8H3k09B5FWHDh9CNfgvWDb4e8OuX446UQLsQxBjFxCW5iE4gwRT3c'
    'QQUyeHwK3wA5yFmO6he4wKMXS4+KYRKpSbhpBqqtOa1tTYpbv9Jk/r3j5S57yctHP3q4Ti9ucdeylqdDfQQ3gIEEYIB1dEgfHaFYg/VHdO1A6ErbsfB6t5Mg9m+7SAUBQLtW73'
    'CCMgOhB+I7rznxVYRM2Dvef6SN/dnA3rDuIc97ji8GcOYTB2AueHQ/XjI3h6dPBScbRRBASJJgIbA6lgANyvFSWRAF61AIkoB5eoIdktR5xOAO4SB6coAP+PANblB6LfESqOYC'
    'qtc5t3EeLtEO3BADdXA4q8BKM1Bz67AOuScDTLFzPRVcvmUARAZcQjVcTZcAP5AASnZcEaADyKQDzHYDzdcFY4AOQ7AGoRAKKqACV/CFVzBlvUIiVxYLf/B1FjAH/t83di6yBm'
    'd3GFpFD2uXbuy3D+gFZ1bzbnRHfy8QJupSd5lgPvvHf/sGLd4QNmgUG7zhOQeYP1xScNSwgEXAPn4QBP0CQ7CAgzOwCjMWBYVQCBuYeRxwcZ5nBCIoB/eAD27Aiii4C+tBcvSy'
    'ei7QEimBHinBcgpRJ0iQBTNWa4ewDlFwC6QQKBPwBJTwSsB1CsW2jMz4Ac2IdMrnbCMADzpQjdV4XM3GfDCAhUPghVfwB93HfdxmK8yjF9qGhl/HhmLXIuJWfseiVScQAWiQBg'
    'vAflZTd/70bi/Ah0Lgh7zhCf0jG4LEd/unZ3q2Z5sRNmhWBL5xV3rkiJCYgLsh/hywIQUHsB8s4AfAIBCn4EI5GAWfGIqiqCeSZIqaYA5qoIrVsARLwIrfwAu7oILswR5swDkg'
    'pBK26BIu0A+6yGAvFZIX6EAyQJRmMApm8EpFiGzN+AFN6ZRP2QR40ATL92zp8GRbgJVNBg/PJgESgIVdeAVep4YpEixcxzzbJpZr6BdtKG5wOCP0gFRN8AT2iGbxlofnFW9+iD'
    'd40xueUGdsBSRMgAEHOZheZT6csDdxYxsoAZESqRu1oXhFEA+VOAmYaAkuNAOZSWugSJIdWIr1oAlkoJLVQJosuQTd8A2iRJNcMIstgZM52RIbEwONQAMLRAq2xoMc4TC18B3b'
    '/jAKyAhkQfaUH1ACJfABpdCUJYB0P/B0zDd1hhFlUDYAU+eV1KcC4chtfbEif0FluSA0eKF945iOalld4faGhoFF6pANaIAHQLAAYTMvdsk3XMBe7PUCQsCXACkmBxdG2kKYhQ'
    'kk4WU1ZMIbENkuEZl4/fAAjpAmQHEcSMCROJiDNTeSy8CBnokIhGAEmjCapdmSpwmTLDE6rGmTbOCaMbiTXMAN0UFpF7gODUNJOCCjLSNDwpmcxVmcpYCjxbl2TOic0VY91WMY'
    'Q1ptWLcGXqgX3+dt53AOizCGUJULaZiGa/h9a2iexWAs8KAOSMV2WHEA9nKfeck3Y3qfARkm/r0RZ+vEGYL5Cq+wf/rAbnUmN415gHUKJhVZBF+AkZyCWBBqCZuog4fAmZ1ZcZ'
    'tgimSwkh7akt2QA6+4k7PImieakywhJu1RB3WwDf4AYQfzohFlDYgABYDwDIBACXTwCSiQD0iHo+fGqj3DqshEhTdwdVnXlbVaq10QAOjgheqopOEXfrdybc0jpVRKpeFmdliV'
    'DjqAVGiABihgj/RTZ/jpj2IqZ/7IP5C5ny/gZgcQJILprZmhDwIKZ/dpG5+FEpDomAlqkULhAWKAE26iHJkZqIN6odhhC5sGmuZwD6VJmi1ZCd+QmlWggjY5ci7REiuRDLHJBj'
    'sQA3XyYAsF/lkWBgWuAAhOAAgVQAcFshYl0KrnJo9QeG5ROIXNB30BYLInm3VZZ7JeOJ7etghNKnbjkCJkCKVNpIYu8nXiFgpDAAPvMALHhUxtFyUHgFb4SWJGW2ckZqZnKib7'
    'uXiD5EbQAi2WwXf4WK0plww5wC526kcVGQ+TSRQeoJGFE6/zOpL1OkG1YAobqq/8appuAAGvKKIvYZMGe7COkrB5swM7QAMGgzB+YgsXZw2u4ArD4AROgAqjcKrItHYnYFxK1o'
    'SQ22wkO33WZ7lrcLIBYH0si4bkCT0vC7pO5J0kEl3SNBdqmIZ/IG5rMATPlw4/i0xyCQTMIAWcEHBhgp+9/iEES4t36oJ/2vpX2tIDnSGYlmE+4ZW0WEKnB3qgXkINeCoUGCkG'
    'HuAHlYkEytGJvjiSJJm2a8uh+MCvH4qa6SGwLdE5tHiiFpOwydA/9FIHHkAJMrAOlyARmnZhruALvnCxdNAJSXYCTqiNrxvA2wh9WuiF1yluB6zAqtu5avl9vwLB50AX3wmlfB'
    'EsVpqzf2B9Y9AFMHADI7CEP9B07sl+sWE/JmZiYsKXu3um9ueX7OU3wssE3wUtmwGn3yNnvMESuoGg7+K1aRK2YoBYh2MJ/tBKISmooXihhVoLGhoOagC+4esG3SC3rmm3KNwG'
    'VYC3LSEE7LEDREAD8csI/vWraRObv76AuPzrhPCwldD2DlX4xlMnq843BAasulKawQycjje7htoJLFXVIk9aInthwRacsypgfejQwR/chCKMAp+gbtJAtPYTifrZG0y7Xk8bQE'
    'wwvDS8GV+DZuOKdwaYJQioTxnwvAqap4BjHEJ3OJayCkYckpY3CLXcgaSYoUYgmlHcryAKDo5qxVZ8DSrGEijBP3rzxWKwDaQwxo8VuIhwYcNAAroACHTwC1CXDmzsZOlQbVfn'
    'zbbaBUOADmsQlrxKrBiMuul8ziqiIoFRK87UK4UcGKqLyFh3A+/wukGLAunWE0Sbw+vySfASJnjnwmLil9sqwxjQAwpt/sNwii97Yz8qlhL8JZHNm8rrKgVEML3H0acLRHkXaH'
    'kTVnH3mstPzMst6YqOEswn+jkCK6J3Q3Jf3LcywAiQJUmcN1GGa7HY0AmdQI1ONgDSNqvS1wWKbNTSR87h6Llj1yItQqxmOTSiC0XSZcFMChhCEwuIrMhV97pRyHZtFwQBiFaF'
    'hhsgxLRnbdD1tlZh4xMznJAKeZj0mcNmvbX60yWojKeuQRQ+Qb04cTgePQEuamnboWmeF5r3sK8syZKoqRLXsNIWYzErwcUtWHJfzAzbAAYNELGbVwuSBQUQg7E87QVW+WTShn'
    'W5ernTN85HqgJJupbsyNTAcsFVlm11/vFMt3JlhGzVgZHVS1M92Qy0I6xuPVCXrPcufvS8TTtvtcE52bp4m7zQMxxQNrw1iClndwVCjclHPqzK0bsf7eoN1PvXDvZgDvS3D8V5'
    'ho2oUYzSpafStIi+ka3FO2xiq0cvX9wIzNAQzQAGm3dxnV1JH4ENo/AGPm2V03bam+uFR3q5SKqG4mDVizAOEt6kvyLbQvOd57gr55iko2sX25bbVc2kfNF9b9gFhgHcsZtuz/'
    'J2OTzRE23JtHFX1OAC6uK7snFOCc0C/aeQDn1WvtE5X3Kujlk3d3omlAgUgdWuYjvECEWUDwERm6229bChiKrY7f3LBhvfJxHZkt0G/v20t0QgDQzxDGbwqZsG4JVTOUY5CkfQ'
    'bESa4NeJwOJG5wisK3zBpONwDuOg53o+4hfePN234YOOF3qxbU0E4VYNGCV+dui5pWvXBAbQVcX9WXr0JSls0E1L44z4vJncn8Irtd7grXCKZhDN6bqx3c4riRYJxHzNAu2KWJ'
    'RQMP5AlM0wOf69aYfaoUtQDVOcmjP5EpJ6Hu99VrNJmxVQAc/gChNrClDg7FBQOYr1BKSABgkw2tx8dStr51Kqx3usIlbt534+4hbcdbtiIuI4NCDOq3+x22dIGGi3BUi1dsfG'
    '4siLN7ihtSp2P55gf5peG5je6cALQJzRf54B13H3/uOUnGKlnOqpLJl/w9dHIrZCTDDb4BDWEFHNcHGdRwigKZr3wOsf6t4itZMG69grEVIJu3oMMJs0oN/h8Qy+QAgkQAjRMA'
    'zD8Azb0ECzgAayUAY6wM1WEOcNXKzc/nXeieeKvtsQHhgULF2GLujPJF1oue6KLg7TswZfBo+P3hiPgQHmE62fdBtfApnA4bvJ3TnPyzmL1p/dWvCcQeqcYHcvoC4mBoMM37wU'
    'eeRCIQ2BZRxj0a5CfNnbUAEWZA21gOadR+WHva/iS8WwOHLoex4htR5FoAjHXgE48AyT1WkUQAw8QFE6H5KlkArZ8L/wUKSae503W11OLaVkKc+x/t/0uGLbTz/IeLFt3s6GTE'
    'oXiFwYWz9mP8BF32Q1+JkbOQAO92PQ6gXk/34/KczvT8tOglnw0BL3ffPPz0/KprwleL33e8op4Q34R+HyyL4N0A4Fm6b4i6+SIP+2cTu3L0Hjd9t6KOESRUALjYAD32HmhUsM'
    'FAAQVKgoocIDl78JM0opUJDtjjp4ViR0WaPij4U5STQmWbRxzsc5uULmyiWupDiUKOeYJMmS5MuXgUjGgjkzl4VYFi5izLho0bkk4ixcWdPFygAHDuidiNAEDhAWTDZkeiGEWj'
    'KsvJJloEbNExuwYLuO5UotgydqbF7048Rpn749TDDMncvErr59/vuKcHkhtk2yv1iTaSVMGGvafkXiHZDSo4eHHmIei6FMQwyNChWePYNiDQoiU6bq1TOiSY2aJalTd/sGDlwb'
    'F7Fly2vTxjU4Xq4Bt1LUqIIZGTLAWHNFgliccJhEKWGAy0+WQwx9+KAHUWKAihYwavTp0+PHmzXFjx9Pk7zMmzl3bufo89wcCyrWFDu6xYE6pk0MAMEglaoQIbLaKpmuPFlrLQ'
    'O74mqrsdgwkJNM3NKHiT0weIUuu5jIax8uiujLkzbMEkwwXko08TCvEmPsAGkcE8MbFlgQw4PKaGiEBic2cwWK0EQjTRMy1LhHtW664WWX2mJjwwVPXKCmNtdy/ssNsH5oaQQH'
    'GRpooJlaoCDEnTjMsUcEEVrBhQbotFBgOgDo2cKKLrC7KKP2fBrHu5TKy4UmPsUzzzzy/MRJJ+0+4oijc4T6IwCjkFKKqR/gCCKqTDIBcESsuPpKrX7UGsusqwpUay+39tkjrg'
    'tT7W/CfdrKpNOxABuxsBMP6yexIqRobDLJaHSMBmmkaaQRJ4qFYsfQCPkxSBtscKPIb3J7DTYX2omNNtuSwW1KF1qJx4lttLSFS0SicYfZKey5hoHnZpHOBwCskwAdi7brbpw7'
    'xzknUZNcCgSnPQPus89ACyZp0JzY6w4onYqqL6n8UJhUnw1eqOqqwTLtio1b/tfySsTDyho1k7z0gYsJVTNk4oC8OOmnr64Cm3WwE7UqMLEYGgtWMhl7fYyIYIcl9plhjjVF2d'
    'I0waRZaI+cVsklm4QySm0Ba4eW3xpgxBZbakGkHqXlsOGbXdphgAZ/FmKzzS3e6YLeOblbBF989+VXJpn4jGXvvQV+iSb0AjZ4pkF3+qg7n0z6oygJBrBPHXoi+GG/Hg6A0CpM'
    'GTRQLQPRuiqDATd+oYgI99lgwj1eQZmu/jTcJwZOuOiUja5kFdDEWgnkuIicWZSMMuAlA5qIOupoBJehd3TFFUIeoSCOMAqYIodoW3MtxNiajK22v7YFZzdanDCjgQvGbcYU/n'
    'PJsAEffHZZF21314TXzXfmrZdOO+ve1yWS/v0zPID57W8F49/BcpIw/M0NKLlYXKMed4IfTG4B3rAcF6yCMa0QaGMv64cnrAK6EVFDCGspnclOhbIKVUhlLGvVy2h3FZndrmYa'
    'vFURcqWz4PmMCESIQR16WAfkbeZYrhhGNLDQi+hVYRdHklaSqJU97n2PMK+pUgXCZYvyea0e7jDH+r7xjWsoggZpWIgCAHBGN6XjbdmxgNzytT9xBCKOuUBPnwAGKJjgkTwhKS'
    'CftCMS7typIw3rQuPs44ATnAAFKFgACyoohBBhamMcAwtaQCgYrqgFQiVDneouJJcVWo50/rB60sxwRzPBeGV0vZOGGFoZvB7skAg7oGUPh0WDzeAACsPwBQko0IsCFCBKt+Ee'
    'k4zpAu5pa0qvaUX4zHCLW5ivXEpTgxva9740xI9NbhrARNbwhz8YClH6giMdzUkwPQ5QneIZSUvyiBPzZOQcc/tJEhi4hgAYcgv4+QE/gLCAynGBC2wI0IjKQo0PvRB0tQJQP0'
    'pIIZRlSHWtWxkLbfih2l0yY7jLYDK+gjMpBKuVC1gA8H6mjx2ogpbFu9EztvEMHBCNBJFIQTvkUYXbXK+YsJHH9ro3mO+1oR8MaARwGAHNLkWDCksbmwjC2Ah/aBONW0jHvNZw'
    'hbhpxG4o/jEnHQk2OJsULCQjaafgYrEScczzTgxroD4doAMdNOETAJVC7NgQyVRuzECk3IphMjDCF3DidBOSyysMC0qVraxVnFjLC2tTNRnmDjE2ZMwrmSGGkgpvlrTkbB1ogJ'
    'nMbMYJjfiCIlKALWJOK0k95V73cKOtNnirEdsY35aIEw1NxGEKU7DBLuRxtjTgIRVrAoAP+ACPbr7NImel0/4S1T//AQ6sBuMjScZak761JK30ZCs+JWCFLexTB/38BDOkIYUi'
    '+CVUGkQoJb2y0FplwGISopCFIqo6xB7AdZy4qFjWa8oSZWwsuNJVZPKA2ctSZoco/QdnVeFZzGwjM8Xi/oFpXSCP6+m0NrShhmySWbXasIGovwmONXDgiiMWQA1TcJ/ZxDCNWQ'
    'x3OtWhqtuGcNVCiSMo/Orfnvb2L3aKRMh+ChRZsRtWlMxznosISVsH4Dh4jBcFo3BlDNLrAkgSKBkBsoqDXvAVs8A3gwCq1OlQpqr+qC4uGmJZWxhLyq6AA2RZKUwqd1eEyvZg'
    'Acw4AzMSvEPOBrp4n5VwBWhAC1oo4gHtiGJqnXjhJ0URtrBRRPisaIaYkoAHSggDmVpMizEKl7j0oAc8qvq2UIATIygJCld9zDfBwcTI070ueEqSR8GxWslBIWTjkAJXNHyCDu'
    'a1MlhCFJgGvQyjYh7z/nxNJRe6fBIDa8ZLy1xmsQ7GLM4yo1UGNxgDxkRGDMyYxgLOQJlY7mMHAuUCLR/8WXgPK9H9cFIGMvAafLcWmR5OZm2o0Y4iWIkZmamAE3Bh2ms49Rph'
    'jAEzghuBVNyBOhAZgI2vOidW5ym6ewugdYXczrKShyUsCblNZLKSJMxTI/BRAaMMGeXxfmIaYkDvlUuJOVXuVSygy8Ep/xohk0Gbdfg91Vs24Ko3V/JjIdLoDGnIFnC/0tzkVv'
    'BmM9Hudu+geB6INy0YUASbItM2+d4wTzsMm9YmiQ2KCPiwRkuLeCgiDAuvTSu40Qg/ZDMCCrgDqSHyDreh46o5+YiO/lVyE3hyXI/8K7l4Ckge6Wp3I0GZwx/k06h0wOMECeDH'
    'ExaQhwMUgd6QLOWnOMUxBWXglFue7wbsciHW2TcuGzAdhLBdSdo56VOzCrBW/soGG+ZM3NOg+mXTjXV2r7QOxGuEDxlAbxdkoA1VsI300w6iCzsJmZGWDdsZgGgpeF0RrdhebO'
    'xOhGnoPeJ3OIE6qDqRG6uAJig3fEi0o3gLyFr/BmP8kAdXeI0QB/hYHHT4rsyDqx9AgfKSgmK7q7+oHVWipJexJDoLMPkKrNOBvdhTM4qZikqxmL5wEK9AC8+pHRIJMA16kKij'
    'jDNYgHJDtwOIgXV7AXbLugfzIW6I/oFWsJYLGzvbaAPrwz7YODvtQybaWRK2Y7t4KIIdlA3z2wEi8IA0yId8SIX1Uwd1SIdukoAhCAWsEglWazX40I6LSJj8c6dA6Zdbe4myar'
    'xYEwmQ+AjtUIFQKKR3SAcEDLZpyIOae6H1apC9+rILUj2GEoJKeQuhQ4BoO5UNaMQPBMF+SIuvaJISNEHD8DaEsqEdiowWPINpODdp4KGr4wIXYIPk2wFuQMUdaAXogxIgfMW0'
    'K7t9S5J9cwF6u5V+aIVWAAvZaAWBUgUi8ANgyIdZkIUrzMJTQ4dUywld0zHwuD/t+CP/m641vDU33COQmMMrQIcxkIARwEMpm6se/kCvF5KVT/mKxuoUCly9CxQsuKALBIA9Dn'
    'REqrAYB7nHSYyaJ8EYmkHBjaGsxhCDTjQ34YkBgeJFF+ACX2Q3X3RC7pE+sotF7hHCDtO+DluSI+RFGmw3VWAHYSRGK7yDh4CHtpGAMRA8+QPDjVCJASQUaURD/nuJAgqJr2Kn'
    'sYpGy6vDMbiBERivCEKBf+oB/qKdGGoQL5vAD+orFASQwEJE1lFEC2FED6zHqiAoEpTEIzTBfsygTBqdHXARgSQ+UJQGGRwoUnRCXyS/s4yiH1StH3TFt5TIYzO9NgALgUqpGp'
    'gEYDgFYiyFiEskeIAHwEO1KygUrVq5McRJaWy8/sCpCZMwsrJKJzUUijEEJzrkRhjgyQSIKwWkK9EzwT/sitmZHQpEJawALJIxmdibi3n8h0esCs8RQSbRR7ziKJuhhn7gghiI'
    'ASJgQYE0Ph4SKCWhxSdCu1hUrWnJKeXUMFeUlRARoVK8S1WoAQRAglOYhVmAuBMYyXSQiDX6g/kzvACUw2hcTJgsspoAOZGoyX7hqgG0zDXgRgngSZ9cpKA8AFjJnLHwoE4RRL'
    'Q4QW9ztqAbOtmjmEqpRyF4Ic9Bi3skiwpEwS0zRTwLSMw6N8pgwHVbErncUInEt9tgol1wjRDNKch6wDboC45UBW/QSyqcBb/MBsBsm8ALBfmz/gBdQ8zELM8zNJgz3FH1VCdA'
    'SYnD0wnLi89C4skRSIAfaAKgBILKET0hAKGOYi+xSBAF2SjBACx3XJ0NlMp9eESC+pQC6bBJzCjbRJFVAhrgsdBYoqW1lJmgAgwObTQRZSITgYASWaISwY3vwYrnVIt2+4ca8A'
    'Bg2EtoiLFUSCSI6M6JEDzw3A6gAIokIE+X3NGCyT9ptNSR6Jfs0i4htb8idbl3oM8lRYH9YIHKeRlmyyuvCIuP+RwsFSFncz0uhT272AOT8UB7tIoHlL5WTQuF2spaSYvgOwBx'
    'Ax4P4KF186nl7FM5fRKHpNNt+QYI6AYIoFZq5YVoWSJiagMh/ohOjvQGDwiCYcTOVIgAGD0BknwHOEHJP1DJRKG8HH3JahQPTMXUMZw1moy1JEuU92CgxXE5CUgHPIwgpwCCSb'
    'GcFxARjkKRLtuYK8VSDbKY1JwQC2FNoqs2COELXsWY55wkz5FSXsBTfyTWqDtWyNgh4UQmbdmWPdWpiyxFJxS7Os1Wa71WPCXZlwWMizRFWtIHdqhOvjxUK0zURfVOR42btEq5'
    'IYXG8ICJx9PRaIQPNry1vpGJlNgqAYwPfCqkAQDHptAPAwiClWGsqzhTFIFYBeHHjpLVEkIVC/kk/DKZvLg6mOFHDarLTQlZYQ2wDeKdxqCRXiEeN6VZ3NBT/t0IsYSsQfITu7'
    'ErEWrFWQjA2W0lJiW5S1qKwjM4gyk011RI18C0AjjBjhpFOTja2vt7Q8d8iXuV2o+Tyb45w37dlya7vO9yHB3IjyYIgRDojy/FoMkl2bQV0zkzDAIBLNMhrIhKs7iIiwPQB1eB'
    'Gf1sVXxk2xIRXqwwEE0MqcfwgFDcrDcdpiaqyxpcRYVsXMN12ZGNlpe9nss9RSJwDD+YBr70XKM1Ne8kXcNMOaYVQJsYGJE7mNbVUY+jyexKsrTan8pruUICry1IpAgoATiQFA'
    'RggtixiusdWcn6lAUhkYzZMoQ6xH2gkFRRIfxiAo3lC63EpA3qi4VlWLSd/qzdjF/ISFYiUCl2Q6blxB6FzLpAS0t+G7sPVU5qOUXOIgIW8QBP7NwYiwD2U9c3Gd2KwDim5ReW'
    '0JvxUEOYkFqMwIiqFYdOzdqt0gkG1icIlmDe7Y+KCZDrnVyG0iAtg1Xj3bIRettbnQsTzpCWoQpLbFuE4iBBBJkz/VspGJ4a3qE6oKXGZUtqYYNWcDdViGRVSMVU1EXyawVKlA'
    'dqkAdPyABOrpbc5AJKTuTlAxpp8AA+SwMmLtr2M7XkkhOl1dq/+Z908ribmNfynEZYawm7UWDLCwD6cJwHZgoJhgMEQAAiuOA2uFOdFYy/CBC8ldjjfYFDDDq5TTOVwYvY/nnh'
    'rTxNjgksQA6zfsRersjNGW4RD0hnWUpFhYS+JrEWu9O64mEHeq6DGqiDSU7FGPi6uCsCRXCEB1A0JeSdGGgEoIEMGuiBYAEWyqCEacgCYkRU0GXUOJlintgqHjunWq7Gm+TiHs'
    '2jPhHjceC1XzYK8EIkYoaDUwgCBKAYC8qK4M2dLdOyAdmojrIKanZHi4W2a0Zhbc4EgqrATAGswIqQAxHkhtUdnOHNx+gBFkjnWGJAK1OE8esHtvshImAHZWCHSdBqD2CHdPaA'
    'RvDeRhCWoCGARpACAjDrRqAMPqOEM/ADZvCD4Enl4DJX7YSIiJDi+9EqKx4g6apl/uni/qml11mWyQTeF8oLWK8NrzP+AAPoXSbYAUuhhgx24ynNHJv+4ASl5tSEqIu92FtFYV'
    '3FoGElITd7Mw+yN9v0vbTgAk7gTRpG1ssAGh/aTQb4oTrwAGWYhEmwg9/2bd+mgUkQA7lmBoemhGEjqQWogD1z6FGYhidQZVWeBuLzM+ROv1X+S3V9sokg3XAyFK29YgFa3dfN'
    '11wujzBO7EklY5d7smGO4Ak+Zm/YAAv6izZePZrmvQ8+zTp2C1oN7WgzLLqtx7P1OS1N7WtbbfjCXtHUzQOIQuPeXAu9jKAp5OXzAN/2AztAAjuwBA9HAhFHAmDwB+p+gif4hC'
    'fgh1Fg/nEUSPFFwgMZxwM0wIMXTwPrtu4zoIQ0gGj7beXu5Ous8tc8Oad1CjL4SPIuploiMw8x9mXbrQ/8iOAPgIMQQABv4JCFHYyclenM6ba8otiSsQsCxWYDtZSC0uBmc7MN'
    'cbMOitK+1SDg2wEWiQwWmF9P3PE+owEP8IM+94NJEPEPtwRCJ/RVsIRV8IcsmEIZRwNHf3RHPwJIl4UIYIoIkIUmsPEnsG6HTr8WLUbuDt3v/ialTbmM9puNnskdtVRL9bGAef'
    'JJXWDvOooos3SnCIEgyPId2PI71e8vR6W2TXDXi4vVPCxcnYqqEIJe9z0heJlSYRnLebMXsDdChNDX/uad+BVIc0s/bj8DYIhrPxhxQoeFFYAFcz/3LMgCaCBGPJAFd690PTiB'
    'MiiDCKD3E5CFE3AIkYy4VMB0FM9x7cYDz31i5BLdirYIkDD1tHI1AEZPyBSJVv9fPEps2mW5WYcySKlyXPcGIuBjmPZ1TKkza0eowKIvMmdNjD0V10TzceYFexuhtkBEfTgAmu'
    'evTgEd+MpSjoltY6UM66ZuEw/6VQCGQ1+Fcjd3QYCFpJ8BaDhU7HT3H5D3RMpdqj+B3D0Beug76vAB9osANHhxTk8/iBZ4Vtbr+jn4IW81l0CnLC7gIbvGmTjg2V1s+XC5o8jd'
    'CGgKOBhbb7Bg2qGz/mbWbBkyzQgt6n14XlBazVPZAw+8lAxm9qZ8C/1iAiJ4nQXHW9celRUMS+1Og1PIglNYhVWAhdFXekE4fVZI/UQohdV/+h+IAKqHK7iKsijTAywkNT44o+'
    'K6g3O18ehOAx7f7u1U1yA/+EKRp9P938BpzP27roJp+JOwm5VrmPcegFovAaeI7L5ftzRPasG/xBDqirWI+cnfwAthxEpxfNzhimYvFSbgeI6n+R3wEBHEeRSpIXALSD77ec/P'
    'B3U3d4BgJWiggIIGtZQqlSpVhBNldOgoMyIdxYoT08GD54APgI4d6d2JgObJk2mUpqXJkg/PrIWpTpzIaEVClwBr/lT8sTAnCc9z4pKIyyU0Vi6iRIUizRU01xyhS50mjTrUqF'
    'Jx566eAzrHwp81AbpIsDJAx4kfEUrACRHCGxNOL9gkS8YLAq+6vOLGpYYX7127e6kJ6feCE6d9+pggfoUBg+JXjvVtyJRJiJC4du9meDGYExEiTNh97hxjRxEubKhRy6BXNTVP'
    '/YoUOSBFmjQxzM5MA5YmzSpY0GAlEsTK4EEtWhQszHYCoo4R79LdeOcMhrPq755vcbCRo8eQaFCMmiZ+N8uWqZTHpEgT3Zo/f+bAT3IVqLilVItKzQ9Vf9JYR6taJV9WW/2hwl'
    'dhDQCPDhFE0MQHanlDxD6ntXFZ/l17VabXXn1ZhhdqbLBRRCb7GIYYY4s1tscekU2ml4UZJENNP1zsQ4Q+7HjggTfsiEbaW6dlIIRqrr1WhBRH0iaGGLjptspv0AgSHHEFGaeA'
    'lehllM51NI3RxRhDeFmMBBIMMMAWfHDXkXLfPZHGSWlMsFJLstxxR0zwvDMmezjp1BNQPiFlVCD8BdXUU/xF5R9Sc9SH1SJJbKWCgWCJRdYJTaBlAAIs6MMJF5XJNdeFeZG6V4'
    'd3eYiaYEUUdsBhJ574yh6QSUaZZXaxxgUnO3TGzo4e8NgZaVz0w4YQqHkiBJGwFRGPbLPV5scZwKzSG3ACCDKlcccpcAc96jiQ/s4AM3k5xBChoKsCuuhQusWZ3IEkEkknUbJb'
    'PrOY91J66ax3kwU6/YRVfU3lMuh9iCIs1RyKElWfgI9CytUaa7SrIINNpBUEAkS4paGFf8WYDKinyoXXkGy8Rtg+iO0Rq2NM0PoWqJfF6AkbXMSgChHs4NgzjzuMRiwbyXpCZD'
    '8PNNvskVL0EK0f1PZGULbEcSuMD9+6a4UVXXQxsQpX/OHfFZKyG1Z2aALAxx16oIFHeOOlce8ssqRi5515drFnTjvJR99TFtw3KFKFMiUUwfoR3pR/R9VnFVYRd3VgpQtimrE3'
    '+uzwgouijipyyBqaGjqyILJK4mEmvgzzPpG9/nDsrZihxkUrvO7swSTsTAKssKUJ1k9rRR/9ANLMxmAkETn68bS1AxFEZZVX0+NA1jTZhNNRWwGuAsVkns2Rd3iUBHcWLLkEEz'
    'xavpO3v0wFnFXj+CkqOKH5yZ8UwYoO7uiAXE1KZoJlNchy+uCC5m5FF1Qlow0hWyBfQmWy0fVDZQdgwh5ewQQLUnAD+8gEAVHjwAu1gRqy20EddsYzYPFMWDvwFMpe4AkX9iOG'
    'wkPa8GJgQ+QhAQmWgMUKmDeQRCSiFMfJhre0UybqreEKFmAKT+DDvwCYbTv0yAbb2mSSafgjbvhKjvnwtJ5QqCAWAJOPVQY2FPwsUSqES5jh/tq4OKc06hwQi5RX2gWRCPwADm'
    'lBgDcOwAljhepjnvMgAzu0lwyE8IURLEKJWMYyfXQqE5oBnV9i5AIXFGEHJOQZ7jhJBJ0Nqx82A57RYmjKIrSiCDEooe1yaIlXriCWsABOEFOhAHpET3paq0l7YhGfJDyKQNsb'
    'gHb4AJJUtC18KNFivsynpX7xiVF/8smhqPIfNtYvKUtZGP6UgpX5CDMAxRBLgijXBAOEIAje2EEmThMqCBxwLwosZMlKhirWtLB0B1gZBSmoj31wgoOa81glY8SG2XHjk5zkJC'
    'h3wAXTDC0wMiqlKFGWylas8niTmAQS7AAMcujwlaeAxhaJ/hi9LYzLCgFAB07is4iXQqpAUDQTmqZ4Ajy4TTzLzMe9GGK38+FtT/9i1FUaV58zUmWJaWxjUw7HxqJ0M47um0OB'
    'vDKmMpHFLHBAJwskZBoD0iwuGQodh0w1OlYVZmWn++fqJGMsgl5GNS64mSY7UwNO1uCTqggliDyBLL8OrTXUuCQbXNAKLmSyM97I0UY3aodJAINaJFVIndShDpTOxCbu2clLIW'
    'aBSZlpI8eUBQp2M40zZFFu5VMHUKH5B/aVkZqBKsq/lJqLJRLMUE91Y1QdN9WqUipBFmsCCgygzk59anMH7FzoSFbW1FAjn63SxwSp+8+AsqGAgazkhw67/gNV6CyveQUlJw5b'
    'WL8KVrB+dYFgXeCJuaaSGxnlETvuyrNJ+AEJq7iXQrIhDKyNS33vmUNnHyWxLljhXfQQRgRkAT6d2muL+koPuaqXk6r4RLZnBFxt/2U/be6WtvhrXFHDGVwF6eAH5wzCGfrYMc'
    'vQZbkgMxWHEBijD8WQMPtEzARJ5Fbt2kXGlqQrr3SmihqAd6+alB172+DkEIaQGlCWsgucTNjDZnIH+/iuJo1sO2rNYBZWqtO34BHgAKigT52NKcVCy4dl3CEbbTNtGnQjt/6a'
    'bwB4s7BOGFXGoyL1X2Ls8KIKZ2g2vhGO1BTHwiKHYLEo6Ac/KO4ZWHCA/hW6M8iiqidZ7cnpZLBGMJs5AKmZsE+AugXIdYHnpmMkhIdq8rtG/uSWH9qKwlbZyeB4Mq973QbC3q'
    'w0Dx02F+rKjvxmARoJGXOZByABzVoAmDCl6hrGebZjRgB8QFhm3Ei6EJiwNh0Vbs+FSfy+QHG4w7jViU6Usp+EHcyoRwUuglA8aRQAQQw9OEAM3jLPVYe1uZ4u642F8IIc75O6'
    'rtonYVw4M1EJObougHWS9aGKDcT6oXN98q53nUAo+9rJ752rC4oFURBRHHfVCqKVFPBfB4zr2S2VtoFVgGBi0gMAd0iFgw2Qhtyk4RSq/bYOzDxuPrFv0UcNhLqbvtTB/kHFqf'
    'q5ZlDeF4srrKFsVkjHCFLMD3wvYN/7MA1cOWdjGtuT4KhpzWZaZWomkCjVQlDgquEp4w/BegcY36uSh13YX7eh4x5XYK93zWsp22ywUpbyryf+3UnYoTcsV8DVwOVszXL2pQu7'
    'whgS7AB6+GDn2bbiTiUMbjOPiZfR9POiAxEUMYoxJ+reSlPdDe+CqVEp94uFCoZQDGe8YyIQSQAKPgGEHuy7CAN9Hc3OjnaC50UzgtFxqU9NGHe+cy7xNOjNiv3dfVx8hQ7lwi'
    'WbHPjAJ6PjTk7gx9XvZMajhvDs/zUXwMtRWMwgEUO8Gma79h5p8wTvocM7aETOiR4e/uxGnaXE0ClH0cVcTUiK7DWKUc2W09WWwrhb7c1P1R2af6gLmERH1/1AAjSB8eVBD0iB'
    'YBDSdl2I8z3fp63dwUXQPiycqflYP7iOXNhdxHVfrHHZkj0UiOSarp2f+hleESIhODDehsRF430XO9gBEvhGKTCbLtVETtBcEuQC50nAFqiDATIEHuTDttWZAeSDt31buGUWn8'
    'HHBJ6bUTQd7S3V4WggorxPodTWH1xBKKDDGMDADXSd14Hdvj2A78DIwHmaWXWa2g1J21UfdTVcAQEcq11IdPXgd22AKtRaEF4S4xGhERLh+SWhlO0FONgFOOya49WAMkQeNChb'
    '3WBN/mbtDUydQyBcwQDiXOiFYT783G4I3RZFQAMaHRKt3p8BWsFY4AXmXtRJBeMYVVP8ix6qADqggzPcQDokQIoRFwqEnRQUAQ4eYo0lYnOBjiEdkiUiHA0ehvVpBowEWYzdRQ'
    'jNlfcVmQ+axsbxGii6n+GBoigqkCkGEjgkwyVpEu4Aw0i1hJ1YIZpFGwBuYRc4QwHqXBjuBhAkIH9FQBq2Fi+5B8A4zrltGFGwG8E8HYgVWn4UlRlFo/agQzHcwA1AhIoRFxCw'
    'QA/EgyhlgIUwl+jQE188F7K8AFo94nVpRmXUHasJ5K8dVF2BFxFkHPkNYeGJIj+GIlWS4j+a4imm/mKxqYIHBAEw3EswnsD0MCTNBcUVDME7eCHoHWBpAd0vmgdMUBgx7s1PfG'
    'R9DArTFcVWCIVS8WVUbJOhSZ1QCAyj3VaBGIiYXGOKNcg5Hd8BFIEnvBMluiBPUpI5ghpQRpDb8dgGtcjrHBAq0h8XcEORfZJTkgZhSeVqruYR5iMq1sUu8IJotsFD6YwHnEHc'
    'mAVrbUFmpRmBad5DduHnTWQE8BRKlF4zpUdQ+csYZdgx4kehOVVJftjhHEoujIPAYE9VHQjXmYWKbVVNckI/5OQOstqngUw5MqGN4VORcAZ1qQ5AHVw4wqNovtfs0M7OfFLQXN'
    'KTJRBV+pr7hVzh/sHmKSaQ4xGBN5wBEOCBpOlA1kCgmj2KcEpkW/6cbsAlni2nazmn0p1RdDJFuyGMdX5YUGQnOFEVd0rAc5DFWZSAAQBBEPRAZOogBFSC3Y2KXoBKOeqFeqIK'
    'AkGXIqXVBCGGjxUlC85mKh5WHZTQXZ3mDnDDreVaP7Imxw0ox6GibO4CKu4ayh1AD4jBNKAACpDFMDIkcEJKLqjAGKglcR4gnUXYLGSkXJ4Pv6iPEjnnnyGFXubHYPYpU0XFOJ'
    'woo62kVW3dHZUAxoSApRVBasBTJUDqeXpIqQiccz1QdM2IKq2MZ6hOrQjJJKJiBsCXJtXBQrFDHZBGK0wpl14p/msa3jX8mjwAHpfOZl2Ipgu8QLERgRgswJhChJn+prQFBR+K'
    'xUaE3h3MAh64ZW4yU/ksZ/rsiRj9hIBoWF/+Rx3Oln7kFqAKalZEjMRsD4sySKKmhRhAJjXkwKNGajz1aCHt6HrCIFCiFT/FZ624o4WkogtAaa940icd1iV1XAbQZqvmI6zyWl'
    'RmKS9sKW3eTAxIQw9MwyeQqQP6pk7AVBJ8VheoJdq8aS/G6ULYTdHhzRAk0WtJE080juLAT4idJMEE5hx0q0/Ah3sYCBRZgYKcAIN8ABzk2wH4TrpCatDCE16E0KQKXF+IY2Zi'
    '6gy6Cqf+kyQlS/Yl6a/hZ6my/oMyoBA7cEOU5loVsGoVPJnBtoHBwirYAqiV8ZrXgoOW0ubExcAB8Oon8MMPUKzM/QFPQMzVIdjZAIAPZIODWRGzDp2+1KkEwAB74Kld9g2g1d'
    'Y12V5+OC4Gulu3NlGhUko6tCi5ToMYpKA88EI3BG2k2ir7qWcD6SRzQdeqZEIM0CtbuYWQ6OCmgcM8coPVKkNjnaom9UOVCSw4qG2vRaWvge2TyeqveYKuZenazqaVqdJsLIDc'
    'ZiNmyZyEisNndV52AADo8dyDjYfQ9VQE/JQXqQ9OsA9PoKwTpRt1XifCvCxTnOj+gKvNYm7ONsgYcm4/XEMOgG7QdkM3KGwT/n7OeiJtC3KaaijLwaUVp3Zq6+QkwMWj4/FKDd'
    'jORuEIEdQB1zqZ2oKDwBKs2SLh+yHs2priwjYeRklB3PLDr8Ycmt1tZ1WvzXkeACzDFDnYz6FEbg6uM11HF5AsnvKN+0AK9nAFh7Hsnxoa5RIq/xgq5i6IiuEb57aDPOhvJSwB'
    '/46uApUj0iJpQd0YNRxcJqQVYjCBjTQc7MLjA7PBd5Xq7eLuqaKSewUel7pmGxRvgLbB8A5vlQ3hNWTplm4prB6Ww/IqCvDDQ5BlsGqeBVzB3qKND2yvMqUW+ZyH+ehAUIGRtE'
    '5rEwmx7AHOMq4vf+QWzM5HENOsVUkARrQo/nGlgRjQgiLIwzd0QxUvQRV3wzegIgAL8GUsFwHrqCLNYOsaqWQ68AMXGzecUGPlDpPuwK1xHAcP75U+sz8ab67xsQizbeMpQgxI'
    'ATPQwSeggQpXLJpibChYmwN0RJwBrk6hRA4/q4CJkTQBMfoOcSeHWOS+2/smMXciGEU08Q/kwzQwAy08gBR/wyzTsv8m6SK+Y4wJWV6ghmZIkD447QYx8DAfKFeWKjJj7alyA5'
    'N9ojT32jPPMXtV2WCtqh+DwzVcwyXJVyMwAyXIrSGvMCIvwlYQ67vM8CNfUSS3BPh2kSWHkQUoriarW9jcVu4FJqJs6xycQ3ZqBYFojzid/jJz4FHxBbQrT0FBy3Il1PJskq5P'
    'TuI3wNM3BJyQHEsMbQYwb1CyuKOM0R+UctIksDGwXPAy92co2nGr6vHInbQ1K2k2S0MeTAM/pPCDntlvwlT1hgIjv5nfJpM6N+u3tbNQOSdQBHE0dpg9t1ERn6hWFOpXWAEBZh'
    'VxATQtOEIYTEEsG3T/ju7zrZpYQwBsbxqqxGBgDMY+ESlbSdKnOvBFF+R9NRZd10Fp/J0nJuFH+5oelx9JIy/bpvQlFQEtSAM3P0ECyHQ4AxNQWAA5Jxja0APPoUBJvMkCmgeW'
    'iG8Pm2zAnO8mA449c+ChJUxTPA6jpWhUj9M7xGRVp8FV/stDVm81a3v1PDGfWBN4bMd2Qa2djCwSiSCGZwQzqHFO+rXBQbWCKpTqBG9UjtSBKkQpVF6p4OE14JGcEP5dc4/wk7'
    'VCNrt0xFq3DojL1rAw3mr3YsfwgskZ91ICDuML3dTNvvRL2Ah1Jv8E+uaEGIGo5A5mNiUFEjuRPm/d/KoYHpR2CkixG7iBLAO4QDJQVhY4LENALYcmXlTGASMwDRIp3Mkn7H7M'
    'aCbUMdsOCqHqMuNar/2naA4s2uJaYQlhf9KqbK6tk6W4wzIDi0NE/51pdi/Mmnb3m+0caYk3FsWNJP/UM/HwTbxzT1CTPHPYUdTPUyQ1G+Hzdka1xuJ3/otOWmkrQgGIgGoL7T'
    'c0l12QdWz3b/+KtYF+TnQRicp4xmE8LQNnn4RPXIUzKY7kTu6cKqp2NPkVlnELXj8S1lzdzMQZ1hBuKS+Q9ZY2nio1Qh6MQkzrQJn45v81USzQON82OgJCNjtnxA5HK8D4hPnK'
    'M+zZ4Uk+VWeTspOjMh41gZQH9EBnNRVTcTdsH+hkpbUT+KwTeCUdy4dkF6uw7um4iny+wL36hVJC6Q6cEO68+bE7lJSyAcj9Yxzf+ccXFvnJzkHNecIq7NS2A2CLAUxb9wgYOi'
    'JDCu8VQ5viUpyxyUlAupx8m51sJDqA0b84TEoaZicfjLZCHXznR2fn/vOohzZElMWkAQF/58CVVzFXb98CjfDB0zqtQ4Cfp8pZr0qrcKqR2grNpOJSDjtjAQtdc/iwlR+U1bkc'
    'i+KIm/zE4VqVqa1dLCx0x4BLd3Nhiwv1zNy4L3abZu+5P/rHSnbhju87qzd9HA7+uDegMr1+hDpUm3K+N0hp5YEUUHlqgy4t04XRbtc3wDIsuwGYkzWQrt0LhQiruArMoLlkeE'
    'I4nqJStkJpMunbG/upoua/LjvHpZ/dOxnJS/uw/Sufc7mtzi4mOaxgx7TMH7a4AwW5X+/ngZ5IuCWEjU9563D6kGxQ//C7G6Y1ZWtUuKxgQi7uOb2o19Ghjja/t3KV/s8ypAo8'
    'BDSXKaq+rANEN4ECv/HitStZsjbJhFCjxoZNv36cOB0gcoAJk337Mr0QIiSZQYPJwLWh1ooLtxh12HlwyW6SB3Z16uzYwYWLCzYu2vBc2AYcOJJC2xTV6QJnUhetdvIMmmOXyK'
    'DU2hWJ0UjMtE8JyuhIN8BKlwAqLMxJcnZOrFBd3m1xQA/AnVSyUDyhNG2avzT5Zs1KFSHViRPwdLyT0AXdGrJlxZ1r7FhcLsm5AuWKZXny5MiSN8/J5flzZtG5xp07h3bOnz8q'
    '1gSQICFdOh0RIvxAAYQZrQfyRAistKQSBAgjExY3GPVbt29ulif/VpCXUIYOqXmC/likCKd9B/QxIaKPY8cMCUVGN9pqBzeaLWHKnKkqvdKd1H4GtR/U6M4XOZOidPEfKHBEKg'
    'g/NhSJQZo8RvmEnwTg+eq1sf4wCy21xrDCLXrouUMWup6Y5q409uorlVTuEOzBd95BLBQVYmEsidMaE2ezQCy4bLTMQNsxl81Ew/Gy0kwTZw4LLFittS6skE2HE35oAoVpmJFC'
    'kWtycAO4SirpZjheEgIpIQG/geA5gdwYaEyDpKPPIYj6eaGIHSzKSB/wOHnhhfFCGqkkapDiZoc6iGjpJZmIENSmVo4qqqihBMSvKD93Sqq/pgI0CDqhXKgKQTEo2aqMEbYY4D'
    'AJMylMwrJQ0GlLHQ3lQgOPNPDKay88/CoRRXgMQ0wxI806DTIfL7usMhxz9AxZyUDLUbKAAAA7'
)
# end images cache

#
#
#########################################
